{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>A vulnerability was found in RDFlib pyrdfa3 and classified as problematic. This issue affects the function <code>_get_option</code> of the file <code>pyRdfa/__init__.py</code>. The manipulation leads to cross site scripting. The attack may be initiated remotely. The name of the patch is ffd1d62dd50d5f4190013b39cedcdfbd81f3ce3e. It is recommended to apply a patch to fix this issue. The identifier VDB-215249 was assigned to this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-4396\">https://nvd.nist.gov/vuln/detail/CVE-2022-4396</a></li>\n<li><a href=\"https://github.com/RDFLib/pyrdfa3/pull/40\">https://github.com/RDFLib/pyrdfa3/pull/40</a></li>\n<li><a href=\"https://github.com/RDFLib/pyrdfa3/commit/ffd1d62dd50d5f4190013b39cedcdfbd81f3ce3e\">https://github.com/RDFLib/pyrdfa3/commit/ffd1d62dd50d5f4190013b39cedcdfbd81f3ce3e</a></li>\n<li><a href=\"https://vuldb.com/?id.215249\">https://vuldb.com/?id.215249</a></li>\n<li><a href=\"https://github.com/RDFLib/pyrdfa3/issues/38\">https://github.com/RDFLib/pyrdfa3/issues/38</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-894q-wpg5-mf2h\">https://github.com/advisories/GHSA-894q-wpg5-mf2h</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-894q-wpg5-mf2h",
            "title": "[pyRdfa3] pyRdfa3 Cross-site Scripting vulnerability",
            "date_modified": "2024-04-08T17:20:48.000Z",
            "date_published": "2022-12-10T12:30:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-894q-wpg5-mf2h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in OFPMatch in parser.py in Faucet SDN Ryu version 4.34, allows remote attackers to cause a denial of service (DoS) (infinite loop).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-28732\">https://nvd.nist.gov/vuln/detail/CVE-2024-28732</a></li>\n<li><a href=\"https://github.com/faucetsdn/ryu/issues/188\">https://github.com/faucetsdn/ryu/issues/188</a></li>\n<li><a href=\"https://gist.github.com/ErodedElk/1133d64dde2d92393a065edc9b243792\">https://gist.github.com/ErodedElk/1133d64dde2d92393a065edc9b243792</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p28x-hj68-7vfp\">https://github.com/advisories/GHSA-p28x-hj68-7vfp</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p28x-hj68-7vfp",
            "title": "[ryu] Ryu Infinite Loop vulnerability",
            "date_modified": "2024-04-08T16:46:54.000Z",
            "date_published": "2024-04-08T15:30:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p28x-hj68-7vfp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Versions of the package pymongo before 4.6.3 are vulnerable to Out-of-bounds Read in the bson module. Using the crafted payload the attacker could force the parser to deserialize unmanaged memory. The parser tries to interpret bytes next to buffer and throws an exception with string. If the following bytes are not printable UTF-8 the parser throws an exception with a single byte.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-21506\">https://nvd.nist.gov/vuln/detail/CVE-2024-21506</a></li>\n<li><a href=\"https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2\">https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2</a></li>\n<li><a href=\"https://gist.github.com/keltecc/62a7c2bf74a997d0a7b48a0ff3853a03\">https://gist.github.com/keltecc/62a7c2bf74a997d0a7b48a0ff3853a03</a></li>\n<li><a href=\"https://security.snyk.io/vuln/SNYK-PYTHON-PYMONGO-6370597\">https://security.snyk.io/vuln/SNYK-PYTHON-PYMONGO-6370597</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cr6f-gf5w-vhrc\">https://github.com/advisories/GHSA-cr6f-gf5w-vhrc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cr6f-gf5w-vhrc",
            "title": "[pymongo] PyMongo Out-of-bounds Read in the bson module",
            "date_modified": "2024-04-08T15:40:18.000Z",
            "date_published": "2024-04-06T06:31:08.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cr6f-gf5w-vhrc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Lektor before 3.3.11 does not sanitize DB path traversal. Thus, shell commands might be executed via a file that is added to the templates directory, if the victim's web browser accesses an untrusted website that uses JavaScript to send requests to localhost port 5000, and the web browser is running on the same machine as the \"lektor server\" command.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-28335\">https://nvd.nist.gov/vuln/detail/CVE-2024-28335</a></li>\n<li><a href=\"https://github.com/lektor/lektor/pull/1179/commits/8f38b9713d152622b69ff5e3b1e6a0d7bb7fa800\">https://github.com/lektor/lektor/pull/1179/commits/8f38b9713d152622b69ff5e3b1e6a0d7bb7fa800</a></li>\n<li><a href=\"https://brave.com/privacy-updates/27-localhost-permission\">https://brave.com/privacy-updates/27-localhost-permission</a></li>\n<li><a href=\"https://cxsecurity.com/issue/WLB-2024030043\">https://cxsecurity.com/issue/WLB-2024030043</a></li>\n<li><a href=\"https://getlektor.com/docs/quickstart\">https://getlektor.com/docs/quickstart</a></li>\n<li><a href=\"https://github.com/lektor/lektor/releases/tag/v3.3.11\">https://github.com/lektor/lektor/releases/tag/v3.3.11</a></li>\n<li><a href=\"https://packetstormsecurity.com/files/177708/Lektor-Static-CMS-3.3.10-Arbitrary-File-Upload-Remote-Code-Execution.html\">https://packetstormsecurity.com/files/177708/Lektor-Static-CMS-3.3.10-Arbitrary-File-Upload-Remote-Code-Execution.html</a></li>\n<li><a href=\"https://github.com/lektor/lektor/commit/7393d87bd354e43120937789956175064e4610a0\">https://github.com/lektor/lektor/commit/7393d87bd354e43120937789956175064e4610a0</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/lektor/PYSEC-2024-49.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/lektor/PYSEC-2024-49.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wv28-7fpw-fj49\">https://github.com/advisories/GHSA-wv28-7fpw-fj49</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wv28-7fpw-fj49",
            "title": "[Lektor] Lektor does not sanitize database path traversal",
            "date_modified": "2024-04-07T05:00:47.000Z",
            "date_published": "2024-03-27T06:30:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wv28-7fpw-fj49"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Lektor before 3.3.11 does not sanitize DB path traversal. Thus, shell commands might be executed via a file that is added to the templates directory, if the victim's web browser accesses an untrusted website that uses JavaScript to send requests to localhost port 5000, and the web browser is running on the same machine as the \"lektor server\" command.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-28335\">https://nvd.nist.gov/vuln/detail/CVE-2024-28335</a></li>\n<li><a href=\"https://github.com/lektor/lektor/pull/1179/commits/8f38b9713d152622b69ff5e3b1e6a0d7bb7fa800\">https://github.com/lektor/lektor/pull/1179/commits/8f38b9713d152622b69ff5e3b1e6a0d7bb7fa800</a></li>\n<li><a href=\"https://brave.com/privacy-updates/27-localhost-permission\">https://brave.com/privacy-updates/27-localhost-permission</a></li>\n<li><a href=\"https://cxsecurity.com/issue/WLB-2024030043\">https://cxsecurity.com/issue/WLB-2024030043</a></li>\n<li><a href=\"https://getlektor.com/docs/quickstart\">https://getlektor.com/docs/quickstart</a></li>\n<li><a href=\"https://github.com/lektor/lektor/releases/tag/v3.3.11\">https://github.com/lektor/lektor/releases/tag/v3.3.11</a></li>\n<li><a href=\"https://packetstormsecurity.com/files/177708/Lektor-Static-CMS-3.3.10-Arbitrary-File-Upload-Remote-Code-Execution.html\">https://packetstormsecurity.com/files/177708/Lektor-Static-CMS-3.3.10-Arbitrary-File-Upload-Remote-Code-Execution.html</a></li>\n<li><a href=\"https://github.com/lektor/lektor/commit/7393d87bd354e43120937789956175064e4610a0\">https://github.com/lektor/lektor/commit/7393d87bd354e43120937789956175064e4610a0</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/lektor/PYSEC-2024-49.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/lektor/PYSEC-2024-49.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wv28-7fpw-fj49\">https://github.com/advisories/GHSA-wv28-7fpw-fj49</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wv28-7fpw-fj49",
            "title": "[Lektor] Lektor does not sanitize database path traversal",
            "date_modified": "2024-04-07T05:00:47.000Z",
            "date_published": "2024-03-27T06:30:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wv28-7fpw-fj49"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>pgAdmin &lt;= 8.4 is affected by a  Remote Code Execution (RCE) vulnerability through the validate binary path API. This vulnerability allows attackers to execute arbitrary code on the server hosting PGAdmin, posing a severe risk to the database management system's integrity and the security of the underlying data.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-3116\">https://nvd.nist.gov/vuln/detail/CVE-2024-3116</a></li>\n<li><a href=\"https://github.com/pgadmin-org/pgadmin4/issues/7326\">https://github.com/pgadmin-org/pgadmin4/issues/7326</a></li>\n<li><a href=\"https://gist.github.com/aelmokhtar/689a8be7e3bd535ec01992d8ec7b2b98\">https://gist.github.com/aelmokhtar/689a8be7e3bd535ec01992d8ec7b2b98</a></li>\n<li><a href=\"https://github.com/pgadmin-org/pgadmin4/commit/fbbbfe22dd468bcfef1e1f833ec32289a6e56a8b\">https://github.com/pgadmin-org/pgadmin4/commit/fbbbfe22dd468bcfef1e1f833ec32289a6e56a8b</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-27jx-ffw8-xrqv\">https://github.com/advisories/GHSA-27jx-ffw8-xrqv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-27jx-ffw8-xrqv",
            "title": "[pgadmin4] pgAdmin Remote Code Execution (RCE) vulnerability",
            "date_modified": "2024-04-04T17:01:58.000Z",
            "date_published": "2024-04-04T15:30:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-27jx-ffw8-xrqv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><em>What kind of vulnerability is it? Who is impacted?</em>\nSSRF vulnerability in firebase database check logic. The attacker can cause the server to make a connection to internal-only services within the organization’s infrastructure. When malicious app is uploaded to Static analyzer, it is possible to make internal requests.</p>\n<p>Credits:  Oleg Surnin (Positive Technologies).</p>\n<h3 id=\"patches\">Patches</h3>\n<p><em>Has the problem been patched? What versions should users upgrade to?</em>\nv3.9.8 and above</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p><em>Is there a way for users to fix or remediate the vulnerability without upgrading?</em>\nCode level patch</p>\n<h3 id=\"references\">References</h3>\n<p><em>Are there any links users can visit to find out more?</em>\n<a href=\"https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2373\">https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2373</a></p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/MobSF/Mobile-Security-Framework-MobSF/security/advisories/GHSA-wpff-wm84-x5cx\">https://github.com/MobSF/Mobile-Security-Framework-MobSF/security/advisories/GHSA-wpff-wm84-x5cx</a></li>\n<li><a href=\"https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2373\">https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2373</a></li>\n<li><a href=\"https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/43bb71d115d78c03faa82d75445dd908e9b32716\">https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/43bb71d115d78c03faa82d75445dd908e9b32716</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-31215\">https://nvd.nist.gov/vuln/detail/CVE-2024-31215</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wpff-wm84-x5cx\">https://github.com/advisories/GHSA-wpff-wm84-x5cx</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wpff-wm84-x5cx",
            "title": "[mobsf] Mobile Security Framework (MobSF) vulnerable to SSRF in firebase database check",
            "date_modified": "2024-04-04T20:24:59.000Z",
            "date_published": "2024-04-04T14:39:03.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wpff-wm84-x5cx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The LDAP auth backend (airflow.contrib.auth.backends.ldap_auth) prior to Apache Airflow 1.10.1 was misconfigured and contained improper checking of exceptions which disabled server certificate checking.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-20245\">https://nvd.nist.gov/vuln/detail/CVE-2018-20245</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-77rc-x84q-pv4f\">https://github.com/advisories/GHSA-77rc-x84q-pv4f</a></li>\n<li><a href=\"https://lists.apache.org/thread.html/b549c7573b342a6e457e5a3225c33054244343927bbfb2a4cdc4cf73@%3Cdev.airflow.apache.org%3E\">https://lists.apache.org/thread.html/b549c7573b342a6e457e5a3225c33054244343927bbfb2a4cdc4cf73@%3Cdev.airflow.apache.org%3E</a></li>\n<li><a href=\"https://github.com/apache/airflow/commit/28abf87bd173cc4cedc57f553118470e5745a968\">https://github.com/apache/airflow/commit/28abf87bd173cc4cedc57f553118470e5745a968</a></li>\n<li><a href=\"https://github.com/apache/airflow/commit/66d0d05ea0802aec407e0ef5435a962080db0926\">https://github.com/apache/airflow/commit/66d0d05ea0802aec407e0ef5435a962080db0926</a></li>\n<li><a href=\"https://github.com/apache/airflow/commit/d8d0e8c59203f793f81d47d5adb1362df0b5d8d1\">https://github.com/apache/airflow/commit/d8d0e8c59203f793f81d47d5adb1362df0b5d8d1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-77rc-x84q-pv4f",
            "title": "[apache-airflow] Improper Certificate Validation in Apache Airflow",
            "date_modified": "2024-04-04T05:01:06.000Z",
            "date_published": "2019-01-25T16:19:19.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-77rc-x84q-pv4f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Pillow before 8.2.0. For EPS data, the readline implementation used in EPSImageFile has to deal with any combination of \\r and \\n as line endings. It used an accidentally quadratic method of accumulating lines while looking for a line ending. A malicious EPS file could use this to perform a DoS of Pillow in the open phase, before an image was accepted for opening.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-28677\">https://nvd.nist.gov/vuln/detail/CVE-2021-28677</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/pull/5377\">https://github.com/python-pillow/Pillow/pull/5377</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28677-fix-eps-dos-on-open\">https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28677-fix-eps-dos-on-open</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202107-33\">https://security.gentoo.org/glsa/202107-33</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html\">https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/5a5e6db0abf4e7a638fb1b3408c4e495a096cb92\">https://github.com/python-pillow/Pillow/commit/5a5e6db0abf4e7a638fb1b3408c4e495a096cb92</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q5hq-fp76-qmrc\">https://github.com/advisories/GHSA-q5hq-fp76-qmrc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q5hq-fp76-qmrc",
            "title": "[Pillow] Uncontrolled Resource Consumption in Pillow",
            "date_modified": "2024-04-03T20:32:04.000Z",
            "date_published": "2021-06-08T18:49:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q5hq-fp76-qmrc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-46695\">https://nvd.nist.gov/vuln/detail/CVE-2023-46695</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f\">https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f</a></li>\n<li><a href=\"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e\">https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e</a></li>\n<li><a href=\"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b\">https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20231214-0001\">https://security.netapp.com/advisory/ntap-20231214-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/nov/01/security-releases\">https://www.djangoproject.com/weblog/2023/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq\">https://github.com/advisories/GHSA-qmf9-6jqf-j8fq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq",
            "title": "[Django] Django potential denial of service vulnerability in UsernameField on Windows",
            "date_modified": "2024-04-03T15:32:07.000Z",
            "date_published": "2023-11-02T06:30:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-46695\">https://nvd.nist.gov/vuln/detail/CVE-2023-46695</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f\">https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f</a></li>\n<li><a href=\"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e\">https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e</a></li>\n<li><a href=\"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b\">https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20231214-0001\">https://security.netapp.com/advisory/ntap-20231214-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/nov/01/security-releases\">https://www.djangoproject.com/weblog/2023/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq\">https://github.com/advisories/GHSA-qmf9-6jqf-j8fq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq",
            "title": "[Django] Django potential denial of service vulnerability in UsernameField on Windows",
            "date_modified": "2024-04-03T15:32:07.000Z",
            "date_published": "2023-11-02T06:30:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-46695\">https://nvd.nist.gov/vuln/detail/CVE-2023-46695</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f\">https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f</a></li>\n<li><a href=\"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e\">https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e</a></li>\n<li><a href=\"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b\">https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20231214-0001\">https://security.netapp.com/advisory/ntap-20231214-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/nov/01/security-releases\">https://www.djangoproject.com/weblog/2023/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq\">https://github.com/advisories/GHSA-qmf9-6jqf-j8fq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq",
            "title": "[Django] Django potential denial of service vulnerability in UsernameField on Windows",
            "date_modified": "2024-04-03T15:32:07.000Z",
            "date_published": "2023-11-02T06:30:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45452\">https://nvd.nist.gov/vuln/detail/CVE-2021-45452</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1\">https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1</a></li>\n<li><a href=\"https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b\">https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b</a></li>\n<li><a href=\"https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6\">https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security\">https://docs.djangoproject.com/en/4.0/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220121-0005\">https://security.netapp.com/advisory/ntap-20220121-0005</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases\">https://www.djangoproject.com/weblog/2022/jan/04/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jrh2-hc4r-7jwx\">https://github.com/advisories/GHSA-jrh2-hc4r-7jwx</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jrh2-hc4r-7jwx",
            "title": "[Django] Directory-traversal in Django",
            "date_modified": "2024-04-03T15:00:48.000Z",
            "date_published": "2022-01-12T19:21:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jrh2-hc4r-7jwx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45452\">https://nvd.nist.gov/vuln/detail/CVE-2021-45452</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1\">https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1</a></li>\n<li><a href=\"https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b\">https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b</a></li>\n<li><a href=\"https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6\">https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security\">https://docs.djangoproject.com/en/4.0/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220121-0005\">https://security.netapp.com/advisory/ntap-20220121-0005</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases\">https://www.djangoproject.com/weblog/2022/jan/04/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jrh2-hc4r-7jwx\">https://github.com/advisories/GHSA-jrh2-hc4r-7jwx</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jrh2-hc4r-7jwx",
            "title": "[Django] Directory-traversal in Django",
            "date_modified": "2024-04-03T15:00:48.000Z",
            "date_published": "2022-01-12T19:21:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jrh2-hc4r-7jwx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45452\">https://nvd.nist.gov/vuln/detail/CVE-2021-45452</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1\">https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1</a></li>\n<li><a href=\"https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b\">https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b</a></li>\n<li><a href=\"https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6\">https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security\">https://docs.djangoproject.com/en/4.0/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220121-0005\">https://security.netapp.com/advisory/ntap-20220121-0005</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases\">https://www.djangoproject.com/weblog/2022/jan/04/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jrh2-hc4r-7jwx\">https://github.com/advisories/GHSA-jrh2-hc4r-7jwx</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jrh2-hc4r-7jwx",
            "title": "[Django] Directory-traversal in Django",
            "date_modified": "2024-04-03T15:00:48.000Z",
            "date_published": "2022-01-12T19:21:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jrh2-hc4r-7jwx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-31047\">https://nvd.nist.gov/vuln/detail/CVE-2023-31047</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd\">https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd</a></li>\n<li><a href=\"https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64\">https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64</a></li>\n<li><a href=\"https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965\">https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230609-0008\">https://security.netapp.com/advisory/ntap-20230609-0008</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/may/03/security-releases\">https://www.djangoproject.com/weblog/2023/may/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r3xc-prgr-mg9p\">https://github.com/advisories/GHSA-r3xc-prgr-mg9p</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p",
            "title": "[Django] Django bypasses validation when using one form field to upload multiple files",
            "date_modified": "2024-04-03T14:59:16.000Z",
            "date_published": "2023-05-07T03:30:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-31047\">https://nvd.nist.gov/vuln/detail/CVE-2023-31047</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd\">https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd</a></li>\n<li><a href=\"https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64\">https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64</a></li>\n<li><a href=\"https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965\">https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230609-0008\">https://security.netapp.com/advisory/ntap-20230609-0008</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/may/03/security-releases\">https://www.djangoproject.com/weblog/2023/may/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r3xc-prgr-mg9p\">https://github.com/advisories/GHSA-r3xc-prgr-mg9p</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p",
            "title": "[Django] Django bypasses validation when using one form field to upload multiple files",
            "date_modified": "2024-04-03T14:59:16.000Z",
            "date_published": "2023-05-07T03:30:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-31047\">https://nvd.nist.gov/vuln/detail/CVE-2023-31047</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd\">https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd</a></li>\n<li><a href=\"https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64\">https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64</a></li>\n<li><a href=\"https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965\">https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230609-0008\">https://security.netapp.com/advisory/ntap-20230609-0008</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/may/03/security-releases\">https://www.djangoproject.com/weblog/2023/may/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r3xc-prgr-mg9p\">https://github.com/advisories/GHSA-r3xc-prgr-mg9p</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p",
            "title": "[Django] Django bypasses validation when using one form field to upload multiple files",
            "date_modified": "2024-04-03T14:59:16.000Z",
            "date_published": "2023-05-07T03:30:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in the Multipart Request Parser in Django 3.2 before 3.2.18, 4.0 before 4.0.10, and 4.1 before 4.1.7. Passing certain inputs (e.g., an excessive number of parts) to multipart forms could result in too many open files or memory exhaustion, and provided a potential vector for a denial-of-service attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-24580\">https://nvd.nist.gov/vuln/detail/CVE-2023-24580</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2023/02/14/1\">http://www.openwall.com/lists/oss-security/2023/02/14/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/628b33a854a9c68ec8a0c51f382f304a0044ec92\">https://github.com/django/django/commit/628b33a854a9c68ec8a0c51f382f304a0044ec92</a></li>\n<li><a href=\"https://github.com/django/django/commit/83f1ea83e4553e211c1c5a0dfc197b66d4e50432\">https://github.com/django/django/commit/83f1ea83e4553e211c1c5a0dfc197b66d4e50432</a></li>\n<li><a href=\"https://github.com/django/django/commit/a665ed5179f5bbd3db95ce67286d0192eff041d8\">https://github.com/django/django/commit/a665ed5179f5bbd3db95ce67286d0192eff041d8</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2023/02/msg00023.html\">https://lists.debian.org/debian-lts-announce/2023/02/msg00023.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.1/releases/security\">https://docs.djangoproject.com/en/4.1/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230316-0006\">https://security.netapp.com/advisory/ntap-20230316-0006</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/feb/14/security-releases\">https://www.djangoproject.com/weblog/2023/feb/14/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2hrw-hx67-34x6\">https://github.com/advisories/GHSA-2hrw-hx67-34x6</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2hrw-hx67-34x6",
            "title": "[Django] Resource exhaustion in Django",
            "date_modified": "2024-04-03T14:58:09.000Z",
            "date_published": "2023-02-15T03:30:47.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2hrw-hx67-34x6"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in the Multipart Request Parser in Django 3.2 before 3.2.18, 4.0 before 4.0.10, and 4.1 before 4.1.7. Passing certain inputs (e.g., an excessive number of parts) to multipart forms could result in too many open files or memory exhaustion, and provided a potential vector for a denial-of-service attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-24580\">https://nvd.nist.gov/vuln/detail/CVE-2023-24580</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2023/02/14/1\">http://www.openwall.com/lists/oss-security/2023/02/14/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/628b33a854a9c68ec8a0c51f382f304a0044ec92\">https://github.com/django/django/commit/628b33a854a9c68ec8a0c51f382f304a0044ec92</a></li>\n<li><a href=\"https://github.com/django/django/commit/83f1ea83e4553e211c1c5a0dfc197b66d4e50432\">https://github.com/django/django/commit/83f1ea83e4553e211c1c5a0dfc197b66d4e50432</a></li>\n<li><a href=\"https://github.com/django/django/commit/a665ed5179f5bbd3db95ce67286d0192eff041d8\">https://github.com/django/django/commit/a665ed5179f5bbd3db95ce67286d0192eff041d8</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2023/02/msg00023.html\">https://lists.debian.org/debian-lts-announce/2023/02/msg00023.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.1/releases/security\">https://docs.djangoproject.com/en/4.1/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230316-0006\">https://security.netapp.com/advisory/ntap-20230316-0006</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/feb/14/security-releases\">https://www.djangoproject.com/weblog/2023/feb/14/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2hrw-hx67-34x6\">https://github.com/advisories/GHSA-2hrw-hx67-34x6</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2hrw-hx67-34x6",
            "title": "[Django] Resource exhaustion in Django",
            "date_modified": "2024-04-03T14:58:09.000Z",
            "date_published": "2023-02-15T03:30:47.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2hrw-hx67-34x6"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}