{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>In Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, <code>EmailValidator</code> and <code>URLValidator</code> are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-36053\">https://nvd.nist.gov/vuln/detail/CVE-2023-36053</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/454f2fb93437f98917283336201b4048293f7582\">https://github.com/django/django/commit/454f2fb93437f98917283336201b4048293f7582</a></li>\n<li><a href=\"https://github.com/django/django/commit/ad0410ec4f458aa39803e5f6b9a3736527062dcd\">https://github.com/django/django/commit/ad0410ec4f458aa39803e5f6b9a3736527062dcd</a></li>\n<li><a href=\"https://github.com/django/django/commit/b7c5feb35a31799de6e582ad6a5a91a9de74e0f9\">https://github.com/django/django/commit/b7c5feb35a31799de6e582ad6a5a91a9de74e0f9</a></li>\n<li><a href=\"https://github.com/django/django/commit/beb3f3d55940d9aa7198bf9d424ab74e873aec3d\">https://github.com/django/django/commit/beb3f3d55940d9aa7198bf9d424ab74e873aec3d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-100.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-100.yaml</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2023/07/msg00022.html\">https://lists.debian.org/debian-lts-announce/2023/07/msg00022.html</a></li>\n<li><a href=\"https://www.debian.org/security/2023/dsa-5465\">https://www.debian.org/security/2023/dsa-5465</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/jul/03/security-releases\">https://www.djangoproject.com/weblog/2023/jul/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jh3w-4vvf-mjgr\">https://github.com/advisories/GHSA-jh3w-4vvf-mjgr</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jh3w-4vvf-mjgr",
            "title": "[Django] Django has regular expression denial of service vulnerability in EmailValidator/URLValidator",
            "date_modified": "2024-09-20T16:00:17.000Z",
            "date_published": "2023-07-03T15:30:45.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jh3w-4vvf-mjgr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, <code>EmailValidator</code> and <code>URLValidator</code> are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-36053\">https://nvd.nist.gov/vuln/detail/CVE-2023-36053</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/454f2fb93437f98917283336201b4048293f7582\">https://github.com/django/django/commit/454f2fb93437f98917283336201b4048293f7582</a></li>\n<li><a href=\"https://github.com/django/django/commit/ad0410ec4f458aa39803e5f6b9a3736527062dcd\">https://github.com/django/django/commit/ad0410ec4f458aa39803e5f6b9a3736527062dcd</a></li>\n<li><a href=\"https://github.com/django/django/commit/b7c5feb35a31799de6e582ad6a5a91a9de74e0f9\">https://github.com/django/django/commit/b7c5feb35a31799de6e582ad6a5a91a9de74e0f9</a></li>\n<li><a href=\"https://github.com/django/django/commit/beb3f3d55940d9aa7198bf9d424ab74e873aec3d\">https://github.com/django/django/commit/beb3f3d55940d9aa7198bf9d424ab74e873aec3d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-100.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-100.yaml</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2023/07/msg00022.html\">https://lists.debian.org/debian-lts-announce/2023/07/msg00022.html</a></li>\n<li><a href=\"https://www.debian.org/security/2023/dsa-5465\">https://www.debian.org/security/2023/dsa-5465</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/jul/03/security-releases\">https://www.djangoproject.com/weblog/2023/jul/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jh3w-4vvf-mjgr\">https://github.com/advisories/GHSA-jh3w-4vvf-mjgr</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jh3w-4vvf-mjgr",
            "title": "[Django] Django has regular expression denial of service vulnerability in EmailValidator/URLValidator",
            "date_modified": "2024-09-20T16:00:17.000Z",
            "date_published": "2023-07-03T15:30:45.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jh3w-4vvf-mjgr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, <code>EmailValidator</code> and <code>URLValidator</code> are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-36053\">https://nvd.nist.gov/vuln/detail/CVE-2023-36053</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/454f2fb93437f98917283336201b4048293f7582\">https://github.com/django/django/commit/454f2fb93437f98917283336201b4048293f7582</a></li>\n<li><a href=\"https://github.com/django/django/commit/ad0410ec4f458aa39803e5f6b9a3736527062dcd\">https://github.com/django/django/commit/ad0410ec4f458aa39803e5f6b9a3736527062dcd</a></li>\n<li><a href=\"https://github.com/django/django/commit/b7c5feb35a31799de6e582ad6a5a91a9de74e0f9\">https://github.com/django/django/commit/b7c5feb35a31799de6e582ad6a5a91a9de74e0f9</a></li>\n<li><a href=\"https://github.com/django/django/commit/beb3f3d55940d9aa7198bf9d424ab74e873aec3d\">https://github.com/django/django/commit/beb3f3d55940d9aa7198bf9d424ab74e873aec3d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-100.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-100.yaml</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2023/07/msg00022.html\">https://lists.debian.org/debian-lts-announce/2023/07/msg00022.html</a></li>\n<li><a href=\"https://www.debian.org/security/2023/dsa-5465\">https://www.debian.org/security/2023/dsa-5465</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRDGTUN4LTI6HG4TWR3JYLSFVXPZT42A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XG5DYKPNDCEHJQ3TKPJQO7QGSR4FAYMS</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/jul/03/security-releases\">https://www.djangoproject.com/weblog/2023/jul/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jh3w-4vvf-mjgr\">https://github.com/advisories/GHSA-jh3w-4vvf-mjgr</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jh3w-4vvf-mjgr",
            "title": "[Django] Django has regular expression denial of service vulnerability in EmailValidator/URLValidator",
            "date_modified": "2024-09-20T16:00:17.000Z",
            "date_published": "2023-07-03T15:30:45.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jh3w-4vvf-mjgr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in <code>django.views.defaults.page_not_found()</code>, leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-3498\">https://nvd.nist.gov/vuln/detail/CVE-2019-3498</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-337x-4q8g-prc5\">https://github.com/advisories/GHSA-337x-4q8g-prc5</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ\">https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html\">https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4363\">https://www.debian.org/security/2019/dsa-4363</a></li>\n<li><a href=\"https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453\">https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-17.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-17.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ</a></li>\n<li><a href=\"https://usn.ubuntu.com/3851-1\">https://usn.ubuntu.com/3851-1</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jan/04/security-releases\">https://www.djangoproject.com/weblog/2019/jan/04/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5",
            "title": "[Django] Improper Input Validation in Django",
            "date_modified": "2024-09-20T15:49:43.000Z",
            "date_published": "2019-01-14T16:20:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in <code>django.views.defaults.page_not_found()</code>, leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-3498\">https://nvd.nist.gov/vuln/detail/CVE-2019-3498</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-337x-4q8g-prc5\">https://github.com/advisories/GHSA-337x-4q8g-prc5</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ\">https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html\">https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4363\">https://www.debian.org/security/2019/dsa-4363</a></li>\n<li><a href=\"https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453\">https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-17.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-17.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ</a></li>\n<li><a href=\"https://usn.ubuntu.com/3851-1\">https://usn.ubuntu.com/3851-1</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jan/04/security-releases\">https://www.djangoproject.com/weblog/2019/jan/04/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5",
            "title": "[Django] Improper Input Validation in Django",
            "date_modified": "2024-09-20T15:49:43.000Z",
            "date_published": "2019-01-14T16:20:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in <code>django.views.defaults.page_not_found()</code>, leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-3498\">https://nvd.nist.gov/vuln/detail/CVE-2019-3498</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-337x-4q8g-prc5\">https://github.com/advisories/GHSA-337x-4q8g-prc5</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ\">https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html\">https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4363\">https://www.debian.org/security/2019/dsa-4363</a></li>\n<li><a href=\"https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453\">https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-17.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-17.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ</a></li>\n<li><a href=\"https://usn.ubuntu.com/3851-1\">https://usn.ubuntu.com/3851-1</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jan/04/security-releases\">https://www.djangoproject.com/weblog/2019/jan/04/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5",
            "title": "[Django] Improper Input Validation in Django",
            "date_modified": "2024-09-20T15:49:43.000Z",
            "date_published": "2019-01-14T16:20:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.20, 3.0 before 3.0.14, and 3.1 before 3.1.8, MultiPartParser allowed directory traversal via uploaded files with suitably crafted file names. Built-in upload handlers were not affected by this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-28658\">https://nvd.nist.gov/vuln/detail/CVE-2021-28658</a></li>\n<li><a href=\"https://groups.google.com/g/django-announce/c/ePr5j-ngdPU\">https://groups.google.com/g/django-announce/c/ePr5j-ngdPU</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/04/msg00008.html\">https://lists.debian.org/debian-lts-announce/2021/04/msg00008.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.1/releases/security\">https://docs.djangoproject.com/en/3.1/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xgxc-v2qg-chmh\">https://github.com/advisories/GHSA-xgxc-v2qg-chmh</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-6.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-6.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE</a></li>\n<li><a href=\"https://pypi.org/project/Django\">https://pypi.org/project/Django</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20210528-0001\">https://security.netapp.com/advisory/ntap-20210528-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/apr/06/security-releases\">https://www.djangoproject.com/weblog/2021/apr/06/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xgxc-v2qg-chmh",
            "title": "[Django] Directory Traversal in Django",
            "date_modified": "2024-09-20T15:47:27.000Z",
            "date_published": "2021-04-08T18:11:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xgxc-v2qg-chmh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.20, 3.0 before 3.0.14, and 3.1 before 3.1.8, MultiPartParser allowed directory traversal via uploaded files with suitably crafted file names. Built-in upload handlers were not affected by this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-28658\">https://nvd.nist.gov/vuln/detail/CVE-2021-28658</a></li>\n<li><a href=\"https://groups.google.com/g/django-announce/c/ePr5j-ngdPU\">https://groups.google.com/g/django-announce/c/ePr5j-ngdPU</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/04/msg00008.html\">https://lists.debian.org/debian-lts-announce/2021/04/msg00008.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.1/releases/security\">https://docs.djangoproject.com/en/3.1/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xgxc-v2qg-chmh\">https://github.com/advisories/GHSA-xgxc-v2qg-chmh</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-6.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-6.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE</a></li>\n<li><a href=\"https://pypi.org/project/Django\">https://pypi.org/project/Django</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20210528-0001\">https://security.netapp.com/advisory/ntap-20210528-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/apr/06/security-releases\">https://www.djangoproject.com/weblog/2021/apr/06/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xgxc-v2qg-chmh",
            "title": "[Django] Directory Traversal in Django",
            "date_modified": "2024-09-20T15:47:27.000Z",
            "date_published": "2021-04-08T18:11:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xgxc-v2qg-chmh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.20, 3.0 before 3.0.14, and 3.1 before 3.1.8, MultiPartParser allowed directory traversal via uploaded files with suitably crafted file names. Built-in upload handlers were not affected by this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-28658\">https://nvd.nist.gov/vuln/detail/CVE-2021-28658</a></li>\n<li><a href=\"https://groups.google.com/g/django-announce/c/ePr5j-ngdPU\">https://groups.google.com/g/django-announce/c/ePr5j-ngdPU</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/04/msg00008.html\">https://lists.debian.org/debian-lts-announce/2021/04/msg00008.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.1/releases/security\">https://docs.djangoproject.com/en/3.1/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xgxc-v2qg-chmh\">https://github.com/advisories/GHSA-xgxc-v2qg-chmh</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-6.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-6.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE</a></li>\n<li><a href=\"https://pypi.org/project/Django\">https://pypi.org/project/Django</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20210528-0001\">https://security.netapp.com/advisory/ntap-20210528-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/apr/06/security-releases\">https://www.djangoproject.com/weblog/2021/apr/06/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xgxc-v2qg-chmh",
            "title": "[Django] Directory Traversal in Django",
            "date_modified": "2024-09-20T15:47:27.000Z",
            "date_published": "2021-04-08T18:11:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xgxc-v2qg-chmh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.24, 3.x before 3.1.12, and 3.2 before 3.2.4, URLValidator, validate_ipv4_address, and validate_ipv46_address do not prohibit leading zero characters in octal literals. This may allow a bypass of access control that is based on IP addresses. (validate_ipv4_address and validate_ipv46_address are unaffected with Python 3.9.5+..) .</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-33571\">https://nvd.nist.gov/vuln/detail/CVE-2021-33571</a></li>\n<li><a href=\"https://groups.google.com/g/django-announce/c/sPyjSKMi8Eo\">https://groups.google.com/g/django-announce/c/sPyjSKMi8Eo</a></li>\n<li><a href=\"https://github.com/django/django/commit/203d4ab9ebcd72fc4d6eb7398e66ed9e474e118e\">https://github.com/django/django/commit/203d4ab9ebcd72fc4d6eb7398e66ed9e474e118e</a></li>\n<li><a href=\"https://github.com/django/django/commit/9f75e2e562fa0c0482f3dde6fc7399a9070b4a3d\">https://github.com/django/django/commit/9f75e2e562fa0c0482f3dde6fc7399a9070b4a3d</a></li>\n<li><a href=\"https://github.com/django/django/commit/f27c38ab5d90f68c9dd60cabef248a570c0be8fc\">https://github.com/django/django/commit/f27c38ab5d90f68c9dd60cabef248a570c0be8fc</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.2/releases/security\">https://docs.djangoproject.com/en/3.2/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p99v-5w3c-jqq9\">https://github.com/advisories/GHSA-p99v-5w3c-jqq9</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-99.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-99.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20210727-0004\">https://security.netapp.com/advisory/ntap-20210727-0004</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/jun/02/security-releases\">https://www.djangoproject.com/weblog/2021/jun/02/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p99v-5w3c-jqq9",
            "title": "[Django] Django Access Control Bypass possibly leading to SSRF, RFI, and LFI attacks ",
            "date_modified": "2024-09-20T15:46:26.000Z",
            "date_published": "2021-06-10T17:21:12.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p99v-5w3c-jqq9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.24, 3.x before 3.1.12, and 3.2 before 3.2.4, URLValidator, validate_ipv4_address, and validate_ipv46_address do not prohibit leading zero characters in octal literals. This may allow a bypass of access control that is based on IP addresses. (validate_ipv4_address and validate_ipv46_address are unaffected with Python 3.9.5+..) .</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-33571\">https://nvd.nist.gov/vuln/detail/CVE-2021-33571</a></li>\n<li><a href=\"https://groups.google.com/g/django-announce/c/sPyjSKMi8Eo\">https://groups.google.com/g/django-announce/c/sPyjSKMi8Eo</a></li>\n<li><a href=\"https://github.com/django/django/commit/203d4ab9ebcd72fc4d6eb7398e66ed9e474e118e\">https://github.com/django/django/commit/203d4ab9ebcd72fc4d6eb7398e66ed9e474e118e</a></li>\n<li><a href=\"https://github.com/django/django/commit/9f75e2e562fa0c0482f3dde6fc7399a9070b4a3d\">https://github.com/django/django/commit/9f75e2e562fa0c0482f3dde6fc7399a9070b4a3d</a></li>\n<li><a href=\"https://github.com/django/django/commit/f27c38ab5d90f68c9dd60cabef248a570c0be8fc\">https://github.com/django/django/commit/f27c38ab5d90f68c9dd60cabef248a570c0be8fc</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.2/releases/security\">https://docs.djangoproject.com/en/3.2/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p99v-5w3c-jqq9\">https://github.com/advisories/GHSA-p99v-5w3c-jqq9</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-99.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-99.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20210727-0004\">https://security.netapp.com/advisory/ntap-20210727-0004</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/jun/02/security-releases\">https://www.djangoproject.com/weblog/2021/jun/02/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p99v-5w3c-jqq9",
            "title": "[Django] Django Access Control Bypass possibly leading to SSRF, RFI, and LFI attacks ",
            "date_modified": "2024-09-20T15:46:26.000Z",
            "date_published": "2021-06-10T17:21:12.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p99v-5w3c-jqq9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.24, 3.x before 3.1.12, and 3.2 before 3.2.4, URLValidator, validate_ipv4_address, and validate_ipv46_address do not prohibit leading zero characters in octal literals. This may allow a bypass of access control that is based on IP addresses. (validate_ipv4_address and validate_ipv46_address are unaffected with Python 3.9.5+..) .</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-33571\">https://nvd.nist.gov/vuln/detail/CVE-2021-33571</a></li>\n<li><a href=\"https://groups.google.com/g/django-announce/c/sPyjSKMi8Eo\">https://groups.google.com/g/django-announce/c/sPyjSKMi8Eo</a></li>\n<li><a href=\"https://github.com/django/django/commit/203d4ab9ebcd72fc4d6eb7398e66ed9e474e118e\">https://github.com/django/django/commit/203d4ab9ebcd72fc4d6eb7398e66ed9e474e118e</a></li>\n<li><a href=\"https://github.com/django/django/commit/9f75e2e562fa0c0482f3dde6fc7399a9070b4a3d\">https://github.com/django/django/commit/9f75e2e562fa0c0482f3dde6fc7399a9070b4a3d</a></li>\n<li><a href=\"https://github.com/django/django/commit/f27c38ab5d90f68c9dd60cabef248a570c0be8fc\">https://github.com/django/django/commit/f27c38ab5d90f68c9dd60cabef248a570c0be8fc</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.2/releases/security\">https://docs.djangoproject.com/en/3.2/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p99v-5w3c-jqq9\">https://github.com/advisories/GHSA-p99v-5w3c-jqq9</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-99.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-99.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20210727-0004\">https://security.netapp.com/advisory/ntap-20210727-0004</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/jun/02/security-releases\">https://www.djangoproject.com/weblog/2021/jun/02/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p99v-5w3c-jqq9",
            "title": "[Django] Django Access Control Bypass possibly leading to SSRF, RFI, and LFI attacks ",
            "date_modified": "2024-09-20T15:46:26.000Z",
            "date_published": "2021-06-10T17:21:12.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p99v-5w3c-jqq9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><em>What kind of vulnerability is it? Who is impacted?</em>\nPotential XSS from API calls below:\nGET /v1/credentials\nGET /v1/credentials/\nGET /v1/archive/credentials/\nGET /v1/archive/credentials\nPOST /v1/credentials\nPUT /v1/credentials/\nPUT /v1/credentials//</p>\n<p>GET /v1/services\nGET /v1/services/\nGET /v1/archive/services/\nGET /v1/archive/services\nPUT /v1/services/\nPUT /v1/services//</p>\n<p>Stored XSS that can only be used as a stored HTML injection. The attacker needs to be authenticated and have privileges to create new credentials, but could use this to show information and run scripts to other users into the same Confidant instance.</p>\n<h3 id=\"patches\">Patches</h3>\n<p><em>Has the problem been patched? What versions should users upgrade to?</em>\nyes, version 6.6.2</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p><em>Is there a way for users to fix or remediate the vulnerability without upgrading?</em>\nNO</p>\n<h3 id=\"references\">References</h3>\n<p><em>Are there any links users can visit to find out more?</em>\n<a href=\"https://hackerone.com/reports/2332004\">https://hackerone.com/reports/2332004</a>\n<a href=\"https://hackerone.com/reports/2456673\">https://hackerone.com/reports/2456673</a>\n<a href=\"https://hackerone.com/reports/2476542\">https://hackerone.com/reports/2476542</a>\nAcknowledgement: \nThank you Rein Daelman (<a href=\"https://hackerone.com/trein\">trein</a>) for reporting and proposing the fix.</p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/lyft/confidant/security/advisories/GHSA-rxq8-q85f-m866\">https://github.com/lyft/confidant/security/advisories/GHSA-rxq8-q85f-m866</a></li>\n<li><a href=\"https://github.com/lyft/confidant/commit/8876b07abde0c8d2a4974f79b60562b6d0193db9\">https://github.com/lyft/confidant/commit/8876b07abde0c8d2a4974f79b60562b6d0193db9</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rxq8-q85f-m866\">https://github.com/advisories/GHSA-rxq8-q85f-m866</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rxq8-q85f-m866",
            "title": "[confidant] Prevent XSS from Confidant API call",
            "date_modified": "2024-09-20T15:45:26.000Z",
            "date_published": "2024-09-20T15:45:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rxq8-q85f-m866"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths. This issue has low severity, according to the Django security policy.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-44420\">https://nvd.nist.gov/vuln/detail/CVE-2021-44420</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2021/12/07/1\">https://www.openwall.com/lists/oss-security/2021/12/07/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6\">https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.2/releases/security\">https://docs.djangoproject.com/en/3.2/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v6rh-hp5x-86rv\">https://github.com/advisories/GHSA-v6rh-hp5x-86rv</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-439.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-439.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20211229-0006\">https://security.netapp.com/advisory/ntap-20211229-0006</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/dec/07/security-releases\">https://www.djangoproject.com/weblog/2021/dec/07/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v6rh-hp5x-86rv",
            "title": "[Django] Potential bypass of an upstream access control based on URL paths in Django",
            "date_modified": "2024-09-20T15:44:57.000Z",
            "date_published": "2021-12-09T19:09:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v6rh-hp5x-86rv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths. This issue has low severity, according to the Django security policy.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-44420\">https://nvd.nist.gov/vuln/detail/CVE-2021-44420</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2021/12/07/1\">https://www.openwall.com/lists/oss-security/2021/12/07/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6\">https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.2/releases/security\">https://docs.djangoproject.com/en/3.2/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v6rh-hp5x-86rv\">https://github.com/advisories/GHSA-v6rh-hp5x-86rv</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-439.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-439.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20211229-0006\">https://security.netapp.com/advisory/ntap-20211229-0006</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/dec/07/security-releases\">https://www.djangoproject.com/weblog/2021/dec/07/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v6rh-hp5x-86rv",
            "title": "[Django] Potential bypass of an upstream access control based on URL paths in Django",
            "date_modified": "2024-09-20T15:44:57.000Z",
            "date_published": "2021-12-09T19:09:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v6rh-hp5x-86rv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths. This issue has low severity, according to the Django security policy.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-44420\">https://nvd.nist.gov/vuln/detail/CVE-2021-44420</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2021/12/07/1\">https://www.openwall.com/lists/oss-security/2021/12/07/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6\">https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.2/releases/security\">https://docs.djangoproject.com/en/3.2/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v6rh-hp5x-86rv\">https://github.com/advisories/GHSA-v6rh-hp5x-86rv</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-439.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2021-439.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20211229-0006\">https://security.netapp.com/advisory/ntap-20211229-0006</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2021/dec/07/security-releases\">https://www.djangoproject.com/weblog/2021/dec/07/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v6rh-hp5x-86rv",
            "title": "[Django] Potential bypass of an upstream access control based on URL paths in Django",
            "date_modified": "2024-09-20T15:44:57.000Z",
            "date_published": "2021-12-09T19:09:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v6rh-hp5x-86rv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-31047\">https://nvd.nist.gov/vuln/detail/CVE-2023-31047</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd\">https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd</a></li>\n<li><a href=\"https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64\">https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64</a></li>\n<li><a href=\"https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965\">https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230609-0008\">https://security.netapp.com/advisory/ntap-20230609-0008</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/may/03/security-releases\">https://www.djangoproject.com/weblog/2023/may/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r3xc-prgr-mg9p\">https://github.com/advisories/GHSA-r3xc-prgr-mg9p</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p",
            "title": "[Django] Django bypasses validation when using one form field to upload multiple files",
            "date_modified": "2024-09-20T15:44:06.000Z",
            "date_published": "2023-05-07T03:30:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-31047\">https://nvd.nist.gov/vuln/detail/CVE-2023-31047</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd\">https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd</a></li>\n<li><a href=\"https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64\">https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64</a></li>\n<li><a href=\"https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965\">https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230609-0008\">https://security.netapp.com/advisory/ntap-20230609-0008</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/may/03/security-releases\">https://www.djangoproject.com/weblog/2023/may/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r3xc-prgr-mg9p\">https://github.com/advisories/GHSA-r3xc-prgr-mg9p</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p",
            "title": "[Django] Django bypasses validation when using one form field to upload multiple files",
            "date_modified": "2024-09-20T15:44:06.000Z",
            "date_published": "2023-05-07T03:30:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-31047\">https://nvd.nist.gov/vuln/detail/CVE-2023-31047</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd\">https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd</a></li>\n<li><a href=\"https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64\">https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64</a></li>\n<li><a href=\"https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965\">https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20230609-0008\">https://security.netapp.com/advisory/ntap-20230609-0008</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/may/03/security-releases\">https://www.djangoproject.com/weblog/2023/may/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r3xc-prgr-mg9p\">https://github.com/advisories/GHSA-r3xc-prgr-mg9p</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p",
            "title": "[Django] Django bypasses validation when using one form field to upload multiple files",
            "date_modified": "2024-09-20T15:44:06.000Z",
            "date_published": "2023-05-07T03:30:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r3xc-prgr-mg9p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django version 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-13596\">https://nvd.nist.gov/vuln/detail/CVE-2020-13596</a></li>\n<li><a href=\"https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ\">https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ</a></li>\n<li><a href=\"https://www.debian.org/security/2020/dsa-4705\">https://www.debian.org/security/2020/dsa-4705</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpujan2021.html\">https://www.oracle.com/security-alerts/cpujan2021.html</a></li>\n<li><a href=\"https://github.com/django/django/commit/1f2dd37f6fcefdd10ed44cb233b2e62b520afb38\">https://github.com/django/django/commit/1f2dd37f6fcefdd10ed44cb233b2e62b520afb38</a></li>\n<li><a href=\"https://github.com/django/django/commit/6d61860b22875f358fac83d903dc629897934815\">https://github.com/django/django/commit/6d61860b22875f358fac83d903dc629897934815</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.0/releases/security\">https://docs.djangoproject.com/en/3.0/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20200611-0002\">https://security.netapp.com/advisory/ntap-20200611-0002</a></li>\n<li><a href=\"https://usn.ubuntu.com/4381-1\">https://usn.ubuntu.com/4381-1</a></li>\n<li><a href=\"https://usn.ubuntu.com/4381-2\">https://usn.ubuntu.com/4381-2</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2020/jun/03/security-releases\">https://www.djangoproject.com/weblog/2020/jun/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2m34-jcjv-45xf\">https://github.com/advisories/GHSA-2m34-jcjv-45xf</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2020-32.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2020-32.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2m34-jcjv-45xf",
            "title": "[Django] XSS in Django",
            "date_modified": "2024-09-20T15:43:13.000Z",
            "date_published": "2020-06-05T16:24:28.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2m34-jcjv-45xf"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}