{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>A path traversal vulnerability inside of <code>LocalMode</code>'s <code>open_local_file</code> method allows an authenticated user with adequate permissions to download any <code>.txt</code> via the <code>ScreensController#show</code> on the web server COSMOS is running on (depending on the file permissions).</p>\n<p>Note: This CVE affects all OpenC3 COSMOS Editions</p>\n<h3 id=\"impact\">Impact</h3>\n<p>This issue may lead to Information Disclosure.</p>\n<p><strong>NOTE:</strong> The complete advisory with much more information is added as <a href=\"https://github.com/OpenC3/cosmos/security/advisories/GHSA-8jxr-mccc-mwg8#advisory-comment-104903\">comment</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/OpenC3/cosmos/security/advisories/GHSA-8jxr-mccc-mwg8\">https://github.com/OpenC3/cosmos/security/advisories/GHSA-8jxr-mccc-mwg8</a></li>\n<li><a href=\"https://github.com/OpenC3/cosmos/commit/a34e61aea5a465f0ab3e57d833ae7ff4cafd710b\">https://github.com/OpenC3/cosmos/commit/a34e61aea5a465f0ab3e57d833ae7ff4cafd710b</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-46977\">https://nvd.nist.gov/vuln/detail/CVE-2024-46977</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/openc3/PYSEC-2024-101.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/openc3/PYSEC-2024-101.yaml</a></li>\n<li><a href=\"https://rubysec.com/advisories/CVE-2024-46977\">https://rubysec.com/advisories/CVE-2024-46977</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8jxr-mccc-mwg8\">https://github.com/advisories/GHSA-8jxr-mccc-mwg8</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8jxr-mccc-mwg8",
            "title": "[openc3] OpenC3 Path Traversal via screen controller (`GHSL-2024-127`)",
            "date_modified": "2024-10-09T18:32:30.000Z",
            "date_published": "2024-10-02T19:29:32.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8jxr-mccc-mwg8"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>The login functionality contains a reflected cross-site scripting (XSS) vulnerability.</p>\n<p>Note: This CVE only affects Open Source Edition, and not OpenC3 COSMOS Enterprise Edition</p>\n<h3 id=\"impact\">Impact</h3>\n<p>This issue may lead up to Remote Code Execution (RCE).</p>\n<p><strong>NOTE:</strong> The complete advisory with much more information is added as <a href=\"https://github.com/OpenC3/cosmos/security/advisories/GHSA-vfj8-5pj7-2f9g#advisory-comment-104904\">comment</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/OpenC3/cosmos/security/advisories/GHSA-vfj8-5pj7-2f9g\">https://github.com/OpenC3/cosmos/security/advisories/GHSA-vfj8-5pj7-2f9g</a></li>\n<li><a href=\"https://github.com/OpenC3/cosmos/commit/762d7e0e93bdc2f340b1e42acccedc78994a576e\">https://github.com/OpenC3/cosmos/commit/762d7e0e93bdc2f340b1e42acccedc78994a576e</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-43795\">https://nvd.nist.gov/vuln/detail/CVE-2024-43795</a></li>\n<li><a href=\"https://github.com/rubysec/ruby-advisory-db/blob/master/gems/openc3/CVE-2024-43795.yml\">https://github.com/rubysec/ruby-advisory-db/blob/master/gems/openc3/CVE-2024-43795.yml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/openc3/PYSEC-2024-100.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/openc3/PYSEC-2024-100.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vfj8-5pj7-2f9g\">https://github.com/advisories/GHSA-vfj8-5pj7-2f9g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vfj8-5pj7-2f9g",
            "title": "[openc3] OpenC3 Cross-site Scripting in Login functionality (`GHSL-2024-128`)",
            "date_modified": "2024-10-09T18:27:43.000Z",
            "date_published": "2024-10-02T19:29:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vfj8-5pj7-2f9g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue in the getcolor function in utils.py of xhtml2pdf v0.2.13 allows attackers to cause a Regular expression Denial of Service (ReDOS) via supplying a crafted string.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-25885\">https://nvd.nist.gov/vuln/detail/CVE-2024-25885</a></li>\n<li><a href=\"https://gist.github.com/salvatore-abello/c88dd0027496774023ef36c7b576d206\">https://gist.github.com/salvatore-abello/c88dd0027496774023ef36c7b576d206</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jj5c-hhrg-vv5h\">https://github.com/advisories/GHSA-jj5c-hhrg-vv5h</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jj5c-hhrg-vv5h",
            "title": "[xhtml2pdf] xhtml2pdf Denial of Service via crafted string",
            "date_modified": "2024-10-09T17:01:39.000Z",
            "date_published": "2024-10-08T18:33:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jj5c-hhrg-vv5h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django v5.1.1, v5.0.9, and v4.2.16. The django.contrib.auth.forms.PasswordResetForm class, when used in a view implementing password reset flows, allows remote attackers to enumerate user e-mail addresses by sending password reset requests and observing the outcome (only when e-mail sending is consistently failing).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-45231\">https://nvd.nist.gov/vuln/detail/CVE-2024-45231</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2024/sep/03/security-releases\">https://www.djangoproject.com/weblog/2024/sep/03/security-releases</a></li>\n<li><a href=\"https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca\">https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca</a></li>\n<li><a href=\"https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2\">https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2</a></li>\n<li><a href=\"https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199\">https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rrqc-c2jx-6jgv\">https://github.com/advisories/GHSA-rrqc-c2jx-6jgv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rrqc-c2jx-6jgv",
            "title": "[Django] Django allows enumeration of user e-mail addresses",
            "date_modified": "2024-10-08T21:17:01.000Z",
            "date_published": "2024-10-08T18:33:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rrqc-c2jx-6jgv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django v5.1.1, v5.0.9, and v4.2.16. The django.contrib.auth.forms.PasswordResetForm class, when used in a view implementing password reset flows, allows remote attackers to enumerate user e-mail addresses by sending password reset requests and observing the outcome (only when e-mail sending is consistently failing).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-45231\">https://nvd.nist.gov/vuln/detail/CVE-2024-45231</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2024/sep/03/security-releases\">https://www.djangoproject.com/weblog/2024/sep/03/security-releases</a></li>\n<li><a href=\"https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca\">https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca</a></li>\n<li><a href=\"https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2\">https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2</a></li>\n<li><a href=\"https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199\">https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rrqc-c2jx-6jgv\">https://github.com/advisories/GHSA-rrqc-c2jx-6jgv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rrqc-c2jx-6jgv",
            "title": "[Django] Django allows enumeration of user e-mail addresses",
            "date_modified": "2024-10-08T21:17:01.000Z",
            "date_published": "2024-10-08T18:33:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rrqc-c2jx-6jgv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django v5.1.1, v5.0.9, and v4.2.16. The django.contrib.auth.forms.PasswordResetForm class, when used in a view implementing password reset flows, allows remote attackers to enumerate user e-mail addresses by sending password reset requests and observing the outcome (only when e-mail sending is consistently failing).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-45231\">https://nvd.nist.gov/vuln/detail/CVE-2024-45231</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2024/sep/03/security-releases\">https://www.djangoproject.com/weblog/2024/sep/03/security-releases</a></li>\n<li><a href=\"https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca\">https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca</a></li>\n<li><a href=\"https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2\">https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2</a></li>\n<li><a href=\"https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199\">https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rrqc-c2jx-6jgv\">https://github.com/advisories/GHSA-rrqc-c2jx-6jgv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rrqc-c2jx-6jgv",
            "title": "[Django] Django allows enumeration of user e-mail addresses",
            "date_modified": "2024-10-08T21:17:01.000Z",
            "date_published": "2024-10-08T18:33:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rrqc-c2jx-6jgv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and 4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-45230\">https://nvd.nist.gov/vuln/detail/CVE-2024-45230</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2024/sep/03/security-releases\">https://www.djangoproject.com/weblog/2024/sep/03/security-releases</a></li>\n<li><a href=\"https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397\">https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397</a></li>\n<li><a href=\"https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b\">https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b</a></li>\n<li><a href=\"https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2\">https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5hgc-2vfp-mqvc\">https://github.com/advisories/GHSA-5hgc-2vfp-mqvc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5hgc-2vfp-mqvc",
            "title": "[Django] Django vulnerable to denial-of-service attack via the urlize() and urlizetrunc() template filters",
            "date_modified": "2024-10-08T21:04:46.000Z",
            "date_published": "2024-10-08T18:33:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5hgc-2vfp-mqvc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and 4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-45230\">https://nvd.nist.gov/vuln/detail/CVE-2024-45230</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2024/sep/03/security-releases\">https://www.djangoproject.com/weblog/2024/sep/03/security-releases</a></li>\n<li><a href=\"https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397\">https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397</a></li>\n<li><a href=\"https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b\">https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b</a></li>\n<li><a href=\"https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2\">https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5hgc-2vfp-mqvc\">https://github.com/advisories/GHSA-5hgc-2vfp-mqvc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5hgc-2vfp-mqvc",
            "title": "[Django] Django vulnerable to denial-of-service attack via the urlize() and urlizetrunc() template filters",
            "date_modified": "2024-10-08T21:04:46.000Z",
            "date_published": "2024-10-08T18:33:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5hgc-2vfp-mqvc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and 4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-45230\">https://nvd.nist.gov/vuln/detail/CVE-2024-45230</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2024/sep/03/security-releases\">https://www.djangoproject.com/weblog/2024/sep/03/security-releases</a></li>\n<li><a href=\"https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397\">https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397</a></li>\n<li><a href=\"https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b\">https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b</a></li>\n<li><a href=\"https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2\">https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5hgc-2vfp-mqvc\">https://github.com/advisories/GHSA-5hgc-2vfp-mqvc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5hgc-2vfp-mqvc",
            "title": "[Django] Django vulnerable to denial-of-service attack via the urlize() and urlizetrunc() template filters",
            "date_modified": "2024-10-08T21:04:46.000Z",
            "date_published": "2024-10-08T18:33:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5hgc-2vfp-mqvc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Pillow before 8.1.1. In TiffDecode.c, there is a negative-offset memcpy with an invalid size.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-25290\">https://nvd.nist.gov/vuln/detail/CVE-2021-25290</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/86f02f7c70862a0954bfe8133736d352db978eaa\">https://github.com/python-pillow/Pillow/commit/86f02f7c70862a0954bfe8133736d352db978eaa</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html\">https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202107-33\">https://security.gentoo.org/glsa/202107-33</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html\">https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/e25be1e33dc526bfd1094bc778a54d8e29bf66c9\">https://github.com/python-pillow/Pillow/commit/e25be1e33dc526bfd1094bc778a54d8e29bf66c9</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8xjq-8fcg-g5hw\">https://github.com/advisories/GHSA-8xjq-8fcg-g5hw</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-36.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-36.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8xjq-8fcg-g5hw",
            "title": "[pillow] Out-of-bounds Write in Pillow",
            "date_modified": "2024-10-08T13:11:58.000Z",
            "date_published": "2021-03-29T16:35:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8xjq-8fcg-g5hw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Pillow before 8.1.1. TiffDecode has a heap-based buffer overflow when decoding crafted YCbCr files because of certain interpretation conflicts with LibTIFF in RGBA mode. NOTE: this issue exists because of an incomplete fix for CVE-2020-35654.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-25289\">https://nvd.nist.gov/vuln/detail/CVE-2021-25289</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/3fee28eb9479bf7d59e0fa08068f9cc4a6e2f04c\">https://github.com/python-pillow/Pillow/commit/3fee28eb9479bf7d59e0fa08068f9cc4a6e2f04c</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html\">https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202107-33\">https://security.gentoo.org/glsa/202107-33</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/cbfdde7b1f2295059a20a539ee9960f0bec7b299\">https://github.com/python-pillow/Pillow/commit/cbfdde7b1f2295059a20a539ee9960f0bec7b299</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-57h3-9rgr-c24m\">https://github.com/advisories/GHSA-57h3-9rgr-c24m</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-35.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-35.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-57h3-9rgr-c24m",
            "title": "[pillow] Out of bounds write in Pillow",
            "date_modified": "2024-10-08T13:11:34.000Z",
            "date_published": "2021-03-29T16:35:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-57h3-9rgr-c24m"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Buffer overflow in the <code>ImagingPcdDecode</code> function in <code>PcdDecode.c</code> in Pillow before 3.1.1 and Python Imaging Library (PIL) 1.1.7 and earlier allows remote attackers to cause a denial of service (crash) via a crafted PhotoCD file.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-2533\">https://nvd.nist.gov/vuln/detail/CVE-2016-2533</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/pull/1706\">https://github.com/python-pillow/Pillow/pull/1706</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/5bdf54b5a76b54fb00bd05f2d733e0a4173eefc9#diff-8ff6909c159597e22288ad818938fd6b\">https://github.com/python-pillow/Pillow/commit/5bdf54b5a76b54fb00bd05f2d733e0a4173eefc9#diff-8ff6909c159597e22288ad818938fd6b</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/ae453aa18b66af54e7ff716f4ccb33adca60afd4#diff-8ff6909c159597e22288ad818938fd6b\">https://github.com/python-pillow/Pillow/commit/ae453aa18b66af54e7ff716f4ccb33adca60afd4#diff-8ff6909c159597e22288ad818938fd6b</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3c5c-7235-994j\">https://github.com/advisories/GHSA-3c5c-7235-994j</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201612-52\">https://security.gentoo.org/glsa/201612-52</a></li>\n<li><a href=\"http://www.debian.org/security/2016/dsa-3499\">http://www.debian.org/security/2016/dsa-3499</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2016/02/02/5\">http://www.openwall.com/lists/oss-security/2016/02/02/5</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2016/02/22/2\">http://www.openwall.com/lists/oss-security/2016/02/22/2</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinjan2016-2867206.html\">http://www.oracle.com/technetwork/topics/security/bulletinjan2016-2867206.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst?plain=1#L53\">https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst?plain=1#L53</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-19.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-19.yaml</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst\">https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3c5c-7235-994j",
            "title": "[pillow] Pillow buffer overflow in ImagingPcdDecode",
            "date_modified": "2024-10-08T13:09:01.000Z",
            "date_published": "2018-07-24T20:15:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3c5c-7235-994j"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Integer overflow in the <code>ImagingResampleHorizontal</code> function in <code>libImaging/Resample.c</code> in Pillow before 3.1.1 allows remote attackers to have unspecified impact via negative values of the new size, which triggers a heap-based buffer overflow.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-4009\">https://nvd.nist.gov/vuln/detail/CVE-2016-4009</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/pull/1714\">https://github.com/python-pillow/Pillow/pull/1714</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/4e0d9b0b9740d258ade40cce248c93777362ac1e\">https://github.com/python-pillow/Pillow/commit/4e0d9b0b9740d258ade40cce248c93777362ac1e</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hvr8-466p-75rh\">https://github.com/advisories/GHSA-hvr8-466p-75rh</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst\">https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201612-52\">https://security.gentoo.org/glsa/201612-52</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/86064\">http://www.securityfocus.com/bid/86064</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-7.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-7.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hvr8-466p-75rh",
            "title": "[pillow] Pillow Integer overflow in ImagingResampleHorizontal",
            "date_modified": "2024-10-08T13:06:58.000Z",
            "date_published": "2018-07-24T20:15:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hvr8-466p-75rh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Pillow before 3.3.2 allows context-dependent attackers to obtain sensitive information by using the \"crafted image file\" approach, related to an \"Integer Overflow\" issue affecting the <code>Image.core.map_buffer</code> in <code>map.c</code> component.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-9189\">https://nvd.nist.gov/vuln/detail/CVE-2016-9189</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/issues/2105\">https://github.com/python-pillow/Pillow/issues/2105</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f\">https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rwr3-c2q8-gm56\">https://github.com/advisories/GHSA-rwr3-c2q8-gm56</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201612-52\">https://security.gentoo.org/glsa/201612-52</a></li>\n<li><a href=\"http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html\">http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html</a></li>\n<li><a href=\"http://www.debian.org/security/2016/dsa-3710\">http://www.debian.org/security/2016/dsa-3710</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/94234\">http://www.securityfocus.com/bid/94234</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-8.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-8.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rwr3-c2q8-gm56",
            "title": "[pillow] Pillow Integer overflow in Map.c",
            "date_modified": "2024-10-08T13:06:31.000Z",
            "date_published": "2018-07-24T20:08:27.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rwr3-c2q8-gm56"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Pillow before 8.1.0, PcxDecode has a buffer over-read when decoding a crafted PCX file because the user-supplied stride value is trusted for buffer calculations.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-35653\">https://nvd.nist.gov/vuln/detail/CVE-2020-35653</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/index.html\">https://pillow.readthedocs.io/en/stable/releasenotes/index.html</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html\">https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf\">https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-f5g8-5qq7-938w\">https://github.com/advisories/GHSA-f5g8-5qq7-938w</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-69.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-69.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-f5g8-5qq7-938w",
            "title": "[pillow] Pillow Out-of-bounds Read",
            "date_modified": "2024-10-08T13:05:46.000Z",
            "date_published": "2021-03-18T19:55:41.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-f5g8-5qq7-938w"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Pillow before 8.1.0, SGIRleDecode has a 4-byte buffer over-read when decoding crafted SGI RLE image files because offsets and length tables are mishandled.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-35655\">https://nvd.nist.gov/vuln/detail/CVE-2020-35655</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/index.html\">https://pillow.readthedocs.io/en/stable/releasenotes/index.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf\">https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/7e95c63fa7f503f185d3d9eb16b9cee1e54d1e46\">https://github.com/python-pillow/Pillow/commit/7e95c63fa7f503f185d3d9eb16b9cee1e54d1e46</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hf64-x4gq-p99h\">https://github.com/advisories/GHSA-hf64-x4gq-p99h</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-71.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-71.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hf64-x4gq-p99h",
            "title": "[pillow] Pillow Out-of-bounds Read",
            "date_modified": "2024-10-08T13:05:15.000Z",
            "date_published": "2021-03-18T19:55:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hf64-x4gq-p99h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>There is a DoS vulnerability in Pillow before 6.2.2 caused by FpxImagePlugin.py calling the range function on an unvalidated 32-bit integer if the number of bands is large. On Windows running 32-bit Python, this results in an OverflowError or MemoryError due to the 2 GB limit. However, on Linux running 64-bit Python this results in the process being terminated by the OOM killer.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-19911\">https://nvd.nist.gov/vuln/detail/CVE-2019-19911</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/774e53bb132461d8d5ebefec1162e29ec0ebc63d\">https://github.com/python-pillow/Pillow/commit/774e53bb132461d8d5ebefec1162e29ec0ebc63d</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#622-2020-01-02\">https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#622-2020-01-02</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html\">https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html</a></li>\n<li><a href=\"https://www.debian.org/security/2020/dsa-4631\">https://www.debian.org/security/2020/dsa-4631</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5gm3-px64-rw72\">https://github.com/advisories/GHSA-5gm3-px64-rw72</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-172.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-172.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P</a></li>\n<li><a href=\"https://usn.ubuntu.com/4272-1\">https://usn.ubuntu.com/4272-1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5gm3-px64-rw72",
            "title": "[pillow] Uncontrolled Resource Consumption in Pillow",
            "date_modified": "2024-10-08T13:04:35.000Z",
            "date_published": "2020-04-01T16:36:44.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5gm3-px64-rw72"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>libImaging/TiffDecode.c</code> in Pillow before 6.2.2 has a TIFF decoding integer overflow, related to realloc.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-5310\">https://nvd.nist.gov/vuln/detail/CVE-2020-5310</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/4e2def2539ec13e53a82e06c4b3daf00454100c4\">https://github.com/python-pillow/Pillow/commit/4e2def2539ec13e53a82e06c4b3daf00454100c4</a></li>\n<li><a href=\"https://github.com/pypa/advisory-db/blob/7872b0a91b4d980f749e6d75a81f8cc1af32829f/vulns/pillow/PYSEC-2020-81.yaml\">https://github.com/pypa/advisory-db/blob/7872b0a91b4d980f749e6d75a81f8cc1af32829f/vulns/pillow/PYSEC-2020-81.yaml</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html\">https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vcqg-3p29-xw73\">https://github.com/advisories/GHSA-vcqg-3p29-xw73</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-81.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-81.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2MMU3WT2X64GS5WHDPKKC2WZA7UIIQ3A\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2MMU3WT2X64GS5WHDPKKC2WZA7UIIQ3A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P</a></li>\n<li><a href=\"https://usn.ubuntu.com/4272-1\">https://usn.ubuntu.com/4272-1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vcqg-3p29-xw73",
            "title": "[pillow] Integer overflow in Pillow",
            "date_modified": "2024-10-08T13:03:45.000Z",
            "date_published": "2021-11-03T18:04:41.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vcqg-3p29-xw73"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>ovirt-engine-sdk-python before 3.4.0.7 and 3.5.0.4 does not verify that the hostname of the remote endpoint matches the Common Name (CN) or subjectAltName as specified by its x.509 certificate in a TLS/SSL session. This could allow man-in-the-middle attackers to spoof remote endpoints via an arbitrary valid certificate.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-0161\">https://nvd.nist.gov/vuln/detail/CVE-2014-0161</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/cve-2014-0161\">https://access.redhat.com/security/cve/cve-2014-0161</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-0161\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-0161</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ovirt-engine-sdk-python/PYSEC-2020-245.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ovirt-engine-sdk-python/PYSEC-2020-245.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wf9j-m9fv-92gq\">https://github.com/advisories/GHSA-wf9j-m9fv-92gq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wf9j-m9fv-92gq",
            "title": "[ovirt-engine-sdk-python] ovirt-engine-sdk-python improper validation of hostname in x.509 certificate",
            "date_modified": "2024-10-08T12:56:51.000Z",
            "date_published": "2022-05-17T19:57:11.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wf9j-m9fv-92gq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"background\">Background</h3>\n<p>A variety of templates do not perform proper sanitization through HTML escaping.\nDue to the lack of sanitization and use of <code>jQuery.html()</code>, there are a whole host of XSS possibilities with specially crafted input to a variety of fields.</p>\n<h3 id=\"impact\">Impact</h3>\n<p>OMERO.web before 5.11.0 and OMERO.figure before 4.4.1.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Users should upgrade OMERO.web to 5.11.0 or higher and OMERO.figure to 4.4.1 or higher.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/ome/omero-web/security/advisories/GHSA-g67g-hvc3-xmvf\">https://github.com/ome/omero-web/security/advisories/GHSA-g67g-hvc3-xmvf</a></li>\n<li><a href=\"https://github.com/ome/omero-web/commit/0168067accde5e635341b3c714b1d53ae92ba424\">https://github.com/ome/omero-web/commit/0168067accde5e635341b3c714b1d53ae92ba424</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-41132\">https://nvd.nist.gov/vuln/detail/CVE-2021-41132</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/omero-figure/PYSEC-2021-379.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/omero-figure/PYSEC-2021-379.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/omero-web/PYSEC-2021-372.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/omero-web/PYSEC-2021-372.yaml</a></li>\n<li><a href=\"https://www.openmicroscopy.org/security/advisories/2021-SV3\">https://www.openmicroscopy.org/security/advisories/2021-SV3</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-g67g-hvc3-xmvf\">https://github.com/advisories/GHSA-g67g-hvc3-xmvf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-g67g-hvc3-xmvf",
            "title": "[omero-web] Inconsistent input sanitisation leads to XSS vectors",
            "date_modified": "2024-10-08T12:42:28.000Z",
            "date_published": "2021-10-14T21:19:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-g67g-hvc3-xmvf"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}