{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>Generation of Error Message Containing Sensitive Information vulnerability in Apache Software Foundation Apache Airflow.This issue affects Apache Airflow: before 2.5.2. The traceback contains information that might be useful for a potential attacker to better target their attack (Python/Airflow version, node name). This information should not be shown if traceback is shown to unauthenticated user.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-25695\">https://nvd.nist.gov/vuln/detail/CVE-2023-25695</a></li>\n<li><a href=\"https://github.com/apache/airflow/pull/29501\">https://github.com/apache/airflow/pull/29501</a></li>\n<li><a href=\"https://lists.apache.org/thread/z8w6ckzs61ql365tv4d19k82o67r15p2\">https://lists.apache.org/thread/z8w6ckzs61ql365tv4d19k82o67r15p2</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h6g5-wqqr-3mw3\">https://github.com/advisories/GHSA-h6g5-wqqr-3mw3</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h6g5-wqqr-3mw3",
            "title": "[apache-airflow] Sensitive Information in Error Messages in Apache Airflow",
            "date_modified": "2023-03-16T14:43:09.000Z",
            "date_published": "2023-03-15T12:30:19.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h6g5-wqqr-3mw3"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability was found in Mobile Vikings Django AJAX Utilities and classified as problematic. This issue affects the function Pagination of the file django_ajax/static/ajax-utilities/js/pagination.js of the component Backslash Handler. The manipulation of the argument url leads to cross site scripting. The attack may be initiated remotely. The patch is on commit  329eb1dd1580ca1f9d4f95bc69939833226515c9 which has been inclused in release 1.2.8. It is recommended to apply a patch to fix this issue. The associated identifier of this vulnerability is VDB-222611.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-20182\">https://nvd.nist.gov/vuln/detail/CVE-2017-20182</a></li>\n<li><a href=\"https://vuldb.com/?ctiid.222611\">https://vuldb.com/?ctiid.222611</a></li>\n<li><a href=\"https://vuldb.com/?id.222611\">https://vuldb.com/?id.222611</a></li>\n<li><a href=\"https://github.com/vikingco/django-ajax-utilities/commit/329eb1dd1580ca1f9d4f95bc69939833226515c9\">https://github.com/vikingco/django-ajax-utilities/commit/329eb1dd1580ca1f9d4f95bc69939833226515c9</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p4g9-c9qr-wmg5\">https://github.com/advisories/GHSA-p4g9-c9qr-wmg5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p4g9-c9qr-wmg5",
            "title": "[django-ajax-utilities] Cross-site Scripting in django-ajax-utilities",
            "date_modified": "2023-03-16T13:26:22.000Z",
            "date_published": "2023-03-10T03:30:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p4g9-c9qr-wmg5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>rami.io pretix before 4.17.1 allows OAuth application authorization from a logged-out session. The fixed versions are 4.15.1, 4.16.1, and 4.17.1.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27891\">https://nvd.nist.gov/vuln/detail/CVE-2023-27891</a></li>\n<li><a href=\"https://pretix.eu/about/en/blog/20230306-release-4171/\">https://pretix.eu/about/en/blog/20230306-release-4171/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r76w-3wwq-jv6v\">https://github.com/advisories/GHSA-r76w-3wwq-jv6v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v",
            "title": "[pretix] Insufficient Session Expiration in pretix",
            "date_modified": "2023-03-14T23:01:26.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>rami.io pretix before 4.17.1 allows OAuth application authorization from a logged-out session. The fixed versions are 4.15.1, 4.16.1, and 4.17.1.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27891\">https://nvd.nist.gov/vuln/detail/CVE-2023-27891</a></li>\n<li><a href=\"https://pretix.eu/about/en/blog/20230306-release-4171/\">https://pretix.eu/about/en/blog/20230306-release-4171/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r76w-3wwq-jv6v\">https://github.com/advisories/GHSA-r76w-3wwq-jv6v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v",
            "title": "[pretix] Insufficient Session Expiration in pretix",
            "date_modified": "2023-03-14T23:01:26.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>rami.io pretix before 4.17.1 allows OAuth application authorization from a logged-out session. The fixed versions are 4.15.1, 4.16.1, and 4.17.1.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27891\">https://nvd.nist.gov/vuln/detail/CVE-2023-27891</a></li>\n<li><a href=\"https://pretix.eu/about/en/blog/20230306-release-4171/\">https://pretix.eu/about/en/blog/20230306-release-4171/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r76w-3wwq-jv6v\">https://github.com/advisories/GHSA-r76w-3wwq-jv6v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v",
            "title": "[pretix] Insufficient Session Expiration in pretix",
            "date_modified": "2023-03-14T23:01:26.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the snowflake-connector-python PyPI package, when an attacker is able to supply arbitrary input to the get_file_transfer_type method.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42965\">https://nvd.nist.gov/vuln/detail/CVE-2022-42965</a></li>\n<li><a href=\"https://research.jfrog.com/vulnerabilities/snowflake-connector-python-redos-xray-257185/\">https://research.jfrog.com/vulnerabilities/snowflake-connector-python-redos-xray-257185/</a></li>\n<li><a href=\"https://github.com/snowflakedb/snowflake-connector-python/releases/tag/v2.8.2\">https://github.com/snowflakedb/snowflake-connector-python/releases/tag/v2.8.2</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-4r6j-fwcx-94cf\">https://github.com/advisories/GHSA-4r6j-fwcx-94cf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-4r6j-fwcx-94cf",
            "title": "[snowflake-connector-python] snowflake-connector-python is vulnerable to Regular Expression Denial of Service (ReDoS)",
            "date_modified": "2023-03-14T14:11:10.000Z",
            "date_published": "2022-11-10T12:01:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-4r6j-fwcx-94cf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Open redirect vulnerability exists in web2py versions prior to 2.23.1. When using the tool, a web2py user may be redirected to an arbitrary website by accessing a specially crafted URL. As a result, the user may become a victim of a phishing attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-22432\">https://nvd.nist.gov/vuln/detail/CVE-2023-22432</a></li>\n<li><a href=\"https://jvn.jp/en/jp/JVN78253670/\">https://jvn.jp/en/jp/JVN78253670/</a></li>\n<li><a href=\"http://web2py.com/\">http://web2py.com/</a></li>\n<li><a href=\"http://web2py.com/init/default/download\">http://web2py.com/init/default/download</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-w4r7-vm83-q2c7\">https://github.com/advisories/GHSA-w4r7-vm83-q2c7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-w4r7-vm83-q2c7",
            "title": "[web2py] Open redirect in web2py",
            "date_modified": "2023-03-13T20:41:01.000Z",
            "date_published": "2023-03-06T00:30:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-w4r7-vm83-q2c7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in openstack-glance. This issue could allow a remote, authenticated attacker to tamper with images, compromising the integrity of virtual machines created using these modified images.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-4134\">https://nvd.nist.gov/vuln/detail/CVE-2022-4134</a></li>\n<li><a href=\"https://bugs.launchpad.net/glance/+bug/1990157\">https://bugs.launchpad.net/glance/+bug/1990157</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=2147462\">https://bugzilla.redhat.com/show_bug.cgi?id=2147462</a></li>\n<li><a href=\"https://wiki.openstack.org/wiki/OSSN/OSSN-0090\">https://wiki.openstack.org/wiki/OSSN/OSSN-0090</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-0757\">https://nvd.nist.gov/vuln/detail/CVE-2016-0757</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5gp5-vxj6-4257\">https://github.com/advisories/GHSA-5gp5-vxj6-4257</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5gp5-vxj6-4257",
            "title": "[glance] OpenStack Glance Inclusion of Functionality from Untrusted Control Sphere vulnerability",
            "date_modified": "2023-03-13T19:18:28.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5gp5-vxj6-4257"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>OWSLib's XML parser (which supports both <code>lxml</code> and <code>xml.etree</code>) does not disable entity resolution for <code>lxml</code>, and could lead to arbitrary file reads from an attacker-controlled XML payload. This affects all XML parsing in the codebase.</p>\n<h3 id=\"patches\">Patches</h3>\n<ul>\n<li>Use only lxml for XML handling, adding <code>resolve_entities=False</code> to <code>lxml</code>'s parser: <a href=\"https://github.com/geopython/OWSLib/pull/863\">https://github.com/geopython/OWSLib/pull/863</a></li>\n</ul>\n<h3 id=\"workarounds\">Workarounds</h3>\n<pre><code class=\"language-python\">patch_well_known_namespaces(etree)\netree.set_default_parser(\n    parser=etree.XMLParser(resolve_entities=False)\n)\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><code>GHSL-2022-131</code></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/geopython/OWSLib/security/advisories/GHSA-8h9c-r582-mggc\">https://github.com/geopython/OWSLib/security/advisories/GHSA-8h9c-r582-mggc</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/pull/863\">https://github.com/geopython/OWSLib/pull/863</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/releases/tag/0.28.1\">https://github.com/geopython/OWSLib/releases/tag/0.28.1</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27476\">https://nvd.nist.gov/vuln/detail/CVE-2023-27476</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/pull/863/commits/b92687702be9576c0681bb11cad21eb631b9122f\">https://github.com/geopython/OWSLib/pull/863/commits/b92687702be9576c0681bb11cad21eb631b9122f</a></li>\n<li><a href=\"https://securitylab.github.com/advisories/GHSL-2022-131_owslib/\">https://securitylab.github.com/advisories/GHSL-2022-131_owslib/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8h9c-r582-mggc\">https://github.com/advisories/GHSA-8h9c-r582-mggc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8h9c-r582-mggc",
            "title": "[OWSLib] OWSLib vulnerable to XML External Entity (XXE) Injection",
            "date_modified": "2023-03-08T21:01:42.000Z",
            "date_published": "2023-03-07T20:41:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8h9c-r582-mggc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Denial of service could be caused to markdown-it-py, before v2.2.0, if an attacker was allowed to force null assertions with specially crafted input.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26303\">https://nvd.nist.gov/vuln/detail/CVE-2023-26303</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/commit/ae03c6107dfa18e648f6fdd1280f5b89092d5d49\">https://github.com/executablebooks/markdown-it-py/commit/ae03c6107dfa18e648f6fdd1280f5b89092d5d49</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/pull/246\">https://github.com/executablebooks/markdown-it-py/pull/246</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/commit/53ca3e9c2b9e9b295f6abf7f4ad2730a9b70f68c\">https://github.com/executablebooks/markdown-it-py/commit/53ca3e9c2b9e9b295f6abf7f4ad2730a9b70f68c</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vrjv-mxr7-vjf8\">https://github.com/advisories/GHSA-vrjv-mxr7-vjf8</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vrjv-mxr7-vjf8",
            "title": "[markdown-it-py] markdown-it-py Denial of Service vulnerability",
            "date_modified": "2023-03-03T23:17:36.000Z",
            "date_published": "2023-02-23T00:30:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vrjv-mxr7-vjf8"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site Scripting (XSS) - Reflected in GitHub repository modoboa/modoboa prior to 2.0.45.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-0949\">https://nvd.nist.gov/vuln/detail/CVE-2023-0949</a></li>\n<li><a href=\"https://github.com/modoboa/modoboa/commit/aa74e9a4a870162eea169e0a6a2eab841f8811b7\">https://github.com/modoboa/modoboa/commit/aa74e9a4a870162eea169e0a6a2eab841f8811b7</a></li>\n<li><a href=\"https://huntr.dev/bounties/ef87be4e-493b-4ee9-9738-44c55b8acc19\">https://huntr.dev/bounties/ef87be4e-493b-4ee9-9738-44c55b8acc19</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mgmm-cmhj-2h5f\">https://github.com/advisories/GHSA-mgmm-cmhj-2h5f</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mgmm-cmhj-2h5f",
            "title": "[modoboa] modoboa Cross-site Scripting vulnerability",
            "date_modified": "2023-03-10T05:06:03.000Z",
            "date_published": "2023-02-22T09:30:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mgmm-cmhj-2h5f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}