{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An authenticated member of one project can modify and delete members of another project, without knowledge of this other project's private code. This can be further exploited to access all bills of another project without knowledge of this other project's private code.</p>\n<p>With the default configuration, anybody is allowed to create a new project. An attacker can create a new project and then use it to become authenticated and exploit this flaw. As such, the exposure is similar to an unauthenticated attack, because it is trivial to become authenticated.</p>\n<h3 id=\"patches\">Patches</h3>\n<pre><code class=\"language-diff\"> ihatemoney/models.py | 4 ++--\n 1 file changed, 2 insertions(+), 2 deletions(-)\n\ndiff --git a/ihatemoney/models.py b/ihatemoney/models.py\nindex fe7b519..5691c75 100644\n--- a/ihatemoney/models.py\n+++ b/ihatemoney/models.py\n@@ -380,7 +380,7 @@ class Person(db.Model):\n         def get_by_name(self, name, project):\n             return (\n                 Person.query.filter(Person.name == name)\n-                .filter(Project.id == project.id)\n+                .filter(Person.project_id == project.id)\n                 .one()\n             )\n \n@@ -389,7 +389,7 @@ class Person(db.Model):\n                 project = g.project\n             return (\n                 Person.query.filter(Person.id == id)\n-                .filter(Project.id == project.id)\n+                .filter(Person.project_id == project.id)\n                 .one()\n             )\n \n</code></pre>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>To limit the impact, it is possible to disable public project creation by setting <code>ALLOW_PUBLIC_PROJECT_CREATION = False</code> in the configuration (see <a href=\"https://ihatemoney.readthedocs.io/en/latest/configuration.html\">documentation</a>). Existing users will still be able to exploit the flaw, but this will prevent an external attacker from creating a new project.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p><code>Person.query.get()</code> and <code>Person.query.get_by_name()</code> were mistakenly running a database join on the Project table without constraining the result.</p>\n<p>As a result, <code>Person.query.get(42, \"projectfoo\")</code> would return the Person with id=42, even if it is not associated to the project \"projectfoo\".  The only condition is that \"projectfoo\" must exist.</p>\n<p>This flaw can be exploited in several places:</p>\n<ol>\n<li><p>API: PUT requests to <code>/api/projects/&lt;project&gt;/members/&lt;personID&gt;</code> will succeed even though <code>&lt;personID&gt;</code> is not a member of <code>&lt;project&gt;</code>.</p>\n<p>This allows an authenticated attacker to alter the state of a member (name, weight, activated) in any project.  In addition, the altered member will no longer be associated with its original project but will be associated to the attacker project instead, breaking many features of IHateMoney.  For instance, bills referencing the altered member will no longer be visible in the original project.</p>\n<p>This causes an additional information disclosure and loss of integrity on bills: the attacker will now be able to see, edit and delete bills belonging to the altered member, because IHateMoney now believes that these bills are associated to the attacker project through the altered member.</p>\n<p>For instance, assume that <code>Person(id=42)</code> is a member of project \"targetProject\", and that the attacker has access to another project \"attackerProject\" with the private code \"attackerPassword\".  The attacker can modify <code>Person(id=42)</code> with this command:</p>\n<p>  $ curl -X PUT -d \"name=Pwn3d&amp;activated=1\" --basic -u attackerProject:attackerPassword http://$SERVER/api/projects/attackerProject/members/42</p>\n<p>The attacker can now see, edit and delete bills paid by <code>Person(id=42)</code> by simply browsing to http://$SERVER/attackerProject/</p>\n</li>\n<li><p>Editing a member through the web interface at <code>/&lt;project&gt;/members/&lt;personID&gt;/edit</code> will succeed even though <code>&lt;personID&gt;</code> is not a member of <code>&lt;project&gt;</code>.</p>\n<p>This is very similar to the PUT exploit.  Reusing the same example, the attacker needs to login to its \"attackerProject\" project with the private code \"attackerPassword\".  It can then alter the state of <code>Person(id=42)</code> by accessing the edit form at the following URL:</p>\n<p>  http://$SERVER/attackerProject/members/42/edit</p>\n<p>Again, as a result of the alteration, the altered member will become associated to the project \"attackerProject\", resulting in the same information disclosure and loss of integrity on bills.</p>\n</li>\n<li><p>API: DELETE requests to <code>/api/projects/&lt;project&gt;/members/&lt;personID&gt;</code> will similarly allow to delete the member <code>&lt;personID&gt;</code> even if it belongs to a different project than <code>&lt;project&gt;</code>.</p>\n<p>  $ curl -X DELETE --basic -u attackerProject:attackerPassword http://$SERVER/api/projects/attackerProject/members/42</p>\n<p>The impact is less serious than with PUT, because DELETE only deactivates a member (it does not really delete it).</p>\n</li>\n</ol>\n<p>All these exploits require authentication: an attacker needs to know a valid project name and its associated \"private code\".  Once this requirement is fullfilled, the attacker can exploit this flaw to alter the state of members in any other project, without needing to know the target project name or its private code.</p>\n<p><code>Person.query.get_by_name()</code> suffers from the same issue as <code>Person.query.get()</code>.  It has an additional issue: if multiple Person objects with the same name exist (this is possible if they are associated to different projects), <code>get_by_name()</code> will crash with <code>MultipleResultsFound</code> because of the call to <code>one()</code>.</p>\n<p>However, since <code>Person.query.get_by_name()</code> is currently not used anywhere in IHateMoney, the bug affecting this function has no impact and is not exploitable.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/spiral-project/ihatemoney/security/advisories/GHSA-67j9-c52g-w2q9\">https://github.com/spiral-project/ihatemoney/security/advisories/GHSA-67j9-c52g-w2q9</a></li>\n<li><a href=\"https://github.com/spiral-project/ihatemoney/commit/8d77cf5d5646e1d2d8ded13f0660638f57e98471\">https://github.com/spiral-project/ihatemoney/commit/8d77cf5d5646e1d2d8ded13f0660638f57e98471</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-15120\">https://nvd.nist.gov/vuln/detail/CVE-2020-15120</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ihatemoney/PYSEC-2020-264.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ihatemoney/PYSEC-2020-264.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-67j9-c52g-w2q9\">https://github.com/advisories/GHSA-67j9-c52g-w2q9</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-67j9-c52g-w2q9",
            "title": "[ihatemoney] Authorization Bypass in I hate money",
            "date_modified": "2024-09-23T17:00:56.000Z",
            "date_published": "2020-07-27T17:47:52.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-67j9-c52g-w2q9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site scripting (XSS) vulnerability in IPython 3.x before 3.2 allows remote attackers to inject arbitrary web script or HTML via vectors involving JSON error messages and the /api/contents path.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-4706\">https://nvd.nist.gov/vuln/detail/CVE-2015-4706</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/7222bd53ad089a65fd610fab4626f9d0ab47dfce\">https://github.com/ipython/ipython/commit/7222bd53ad089a65fd610fab4626f9d0ab47dfce</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/c2078a53543ed502efd968649fee1125e0eb549c\">https://github.com/ipython/ipython/commit/c2078a53543ed502efd968649fee1125e0eb549c</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1235688\">https://bugzilla.redhat.com/show_bug.cgi?id=1235688</a></li>\n<li><a href=\"https://ipython.org/ipython-doc/3/whatsnew/version3.html\">https://ipython.org/ipython-doc/3/whatsnew/version3.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2015/06/22/7\">http://www.openwall.com/lists/oss-security/2015/06/22/7</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q326-jhw3-699g\">https://github.com/advisories/GHSA-q326-jhw3-699g</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2017-45.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2017-45.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20200516112656/http://www.securityfocus.com/bid/75328\">https://web.archive.org/web/20200516112656/http://www.securityfocus.com/bid/75328</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q326-jhw3-699g",
            "title": "[ipython] Improper Neutralization of Input During Web Page Generation in IPython",
            "date_modified": "2024-09-23T16:46:29.000Z",
            "date_published": "2022-05-17T00:36:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q326-jhw3-699g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site scripting (XSS) vulnerability in the file browser in notebook/notebookapp.py in IPython Notebook before 3.2.2 and Jupyter Notebook 4.0.x before 4.0.5 allows remote attackers to inject arbitrary web script or HTML via a folder name.  NOTE: this was originally reported as a cross-site request forgery (CSRF) vulnerability, but this may be inaccurate.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-6938\">https://nvd.nist.gov/vuln/detail/CVE-2015-6938</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/3ab41641cf6fce3860c73d5cf4645aa12e1e5892\">https://github.com/ipython/ipython/commit/3ab41641cf6fce3860c73d5cf4645aa12e1e5892</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/35f32dd2da804d108a3a3585b69ec3295b2677ed\">https://github.com/jupyter/notebook/commit/35f32dd2da804d108a3a3585b69ec3295b2677ed</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/dd9876381f0ef09873d8c5f6f2063269172331e3\">https://github.com/jupyter/notebook/commit/dd9876381f0ef09873d8c5f6f2063269172331e3</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1259405\">https://bugzilla.redhat.com/show_bug.cgi?id=1259405</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166460.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166460.html</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166471.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166471.html</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-September/167670.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-September/167670.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-10/msg00016.html\">http://lists.opensuse.org/opensuse-updates/2015-10/msg00016.html</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2015/q3/474\">http://seclists.org/oss-sec/2015/q3/474</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2015/q3/544\">http://seclists.org/oss-sec/2015/q3/544</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-4vwq-x64q-j4cj\">https://github.com/advisories/GHSA-4vwq-x64q-j4cj</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2015-24.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2015-24.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2015-26.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2015-26.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-4vwq-x64q-j4cj",
            "title": "[ipython] Improper Neutralization of Input During Web Page Generation in Jupyter Notebook",
            "date_modified": "2024-09-23T16:44:05.000Z",
            "date_published": "2022-05-14T02:04:49.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-4vwq-x64q-j4cj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site scripting (XSS) vulnerability in the file browser in notebook/notebookapp.py in IPython Notebook before 3.2.2 and Jupyter Notebook 4.0.x before 4.0.5 allows remote attackers to inject arbitrary web script or HTML via a folder name.  NOTE: this was originally reported as a cross-site request forgery (CSRF) vulnerability, but this may be inaccurate.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-6938\">https://nvd.nist.gov/vuln/detail/CVE-2015-6938</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/3ab41641cf6fce3860c73d5cf4645aa12e1e5892\">https://github.com/ipython/ipython/commit/3ab41641cf6fce3860c73d5cf4645aa12e1e5892</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/35f32dd2da804d108a3a3585b69ec3295b2677ed\">https://github.com/jupyter/notebook/commit/35f32dd2da804d108a3a3585b69ec3295b2677ed</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/dd9876381f0ef09873d8c5f6f2063269172331e3\">https://github.com/jupyter/notebook/commit/dd9876381f0ef09873d8c5f6f2063269172331e3</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1259405\">https://bugzilla.redhat.com/show_bug.cgi?id=1259405</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166460.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166460.html</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166471.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-September/166471.html</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-September/167670.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-September/167670.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-10/msg00016.html\">http://lists.opensuse.org/opensuse-updates/2015-10/msg00016.html</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2015/q3/474\">http://seclists.org/oss-sec/2015/q3/474</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2015/q3/544\">http://seclists.org/oss-sec/2015/q3/544</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-4vwq-x64q-j4cj\">https://github.com/advisories/GHSA-4vwq-x64q-j4cj</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2015-24.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2015-24.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2015-26.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2015-26.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-4vwq-x64q-j4cj",
            "title": "[notebook] Improper Neutralization of Input During Web Page Generation in Jupyter Notebook",
            "date_modified": "2024-09-23T16:44:05.000Z",
            "date_published": "2022-05-14T02:04:49.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-4vwq-x64q-j4cj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in management/commands/hyperkitty_import.py in HyperKitty prior to 1.3.5. When importing a private mailing list's archives, these archives are publicly visible for the duration of the import. For example, sensitive information might be available on the web for an hour during a large migration from Mailman 2 to Mailman 3.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-33038\">https://nvd.nist.gov/vuln/detail/CVE-2021-33038</a></li>\n<li><a href=\"https://gitlab.com/mailman/hyperkitty/-/commit/9025324597d60b2dff740e49b70b15589d6804fa\">https://gitlab.com/mailman/hyperkitty/-/commit/9025324597d60b2dff740e49b70b15589d6804fa</a></li>\n<li><a href=\"https://gitlab.com/mailman/hyperkitty/-/issues/380\">https://gitlab.com/mailman/hyperkitty/-/issues/380</a></li>\n<li><a href=\"https://www.debian.org/security/2021/dsa-4922\">https://www.debian.org/security/2021/dsa-4922</a></li>\n<li><a href=\"https://gitlab.com/mailman/hyperkitty/-/blob/master/doc/news.rst#L83-L87\">https://gitlab.com/mailman/hyperkitty/-/blob/master/doc/news.rst#L83-L87</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h39g-q63v-4h9p\">https://github.com/advisories/GHSA-h39g-q63v-4h9p</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/hyperkitty/PYSEC-2021-77.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/hyperkitty/PYSEC-2021-77.yaml</a></li>\n<li><a href=\"https://techblog.wikimedia.org/2021/06/11/discovering-and-fixing-cve-2021-33038-in-mailman3\">https://techblog.wikimedia.org/2021/06/11/discovering-and-fixing-cve-2021-33038-in-mailman3</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h39g-q63v-4h9p",
            "title": "[HyperKitty] Exposure of sensitive information to an unauthorized actor in HyperKitty",
            "date_modified": "2024-09-23T16:25:28.000Z",
            "date_published": "2021-06-01T21:56:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h39g-q63v-4h9p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>The <code>pool-upgrade</code> request handler in Indy-Node <code>&lt;=1.12.4</code> allows an improperly authenticated attacker to remotely execute code on nodes within the network.</p>\n<p>Network operators are strongly encouraged to upgrade to the latest Indy-Node release <code>&gt;=1.12.5</code> as soon as possible.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The <code>pool-upgrade</code> request handler in Indy-Node <code>&gt;=1.12.5</code> has been updated to properly authenticate <code>pool-upgrade</code> transactions before any processing is performed by the request handler.  The transactions are further sanitized to prevent remote code execution.</p>\n<h3 id=\"mitigations\">Mitigations</h3>\n<p>Network operators are strongly encouraged to upgrade to the latest Indy-Node release <code>&gt;=1.12.5</code> as soon as possible.</p>\n<h3 id=\"acknowledgements\">Acknowledgements</h3>\n<p>Thank you to @shakreiner at CyberArk Labs for finding and responsibly disclosing this issue.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/hyperledger/indy-node/security/advisories/GHSA-r6v9-p59m-gj2p\">https://github.com/hyperledger/indy-node/security/advisories/GHSA-r6v9-p59m-gj2p</a></li>\n<li><a href=\"https://github.com/hyperledger/indy-node/commit/fe507474f77084faef4539101e2bbb4d508a97f5\">https://github.com/hyperledger/indy-node/commit/fe507474f77084faef4539101e2bbb4d508a97f5</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-31020\">https://nvd.nist.gov/vuln/detail/CVE-2022-31020</a></li>\n<li><a href=\"https://github.com/hyperledger/indy-node/releases/tag/v1.12.5\">https://github.com/hyperledger/indy-node/releases/tag/v1.12.5</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/indy-node/PYSEC-2022-265.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/indy-node/PYSEC-2022-265.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r6v9-p59m-gj2p\">https://github.com/advisories/GHSA-r6v9-p59m-gj2p</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r6v9-p59m-gj2p",
            "title": "[indy-node] Indy's NODE_UPGRADE transaction vulnerable to remote code execution",
            "date_modified": "2024-09-23T16:24:28.000Z",
            "date_published": "2022-09-02T21:55:20.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r6v9-p59m-gj2p"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>A malicious server which responds with long series of <code>\\xa0</code> characters in the <code>www-authenticate</code> header may cause Denial of Service (CPU burn while parsing header) of the httplib2 client accessing said server.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Version 0.19.0 contains new implementation of auth headers parsing, using pyparsing library.\n<a href=\"https://github.com/httplib2/httplib2/pull/182\">https://github.com/httplib2/httplib2/pull/182</a></p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<pre><code class=\"language-py\">import httplib2\nhttplib2.USE_WWW_AUTH_STRICT_PARSING = True\n</code></pre>\n<h3 id=\"technical-details\">Technical Details</h3>\n<p>The vulnerable regular expression is <a href=\"https://github.com/httplib2/httplib2/blob/595e248d0958c00e83cb28f136a2a54772772b50/python3/httplib2/__init__.py#L336-L338\">https://github.com/httplib2/httplib2/blob/595e248d0958c00e83cb28f136a2a54772772b50/python3/httplib2/__init__.py#L336-L338</a></p>\n<p>The section before the equals sign contains multiple overlapping groups. Ignoring the optional part containing a comma, we have:</p>\n<pre><code>\\s*[^ \\t\\r\\n=]+\\s*=\n</code></pre>\n<p>Since all three infinitely repeating groups accept the non-breaking space character <code>\\xa0</code>, a long string of <code>\\xa0</code> causes catastrophic backtracking.</p>\n<p>The complexity is cubic, so doubling the length of the malicious string of <code>\\xa0</code> makes processing take 8 times as long.</p>\n<h3 id=\"reproduction-steps\">Reproduction Steps</h3>\n<p>Run a malicious server which responds with</p>\n<pre><code>www-authenticate: x \\xa0\\xa0\\xa0\\xa0x\n</code></pre>\n<p>but with many more <code>\\xa0</code> characters.</p>\n<p>An example malicious python server is below:</p>\n<pre><code class=\"language-py\">from http.server import BaseHTTPRequestHandler, HTTPServer\n\ndef make_header_value(n_spaces):\n    repeat = \"\\xa0\" * n_spaces\n    return f\"x {repeat}x\"\n\nclass Handler(BaseHTTPRequestHandler):\n    def do_GET(self):\n        self.log_request(401)\n        self.send_response_only(401)  # Don't bother sending Server and Date\n        n_spaces = (\n            int(self.path[1:])  # Can GET e.g. /100 to test shorter sequences\n            if len(self.path) &gt; 1 else\n            65512  # Max header line length 65536\n        )\n        value = make_header_value(n_spaces)\n        self.send_header(\"www-authenticate\", value)  # This header can actually be sent multiple times\n        self.end_headers()\n\nif __name__ == \"__main__\":\n    HTTPServer((\"\", 1337), Handler).serve_forever()\n</code></pre>\n<p>Connect to the server with httplib2:</p>\n<pre><code class=\"language-py\">import httplib2\nhttplib2.Http(\".cache\").request(\"http://localhost:1337\", \"GET\")\n</code></pre>\n<p>To benchmark performance with shorter strings, you can set the path to a number e.g. <a href=\"http://localhost:1337/1000\">http://localhost:1337/1000</a></p>\n<h3 id=\"references\">References</h3>\n<p>Thanks to <a href=\"https://github.com/b-c-ds\">Ben Caller</a> (<a href=\"https://doyensec.com\">Doyensec</a>) for finding vulnerability and discrete notification.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in <a href=\"https://github.com/httplib2/httplib2/issues/new\">httplib2</a></li>\n<li>Email <a href=\"mailto:temotor@gmail.com\">current maintainer at 2021-01</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/httplib2/httplib2/security/advisories/GHSA-93xj-8mrv-444m\">https://github.com/httplib2/httplib2/security/advisories/GHSA-93xj-8mrv-444m</a></li>\n<li><a href=\"https://github.com/httplib2/httplib2/pull/182\">https://github.com/httplib2/httplib2/pull/182</a></li>\n<li><a href=\"https://github.com/httplib2/httplib2/commit/bd9ee252c8f099608019709e22c0d705e98d26bc\">https://github.com/httplib2/httplib2/commit/bd9ee252c8f099608019709e22c0d705e98d26bc</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-21240\">https://nvd.nist.gov/vuln/detail/CVE-2021-21240</a></li>\n<li><a href=\"https://pypi.org/project/httplib2\">https://pypi.org/project/httplib2</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/httplib2/PYSEC-2021-16.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/httplib2/PYSEC-2021-16.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-93xj-8mrv-444m\">https://github.com/advisories/GHSA-93xj-8mrv-444m</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-93xj-8mrv-444m",
            "title": "[httplib2] Regular Expression Denial of Service (REDoS) in httplib2",
            "date_modified": "2024-09-23T16:13:17.000Z",
            "date_published": "2021-02-08T19:41:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-93xj-8mrv-444m"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h2 id=\"cross-site-scripting-xss-vulnerability-in-administration-interface\">Cross-Site Scripting (XSS) vulnerability in administration interface</h2>\n<h3 id=\"impact\">Impact</h3>\n<p>A Cross-Site Scripting (XSS) vulnerability was discovered when rendering JSON for a record in the administration interface. The vulnerability could be exploited by e.g. a user who had access to upload a new record, that an admin user would then later view in the admin interface.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>All supported versions of Invenio-Records have been patched. You should upgrade to either v1.0.1, v1.1.1 or v1.2.2</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Email us at <a href=\"mailto:info@inveniosoftware.org\">info@inveniosoftware.org</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-records/security/advisories/GHSA-vxh3-mvv7-265j\">https://github.com/inveniosoftware/invenio-records/security/advisories/GHSA-vxh3-mvv7-265j</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-1020003\">https://nvd.nist.gov/vuln/detail/CVE-2019-1020003</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vxh3-mvv7-265j\">https://github.com/advisories/GHSA-vxh3-mvv7-265j</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-records/PYSEC-2019-27.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-records/PYSEC-2019-27.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vxh3-mvv7-265j",
            "title": "[invenio-records] Cross-site scripting invenio-records",
            "date_modified": "2024-09-23T16:09:06.000Z",
            "date_published": "2019-07-16T00:52:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vxh3-mvv7-265j"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h2 id=\"cross-site-scripting-xss-vulnerability-in-administration-interface\">Cross-Site Scripting (XSS) vulnerability in administration interface</h2>\n<h3 id=\"impact\">Impact</h3>\n<p>A Cross-Site Scripting (XSS) vulnerability was discovered when rendering JSON for a record in the administration interface. The vulnerability could be exploited by e.g. a user who had access to upload a new record, that an admin user would then later view in the admin interface.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>All supported versions of Invenio-Records have been patched. You should upgrade to either v1.0.1, v1.1.1 or v1.2.2</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Email us at <a href=\"mailto:info@inveniosoftware.org\">info@inveniosoftware.org</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-records/security/advisories/GHSA-vxh3-mvv7-265j\">https://github.com/inveniosoftware/invenio-records/security/advisories/GHSA-vxh3-mvv7-265j</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-1020003\">https://nvd.nist.gov/vuln/detail/CVE-2019-1020003</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vxh3-mvv7-265j\">https://github.com/advisories/GHSA-vxh3-mvv7-265j</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-records/PYSEC-2019-27.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-records/PYSEC-2019-27.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vxh3-mvv7-265j",
            "title": "[invenio-records] Cross-site scripting invenio-records",
            "date_modified": "2024-09-23T16:09:06.000Z",
            "date_published": "2019-07-16T00:52:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vxh3-mvv7-265j"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h2 id=\"cross-site-scripting-xss-vulnerability-in-administration-interface\">Cross-Site Scripting (XSS) vulnerability in administration interface</h2>\n<h3 id=\"impact\">Impact</h3>\n<p>A Cross-Site Scripting (XSS) vulnerability was discovered when rendering JSON for a record in the administration interface. The vulnerability could be exploited by e.g. a user who had access to upload a new record, that an admin user would then later view in the admin interface.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>All supported versions of Invenio-Records have been patched. You should upgrade to either v1.0.1, v1.1.1 or v1.2.2</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Email us at <a href=\"mailto:info@inveniosoftware.org\">info@inveniosoftware.org</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-records/security/advisories/GHSA-vxh3-mvv7-265j\">https://github.com/inveniosoftware/invenio-records/security/advisories/GHSA-vxh3-mvv7-265j</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-1020003\">https://nvd.nist.gov/vuln/detail/CVE-2019-1020003</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vxh3-mvv7-265j\">https://github.com/advisories/GHSA-vxh3-mvv7-265j</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-records/PYSEC-2019-27.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-records/PYSEC-2019-27.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vxh3-mvv7-265j",
            "title": "[invenio-records] Cross-site scripting invenio-records",
            "date_modified": "2024-09-23T16:09:06.000Z",
            "date_published": "2019-07-16T00:52:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vxh3-mvv7-265j"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site scripting (XSS) vulnerability in IPython before 3.2 allows remote attackers to inject arbitrary web script or HTML via vectors involving JSON error messages and the /api/notebooks path.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-4707\">https://nvd.nist.gov/vuln/detail/CVE-2015-4707</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/7222bd53ad089a65fd610fab4626f9d0ab47dfce\">https://github.com/ipython/ipython/commit/7222bd53ad089a65fd610fab4626f9d0ab47dfce</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/c2078a53543ed502efd968649fee1125e0eb549c\">https://github.com/ipython/ipython/commit/c2078a53543ed502efd968649fee1125e0eb549c</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1235688\">https://bugzilla.redhat.com/show_bug.cgi?id=1235688</a></li>\n<li><a href=\"https://ipython.org/ipython-doc/3/whatsnew/version3.html\">https://ipython.org/ipython-doc/3/whatsnew/version3.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2015/06/22/7\">http://www.openwall.com/lists/oss-security/2015/06/22/7</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-66gw-5xpf-gfp5\">https://github.com/advisories/GHSA-66gw-5xpf-gfp5</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2017-46.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2017-46.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20200227150022/https://www.securityfocus.com/bid/75328\">https://web.archive.org/web/20200227150022/https://www.securityfocus.com/bid/75328</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-66gw-5xpf-gfp5",
            "title": "[ipython] Improper Neutralization of Input During Web Page Generation in IPython",
            "date_modified": "2024-09-23T16:09:37.000Z",
            "date_published": "2022-05-13T01:31:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-66gw-5xpf-gfp5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Invenio-Drafts-Resources does not properly check permissions when a record is published. The vulnerability is exploitable in a default installation of InvenioRDM. An authenticated user is able via REST API calls to publish draft records of other users if they know the record identifier and the draft validates (e.g. all require fields filled out). An attacker is not able to modify the data in the record, and thus e.g. <em>cannot</em> change a record from restricted to public.</p>\n<h3 id=\"details\">Details</h3>\n<p>The service's <code>publish()</code> method contains the following permission check:</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\")\n</code></pre>\n<p>However, the record should have been passed into the permission check so that the need generators have access to e.g. the record owner.</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\", record=record)\n</code></pre>\n<p>The bug is activated in Invenio-RDM-Records which has a need generator called <code>RecordOwners()</code>, which when no record is passed in defaults to allow any authenticated user:</p>\n<pre><code class=\"language-python\">class RecordOwners(Generator):\n    def needs(self, record=None, **kwargs):\n        if record is None:\n            return [authenticated_user]\n    # ...\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem is patched in Invenio-Drafts-Resources v0.13.7 and 0.14.6+, which is part of InvenioRDM v6.0.1 and InvenioRDM v7.0 respectively.</p>\n<p>You can verify the version installed of Invenio-Drafts-Resources via PIP:</p>\n<pre><code class=\"language-console\">cd ~/src/my-site\npipenv run pip freeze | grep invenio-drafts-resources\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://invenio.readthedocs.io/en/latest/community/security-policy.html\">Security policy</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Chat with us on Discord: <a href=\"https://discord.gg/8qatqBC\">https://discord.gg/8qatqBC</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-43781\">https://nvd.nist.gov/vuln/detail/CVE-2021-43781</a></li>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626\">https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/advisories/GHSA-xr38-w74q-r8jv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv",
            "title": "[invenio-app-rdm] Permissions not properly checked in Invenio-Drafts-Resources",
            "date_modified": "2024-09-23T16:02:07.000Z",
            "date_published": "2021-12-06T23:57:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Invenio-Drafts-Resources does not properly check permissions when a record is published. The vulnerability is exploitable in a default installation of InvenioRDM. An authenticated user is able via REST API calls to publish draft records of other users if they know the record identifier and the draft validates (e.g. all require fields filled out). An attacker is not able to modify the data in the record, and thus e.g. <em>cannot</em> change a record from restricted to public.</p>\n<h3 id=\"details\">Details</h3>\n<p>The service's <code>publish()</code> method contains the following permission check:</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\")\n</code></pre>\n<p>However, the record should have been passed into the permission check so that the need generators have access to e.g. the record owner.</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\", record=record)\n</code></pre>\n<p>The bug is activated in Invenio-RDM-Records which has a need generator called <code>RecordOwners()</code>, which when no record is passed in defaults to allow any authenticated user:</p>\n<pre><code class=\"language-python\">class RecordOwners(Generator):\n    def needs(self, record=None, **kwargs):\n        if record is None:\n            return [authenticated_user]\n    # ...\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem is patched in Invenio-Drafts-Resources v0.13.7 and 0.14.6+, which is part of InvenioRDM v6.0.1 and InvenioRDM v7.0 respectively.</p>\n<p>You can verify the version installed of Invenio-Drafts-Resources via PIP:</p>\n<pre><code class=\"language-console\">cd ~/src/my-site\npipenv run pip freeze | grep invenio-drafts-resources\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://invenio.readthedocs.io/en/latest/community/security-policy.html\">Security policy</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Chat with us on Discord: <a href=\"https://discord.gg/8qatqBC\">https://discord.gg/8qatqBC</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-43781\">https://nvd.nist.gov/vuln/detail/CVE-2021-43781</a></li>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626\">https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/advisories/GHSA-xr38-w74q-r8jv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv",
            "title": "[invenio-rdm-records] Permissions not properly checked in Invenio-Drafts-Resources",
            "date_modified": "2024-09-23T16:02:07.000Z",
            "date_published": "2021-12-06T23:57:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Invenio-Drafts-Resources does not properly check permissions when a record is published. The vulnerability is exploitable in a default installation of InvenioRDM. An authenticated user is able via REST API calls to publish draft records of other users if they know the record identifier and the draft validates (e.g. all require fields filled out). An attacker is not able to modify the data in the record, and thus e.g. <em>cannot</em> change a record from restricted to public.</p>\n<h3 id=\"details\">Details</h3>\n<p>The service's <code>publish()</code> method contains the following permission check:</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\")\n</code></pre>\n<p>However, the record should have been passed into the permission check so that the need generators have access to e.g. the record owner.</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\", record=record)\n</code></pre>\n<p>The bug is activated in Invenio-RDM-Records which has a need generator called <code>RecordOwners()</code>, which when no record is passed in defaults to allow any authenticated user:</p>\n<pre><code class=\"language-python\">class RecordOwners(Generator):\n    def needs(self, record=None, **kwargs):\n        if record is None:\n            return [authenticated_user]\n    # ...\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem is patched in Invenio-Drafts-Resources v0.13.7 and 0.14.6+, which is part of InvenioRDM v6.0.1 and InvenioRDM v7.0 respectively.</p>\n<p>You can verify the version installed of Invenio-Drafts-Resources via PIP:</p>\n<pre><code class=\"language-console\">cd ~/src/my-site\npipenv run pip freeze | grep invenio-drafts-resources\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://invenio.readthedocs.io/en/latest/community/security-policy.html\">Security policy</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Chat with us on Discord: <a href=\"https://discord.gg/8qatqBC\">https://discord.gg/8qatqBC</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-43781\">https://nvd.nist.gov/vuln/detail/CVE-2021-43781</a></li>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626\">https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/advisories/GHSA-xr38-w74q-r8jv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv",
            "title": "[invenio-drafts-resources] Permissions not properly checked in Invenio-Drafts-Resources",
            "date_modified": "2024-09-23T16:02:07.000Z",
            "date_published": "2021-12-06T23:57:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Invenio-Drafts-Resources does not properly check permissions when a record is published. The vulnerability is exploitable in a default installation of InvenioRDM. An authenticated user is able via REST API calls to publish draft records of other users if they know the record identifier and the draft validates (e.g. all require fields filled out). An attacker is not able to modify the data in the record, and thus e.g. <em>cannot</em> change a record from restricted to public.</p>\n<h3 id=\"details\">Details</h3>\n<p>The service's <code>publish()</code> method contains the following permission check:</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\")\n</code></pre>\n<p>However, the record should have been passed into the permission check so that the need generators have access to e.g. the record owner.</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\", record=record)\n</code></pre>\n<p>The bug is activated in Invenio-RDM-Records which has a need generator called <code>RecordOwners()</code>, which when no record is passed in defaults to allow any authenticated user:</p>\n<pre><code class=\"language-python\">class RecordOwners(Generator):\n    def needs(self, record=None, **kwargs):\n        if record is None:\n            return [authenticated_user]\n    # ...\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem is patched in Invenio-Drafts-Resources v0.13.7 and 0.14.6+, which is part of InvenioRDM v6.0.1 and InvenioRDM v7.0 respectively.</p>\n<p>You can verify the version installed of Invenio-Drafts-Resources via PIP:</p>\n<pre><code class=\"language-console\">cd ~/src/my-site\npipenv run pip freeze | grep invenio-drafts-resources\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://invenio.readthedocs.io/en/latest/community/security-policy.html\">Security policy</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Chat with us on Discord: <a href=\"https://discord.gg/8qatqBC\">https://discord.gg/8qatqBC</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-43781\">https://nvd.nist.gov/vuln/detail/CVE-2021-43781</a></li>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626\">https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/advisories/GHSA-xr38-w74q-r8jv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv",
            "title": "[invenio-rdm-records] Permissions not properly checked in Invenio-Drafts-Resources",
            "date_modified": "2024-09-23T16:02:07.000Z",
            "date_published": "2021-12-06T23:57:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Invenio-Drafts-Resources does not properly check permissions when a record is published. The vulnerability is exploitable in a default installation of InvenioRDM. An authenticated user is able via REST API calls to publish draft records of other users if they know the record identifier and the draft validates (e.g. all require fields filled out). An attacker is not able to modify the data in the record, and thus e.g. <em>cannot</em> change a record from restricted to public.</p>\n<h3 id=\"details\">Details</h3>\n<p>The service's <code>publish()</code> method contains the following permission check:</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\")\n</code></pre>\n<p>However, the record should have been passed into the permission check so that the need generators have access to e.g. the record owner.</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\", record=record)\n</code></pre>\n<p>The bug is activated in Invenio-RDM-Records which has a need generator called <code>RecordOwners()</code>, which when no record is passed in defaults to allow any authenticated user:</p>\n<pre><code class=\"language-python\">class RecordOwners(Generator):\n    def needs(self, record=None, **kwargs):\n        if record is None:\n            return [authenticated_user]\n    # ...\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem is patched in Invenio-Drafts-Resources v0.13.7 and 0.14.6+, which is part of InvenioRDM v6.0.1 and InvenioRDM v7.0 respectively.</p>\n<p>You can verify the version installed of Invenio-Drafts-Resources via PIP:</p>\n<pre><code class=\"language-console\">cd ~/src/my-site\npipenv run pip freeze | grep invenio-drafts-resources\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://invenio.readthedocs.io/en/latest/community/security-policy.html\">Security policy</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Chat with us on Discord: <a href=\"https://discord.gg/8qatqBC\">https://discord.gg/8qatqBC</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-43781\">https://nvd.nist.gov/vuln/detail/CVE-2021-43781</a></li>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626\">https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/advisories/GHSA-xr38-w74q-r8jv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv",
            "title": "[invenio-app-rdm] Permissions not properly checked in Invenio-Drafts-Resources",
            "date_modified": "2024-09-23T16:02:07.000Z",
            "date_published": "2021-12-06T23:57:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Invenio-Drafts-Resources does not properly check permissions when a record is published. The vulnerability is exploitable in a default installation of InvenioRDM. An authenticated user is able via REST API calls to publish draft records of other users if they know the record identifier and the draft validates (e.g. all require fields filled out). An attacker is not able to modify the data in the record, and thus e.g. <em>cannot</em> change a record from restricted to public.</p>\n<h3 id=\"details\">Details</h3>\n<p>The service's <code>publish()</code> method contains the following permission check:</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\")\n</code></pre>\n<p>However, the record should have been passed into the permission check so that the need generators have access to e.g. the record owner.</p>\n<pre><code class=\"language-python\">def publish(..):\n    self.require_permission(identity, \"publish\", record=record)\n</code></pre>\n<p>The bug is activated in Invenio-RDM-Records which has a need generator called <code>RecordOwners()</code>, which when no record is passed in defaults to allow any authenticated user:</p>\n<pre><code class=\"language-python\">class RecordOwners(Generator):\n    def needs(self, record=None, **kwargs):\n        if record is None:\n            return [authenticated_user]\n    # ...\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem is patched in Invenio-Drafts-Resources v0.13.7 and 0.14.6+, which is part of InvenioRDM v6.0.1 and InvenioRDM v7.0 respectively.</p>\n<p>You can verify the version installed of Invenio-Drafts-Resources via PIP:</p>\n<pre><code class=\"language-console\">cd ~/src/my-site\npipenv run pip freeze | grep invenio-drafts-resources\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://invenio.readthedocs.io/en/latest/community/security-policy.html\">Security policy</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Chat with us on Discord: <a href=\"https://discord.gg/8qatqBC\">https://discord.gg/8qatqBC</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/inveniosoftware/invenio-drafts-resources/security/advisories/GHSA-xr38-w74q-r8jv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-43781\">https://nvd.nist.gov/vuln/detail/CVE-2021-43781</a></li>\n<li><a href=\"https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626\">https://github.com/inveniosoftware/invenio-drafts-resources/commit/039b0cff1ad4b952000f4d8c3a93f347108b6626</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app-rdm/PYSEC-2021-837.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-drafts-resources/PYSEC-2021-836.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xr38-w74q-r8jv\">https://github.com/advisories/GHSA-xr38-w74q-r8jv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv",
            "title": "[invenio-drafts-resources] Permissions not properly checked in Invenio-Drafts-Resources",
            "date_modified": "2024-09-23T16:02:07.000Z",
            "date_published": "2021-12-06T23:57:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xr38-w74q-r8jv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h2 id=\"app_allowed_hosts-not-always-preventing-host-header-injection\">APP_ALLOWED_HOSTS not always preventing host header injection</h2>\n<h3 id=\"impact\">Impact</h3>\n<p>A possible host header injection attack have been identified in Invenio-App.  For an attack to be possible, all conditions below must be met:</p>\n<ol>\n<li>Your webserver must have been configured to route all requests to your application. </li>\n<li>You must have relied on <code>APP_ALLOWED_HOSTS</code> configuration variable to whitelist allowed host headers.</li>\n<li>Flask's <code>request.host</code> must not have been evaluated during request handling.</li>\n</ol>\n<p>An example of a view which does not evalute <code>request.host</code> is a simple view using just <code>url_for</code> to generate an external URL (similar is possible when rendering just a Jinja template):</p>\n<pre><code class=\"language-python\">@app.route('/')\ndef index():\n    return url_for('index_url', _external=True)\n</code></pre>\n<p>This happens, because Werkzeug's trusted host feature, which <code>APP_ALLOWED_HOSTS</code> rely on, does not check the the list of trusted hosts in it's routing system that <code>url_for</code> is relying on.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Invenio-App v1.0.6 and v1.1.1 fully fix the issue. </p>\n<p>Note, we strongly recommend (see <a href=\"https://invenio.readthedocs.io/en/latest/deployment/securing-your-instance.html#allowed-hosts\">Securing your instance</a>) that you never route requests to your application with a wrong host header.  The <code>APP_ALLOWED_HOSTS</code> configuration variable exists as an extra protective measure because it is easy to misconfigure your web server to allow requests with any host header. </p>\n<h3 id=\"workaround-1---configure-your-webserver\">Workaround 1 - Configure your webserver</h3>\n<p>You should ensure that you never route requests with a wrong host header to your application. The workaround depends on which web server you are using to proxy requests to your application. In general it involves ensuring that the web server has two virtual hosts defined:</p>\n<ol>\n<li><strong>Default virtual host</strong>: a dummy default virtual host that by default is used unless the webserver can match the host header to another virtual host (i.e. a catch-all).</li>\n<li><strong>Application virtual host</strong>: the application virtual host responsible for proxing requests to the application, and configured to only reply to a whitelist of host headers.</li>\n</ol>\n<p>Note, for instance in Nginx if you only configure the application virtual host, by default, it will also act as the default virtual host despite you having configured a whitelist of host headers.</p>\n<p>Below is an example for Nginx. Note for clarity we have only included the virtual host for port 443, but this also extends to virtual hosts running on any other port.</p>\n<pre><code># etc/nginx/nginx.conf\nhttp {\n  # ...\n  include /etc/nginx/conf.d/*.conf;\n}\n</code></pre>\n<p><strong>Default virtual host</strong></p>\n<p>Notice, the <code>server_name</code> is <code>_</code> and the <code>listen</code> directive has it marked as <code>default_server</code>.</p>\n<pre><code># etc/nginx/conf.d/default.conf\nserver {\n  listen 443 default_server;\n  listen [::]:443 default_server;\n  server_name _;\n\n  # ... \n\n  return 301 https://www.example.com;\n}\n</code></pre>\n<p><strong>Application virtual host</strong></p>\n<p>Notice, the <code>server_name</code> is set to the host header whitelist.</p>\n<pre><code># etc/nginx/conf.d/app.conf\nserver {\n  listen 443;\n  listen [::]:443;\n  server_name www.example.com;\n\n  # ...\n}\n</code></pre>\n<h3 id=\"workaround-2---include-application-snippet\">Workaround 2 - Include application snippet</h3>\n<p>We strongly recommend that you use the method described in Workaround 1.</p>\n<p>If you are not able to upgrade to the patched versions of Invenio-App, you can include the following code snippet in your application to force evaluation of <code>request.hosts</code>.</p>\n<pre><code class=\"language-python\">@app.before_request\ndef before_request():\n    request.host\n</code></pre>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Email us at <a href=\"mailto:info@inveniosoftware.org\">info@inveniosoftware.org</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-app/security/advisories/GHSA-94mf-xfg5-r247\">https://github.com/inveniosoftware/invenio-app/security/advisories/GHSA-94mf-xfg5-r247</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-1020006\">https://nvd.nist.gov/vuln/detail/CVE-2019-1020006</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-94mf-xfg5-r247\">https://github.com/advisories/GHSA-94mf-xfg5-r247</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app/PYSEC-2019-24.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app/PYSEC-2019-24.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-94mf-xfg5-r247",
            "title": "[invenio-app] Invenio-App vulnerable to host header injection attack",
            "date_modified": "2024-09-23T16:00:54.000Z",
            "date_published": "2019-07-16T00:52:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-94mf-xfg5-r247"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h2 id=\"app_allowed_hosts-not-always-preventing-host-header-injection\">APP_ALLOWED_HOSTS not always preventing host header injection</h2>\n<h3 id=\"impact\">Impact</h3>\n<p>A possible host header injection attack have been identified in Invenio-App.  For an attack to be possible, all conditions below must be met:</p>\n<ol>\n<li>Your webserver must have been configured to route all requests to your application. </li>\n<li>You must have relied on <code>APP_ALLOWED_HOSTS</code> configuration variable to whitelist allowed host headers.</li>\n<li>Flask's <code>request.host</code> must not have been evaluated during request handling.</li>\n</ol>\n<p>An example of a view which does not evalute <code>request.host</code> is a simple view using just <code>url_for</code> to generate an external URL (similar is possible when rendering just a Jinja template):</p>\n<pre><code class=\"language-python\">@app.route('/')\ndef index():\n    return url_for('index_url', _external=True)\n</code></pre>\n<p>This happens, because Werkzeug's trusted host feature, which <code>APP_ALLOWED_HOSTS</code> rely on, does not check the the list of trusted hosts in it's routing system that <code>url_for</code> is relying on.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Invenio-App v1.0.6 and v1.1.1 fully fix the issue. </p>\n<p>Note, we strongly recommend (see <a href=\"https://invenio.readthedocs.io/en/latest/deployment/securing-your-instance.html#allowed-hosts\">Securing your instance</a>) that you never route requests to your application with a wrong host header.  The <code>APP_ALLOWED_HOSTS</code> configuration variable exists as an extra protective measure because it is easy to misconfigure your web server to allow requests with any host header. </p>\n<h3 id=\"workaround-1---configure-your-webserver\">Workaround 1 - Configure your webserver</h3>\n<p>You should ensure that you never route requests with a wrong host header to your application. The workaround depends on which web server you are using to proxy requests to your application. In general it involves ensuring that the web server has two virtual hosts defined:</p>\n<ol>\n<li><strong>Default virtual host</strong>: a dummy default virtual host that by default is used unless the webserver can match the host header to another virtual host (i.e. a catch-all).</li>\n<li><strong>Application virtual host</strong>: the application virtual host responsible for proxing requests to the application, and configured to only reply to a whitelist of host headers.</li>\n</ol>\n<p>Note, for instance in Nginx if you only configure the application virtual host, by default, it will also act as the default virtual host despite you having configured a whitelist of host headers.</p>\n<p>Below is an example for Nginx. Note for clarity we have only included the virtual host for port 443, but this also extends to virtual hosts running on any other port.</p>\n<pre><code># etc/nginx/nginx.conf\nhttp {\n  # ...\n  include /etc/nginx/conf.d/*.conf;\n}\n</code></pre>\n<p><strong>Default virtual host</strong></p>\n<p>Notice, the <code>server_name</code> is <code>_</code> and the <code>listen</code> directive has it marked as <code>default_server</code>.</p>\n<pre><code># etc/nginx/conf.d/default.conf\nserver {\n  listen 443 default_server;\n  listen [::]:443 default_server;\n  server_name _;\n\n  # ... \n\n  return 301 https://www.example.com;\n}\n</code></pre>\n<p><strong>Application virtual host</strong></p>\n<p>Notice, the <code>server_name</code> is set to the host header whitelist.</p>\n<pre><code># etc/nginx/conf.d/app.conf\nserver {\n  listen 443;\n  listen [::]:443;\n  server_name www.example.com;\n\n  # ...\n}\n</code></pre>\n<h3 id=\"workaround-2---include-application-snippet\">Workaround 2 - Include application snippet</h3>\n<p>We strongly recommend that you use the method described in Workaround 1.</p>\n<p>If you are not able to upgrade to the patched versions of Invenio-App, you can include the following code snippet in your application to force evaluation of <code>request.hosts</code>.</p>\n<pre><code class=\"language-python\">@app.before_request\ndef before_request():\n    request.host\n</code></pre>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Email us at <a href=\"mailto:info@inveniosoftware.org\">info@inveniosoftware.org</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/inveniosoftware/invenio-app/security/advisories/GHSA-94mf-xfg5-r247\">https://github.com/inveniosoftware/invenio-app/security/advisories/GHSA-94mf-xfg5-r247</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-1020006\">https://nvd.nist.gov/vuln/detail/CVE-2019-1020006</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-94mf-xfg5-r247\">https://github.com/advisories/GHSA-94mf-xfg5-r247</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app/PYSEC-2019-24.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/invenio-app/PYSEC-2019-24.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-94mf-xfg5-r247",
            "title": "[invenio-app] Invenio-App vulnerable to host header injection attack",
            "date_modified": "2024-09-23T16:00:54.000Z",
            "date_published": "2019-07-16T00:52:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-94mf-xfg5-r247"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h1 id=\"summary\">Summary</h1>\n<p>Indy Node has a bug in TAA handling code. The current primary can be crashed with a malformed transaction from a client, which leads to a view change. Repeated rapid view changes have the potential of bringing down the network.</p>\n<h1 id=\"discovery\">Discovery</h1>\n<p>On May 18, Evernym's monitoring of Sovrin StagingNet showed a report of StagingNet losing sufficient consensus to validate write transactions. The problem resolved itself within a few minutes. On May 20th we saw the alert multiple times, and we began analyzing the logs of our steward node. On May 21st we continued to see the alerts with increasing frequency.</p>\n<p>It appears that someone is unknowingly sending a malformed transaction, and retrying when the transaction fails. The cause of the errors appear to be the TAA acceptance.</p>\n<h1 id=\"proposed-actions\">Proposed actions</h1>\n<ul>\n<li>Reproduce problem in integration tests and create a fix</li>\n<li>Do a hotfix release branching from last stable (current master have some things merged that are too risky)</li>\n<li>Upgrade BuilderNet, StagingNet and MainNet as soon as possible</li>\n<li>Improve testing strategy on Indy Node to reduce probability of such bugs</li>\n</ul>\n<h1 id=\"notes\">Notes</h1>\n<ul>\n<li>The journalctl logs also show an out-of-memory problem on the Australia node. We need to evaluate if this should be raised as a separate issue.</li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/hyperledger/indy-node/security/advisories/GHSA-3gw4-m5w7-v89c\">https://github.com/hyperledger/indy-node/security/advisories/GHSA-3gw4-m5w7-v89c</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-11090\">https://nvd.nist.gov/vuln/detail/CVE-2020-11090</a></li>\n<li><a href=\"https://github.com/hyperledger/indy-node/blob/master/CHANGELOG.md#1123\">https://github.com/hyperledger/indy-node/blob/master/CHANGELOG.md#1123</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/indy-node/PYSEC-2020-47.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/indy-node/PYSEC-2020-47.yaml</a></li>\n<li><a href=\"https://pypi.org/project/indy-node/1.12.3\">https://pypi.org/project/indy-node/1.12.3</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3gw4-m5w7-v89c\">https://github.com/advisories/GHSA-3gw4-m5w7-v89c</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3gw4-m5w7-v89c",
            "title": "[indy-node] Uncontrolled Resource Consumption in Indy Node",
            "date_modified": "2024-09-23T15:59:17.000Z",
            "date_published": "2020-06-11T00:04:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3gw4-m5w7-v89c"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}