{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>The vulnerability is we used MD5 hashing Algorithm In our hashing file. If anyone who is a beginner(and doesn't know about hashes)  can face problems as MD5 is considered a Insecure Hashing Algorithm. </p>\n<h3 id=\"patches\">Patches</h3>\n<p>The vulnerability is patched in v1.1.4 of the product, the users can upgrade to version 1.1.4.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>If u specifically want a version and don't want to upgrade, you can remove the <code>MD5</code> hashing function from the file <code>hashing.py</code> and this vulnerability will be gone</p>\n<h3 id=\"references\">References</h3>\n<p><a href=\"https://www.cybersecurity-help.cz/vdb/cwe/916/\">https://www.cybersecurity-help.cz/vdb/cwe/916/</a>\n<a href=\"https://www.cybersecurity-help.cz/vdb/cwe/327/\">https://www.cybersecurity-help.cz/vdb/cwe/327/</a>\n<a href=\"https://www.cybersecurity-help.cz/vdb/cwe/328/\">https://www.cybersecurity-help.cz/vdb/cwe/328/</a>\n<a href=\"https://www.section.io/engineering-education/what-is-md5/\">https://www.section.io/engineering-education/what-is-md5/</a>\n<a href=\"https://www.johndcook.com/blog/2019/01/24/reversing-an-md5-hash/\">https://www.johndcook.com/blog/2019/01/24/reversing-an-md5-hash/</a></p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in <a href=\"http://www.github.com/Morgan-Phoenix/EnroCrypt\"><strong>Enrocrypt's Official Repo</strong></a></li>\n<li>Create a Discussion in  <a href=\"http://www.github.com/Morgan-Phoenix/EnroCrypt\"><strong>Enrocrypt's Official Repo</strong></a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/Morgan-Phoenix/EnroCrypt/security/advisories/GHSA-35m5-8cvj-8783\">https://github.com/Morgan-Phoenix/EnroCrypt/security/advisories/GHSA-35m5-8cvj-8783</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-39182\">https://nvd.nist.gov/vuln/detail/CVE-2021-39182</a></li>\n<li><a href=\"https://github.com/Morgan-Phoenix/EnroCrypt/commit/e652d56ac60eadfc26489ab83927af13a9b9d8ce\">https://github.com/Morgan-Phoenix/EnroCrypt/commit/e652d56ac60eadfc26489ab83927af13a9b9d8ce</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/enrocrypt/PYSEC-2021-385.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/enrocrypt/PYSEC-2021-385.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-35m5-8cvj-8783\">https://github.com/advisories/GHSA-35m5-8cvj-8783</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-35m5-8cvj-8783",
            "title": "[enrocrypt] Improper hashing in enrocrypt",
            "date_modified": "2024-09-20T16:50:34.000Z",
            "date_published": "2021-11-10T16:28:46.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-35m5-8cvj-8783"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>User enumeration in database authentication in Flask-AppBuilder  &lt; 3.4.4. Allows for a non authenticated user to enumerate existing accounts by timing the response time from the server when you are logging in.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Upgrade to 3.4.4</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<h3 id=\"references\">References</h3>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in <a href=\"http://example.com\">example link to repo</a></li>\n<li>Email us at <a href=\"mailto:example@example.com\">example email address</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-wfjw-w6pv-8p7f\">https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-wfjw-w6pv-8p7f</a></li>\n<li><a href=\"https://github.com/dpgaspar/Flask-AppBuilder/pull/1775\">https://github.com/dpgaspar/Flask-AppBuilder/pull/1775</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-21659\">https://nvd.nist.gov/vuln/detail/CVE-2022-21659</a></li>\n<li><a href=\"https://github.com/dpgaspar/Flask-AppBuilder/commit/e2b744c258ff62ece9d5ac7172c3b4644ff4c2fe\">https://github.com/dpgaspar/Flask-AppBuilder/commit/e2b744c258ff62ece9d5ac7172c3b4644ff4c2fe</a></li>\n<li><a href=\"https://github.com/dpgaspar/Flask-AppBuilder/commits/v3.4.4\">https://github.com/dpgaspar/Flask-AppBuilder/commits/v3.4.4</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/flask-appbuilder/PYSEC-2022-24.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/flask-appbuilder/PYSEC-2022-24.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wfjw-w6pv-8p7f\">https://github.com/advisories/GHSA-wfjw-w6pv-8p7f</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wfjw-w6pv-8p7f",
            "title": "[Flask-AppBuilder] Observable Response Discrepancy in Flask-AppBuilder",
            "date_modified": "2024-09-20T16:49:34.000Z",
            "date_published": "2022-02-01T00:47:53.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wfjw-w6pv-8p7f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h2 id=\"duplicate-advisory\">Duplicate Advisory</h2>\n<p>This advisory has been withdrawn because it is a duplicate of GHSA-pwfw-mgfj-7g3g. This link is maintained to preserve external references.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14853\">https://nvd.nist.gov/vuln/detail/CVE-2019-14853</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853</a></li>\n<li><a href=\"https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3\">https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Dec/33\">https://seclists.org/bugtraq/2019/Dec/33</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4588\">https://www.debian.org/security/2019/dsa-4588</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2mrj-435v-c2cr\">https://github.com/advisories/GHSA-2mrj-435v-c2cr</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pwfw-mgfj-7g3g\">https://github.com/advisories/GHSA-pwfw-mgfj-7g3g</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ecdsa/PYSEC-2019-177.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ecdsa/PYSEC-2019-177.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2mrj-435v-c2cr",
            "title": "[ecdsa] Duplicate Advisory: possible DoS caused by malformed signature decoding in Pure-Python ECDSA",
            "date_modified": "2024-09-20T16:46:34.000Z",
            "date_published": "2019-12-02T18:15:31.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2mrj-435v-c2cr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Donfig 0.3.0. There is a vulnerability in the <code>collect_yaml</code> method in <code>config_obj.py</code>. It can execute arbitrary Python commands, resulting in command execution.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-7537\">https://nvd.nist.gov/vuln/detail/CVE-2019-7537</a></li>\n<li><a href=\"https://github.com/pytroll/donfig/issues/5\">https://github.com/pytroll/donfig/issues/5</a></li>\n<li><a href=\"https://github.com/pytroll/donfig/commit/1f9dbf83b17419a06d63c14ef3fbd29dbc1b8ce5\">https://github.com/pytroll/donfig/commit/1f9dbf83b17419a06d63c14ef3fbd29dbc1b8ce5</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/donfig/PYSEC-2019-21.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/donfig/PYSEC-2019-21.yaml</a></li>\n<li><a href=\"https://github.com/pytroll/donfig/commits/master\">https://github.com/pytroll/donfig/commits/master</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3qr5-h7w4-3gx3\">https://github.com/advisories/GHSA-3qr5-h7w4-3gx3</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3qr5-h7w4-3gx3",
            "title": "[donfig] Donfig Command Injection in collect_yaml method",
            "date_modified": "2024-09-20T16:27:57.000Z",
            "date_published": "2022-05-14T01:15:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3qr5-h7w4-3gx3"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14233\">https://nvd.nist.gov/vuln/detail/CVE-2019-14233</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h5jv-4p7w-64jg\">https://github.com/advisories/GHSA-h5jv-4p7w-64jg</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-12.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-12.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h5jv-4p7w-64jg",
            "title": "[Django] Django Denial-of-service in strip_tags()",
            "date_modified": "2024-09-20T16:25:07.000Z",
            "date_published": "2019-08-06T01:43:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h5jv-4p7w-64jg"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14233\">https://nvd.nist.gov/vuln/detail/CVE-2019-14233</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h5jv-4p7w-64jg\">https://github.com/advisories/GHSA-h5jv-4p7w-64jg</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-12.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-12.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h5jv-4p7w-64jg",
            "title": "[Django] Django Denial-of-service in strip_tags()",
            "date_modified": "2024-09-20T16:25:07.000Z",
            "date_published": "2019-08-06T01:43:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h5jv-4p7w-64jg"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14233\">https://nvd.nist.gov/vuln/detail/CVE-2019-14233</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h5jv-4p7w-64jg\">https://github.com/advisories/GHSA-h5jv-4p7w-64jg</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-12.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-12.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h5jv-4p7w-64jg",
            "title": "[Django] Django Denial-of-service in strip_tags()",
            "date_modified": "2024-09-20T16:25:07.000Z",
            "date_published": "2019-08-06T01:43:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h5jv-4p7w-64jg"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If <code>django.utils.text.Truncator</code>'s <code>chars()</code> and <code>words()</code> methods were passed the <code>html=True</code> argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The <code>chars()</code> and <code>words()</code> methods are used to implement the <code>truncatechars_htm</code>l and <code>truncatewords_html</code> template filters, which were thus vulnerable.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14232\">https://nvd.nist.gov/vuln/detail/CVE-2019-14232</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://github.com/pypa/advisory-db/tree/main/vulns/django/PYSEC-2019-11.yaml\">https://github.com/pypa/advisory-db/tree/main/vulns/django/PYSEC-2019-11.yaml</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2023/10/04/6\">https://www.openwall.com/lists/oss-security/2023/10/04/6</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2023/10/04/6\">http://www.openwall.com/lists/oss-security/2023/10/04/6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/3LGJSPCN3VEG2UJPYCUB6TU75JTIV2TQ\">https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/3LGJSPCN3VEG2UJPYCUB6TU75JTIV2TQ</a></li>\n<li><a href=\"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW\">https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2024/03/04/1\">http://www.openwall.com/lists/oss-security/2024/03/04/1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-11.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-11.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-c4qh-4vgv-qc6g\">https://github.com/advisories/GHSA-c4qh-4vgv-qc6g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-c4qh-4vgv-qc6g",
            "title": "[Django] Django Denial-of-service in django.utils.text.Truncator",
            "date_modified": "2024-09-20T16:15:23.000Z",
            "date_published": "2019-08-06T01:43:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-c4qh-4vgv-qc6g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If <code>django.utils.text.Truncator</code>'s <code>chars()</code> and <code>words()</code> methods were passed the <code>html=True</code> argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The <code>chars()</code> and <code>words()</code> methods are used to implement the <code>truncatechars_htm</code>l and <code>truncatewords_html</code> template filters, which were thus vulnerable.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14232\">https://nvd.nist.gov/vuln/detail/CVE-2019-14232</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://github.com/pypa/advisory-db/tree/main/vulns/django/PYSEC-2019-11.yaml\">https://github.com/pypa/advisory-db/tree/main/vulns/django/PYSEC-2019-11.yaml</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2023/10/04/6\">https://www.openwall.com/lists/oss-security/2023/10/04/6</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2023/10/04/6\">http://www.openwall.com/lists/oss-security/2023/10/04/6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/3LGJSPCN3VEG2UJPYCUB6TU75JTIV2TQ\">https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/3LGJSPCN3VEG2UJPYCUB6TU75JTIV2TQ</a></li>\n<li><a href=\"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW\">https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2024/03/04/1\">http://www.openwall.com/lists/oss-security/2024/03/04/1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-11.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-11.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-c4qh-4vgv-qc6g\">https://github.com/advisories/GHSA-c4qh-4vgv-qc6g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-c4qh-4vgv-qc6g",
            "title": "[Django] Django Denial-of-service in django.utils.text.Truncator",
            "date_modified": "2024-09-20T16:15:23.000Z",
            "date_published": "2019-08-06T01:43:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-c4qh-4vgv-qc6g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If <code>django.utils.text.Truncator</code>'s <code>chars()</code> and <code>words()</code> methods were passed the <code>html=True</code> argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The <code>chars()</code> and <code>words()</code> methods are used to implement the <code>truncatechars_htm</code>l and <code>truncatewords_html</code> template filters, which were thus vulnerable.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14232\">https://nvd.nist.gov/vuln/detail/CVE-2019-14232</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://github.com/pypa/advisory-db/tree/main/vulns/django/PYSEC-2019-11.yaml\">https://github.com/pypa/advisory-db/tree/main/vulns/django/PYSEC-2019-11.yaml</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2023/10/04/6\">https://www.openwall.com/lists/oss-security/2023/10/04/6</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2023/10/04/6\">http://www.openwall.com/lists/oss-security/2023/10/04/6</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/3LGJSPCN3VEG2UJPYCUB6TU75JTIV2TQ\">https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/3LGJSPCN3VEG2UJPYCUB6TU75JTIV2TQ</a></li>\n<li><a href=\"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW\">https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2024/03/04/1\">http://www.openwall.com/lists/oss-security/2024/03/04/1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-11.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-11.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-c4qh-4vgv-qc6g\">https://github.com/advisories/GHSA-c4qh-4vgv-qc6g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-c4qh-4vgv-qc6g",
            "title": "[Django] Django Denial-of-service in django.utils.text.Truncator",
            "date_modified": "2024-09-20T16:15:23.000Z",
            "date_published": "2019-08-06T01:43:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-c4qh-4vgv-qc6g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14235\">https://nvd.nist.gov/vuln/detail/CVE-2019-14235</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v9qg-3j8p-r63v\">https://github.com/advisories/GHSA-v9qg-3j8p-r63v</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-14.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-14.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v9qg-3j8p-r63v",
            "title": "[Django] Uncontrolled Recursion in Django",
            "date_modified": "2024-09-20T16:09:22.000Z",
            "date_published": "2019-08-06T01:43:31.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v9qg-3j8p-r63v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14235\">https://nvd.nist.gov/vuln/detail/CVE-2019-14235</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v9qg-3j8p-r63v\">https://github.com/advisories/GHSA-v9qg-3j8p-r63v</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-14.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-14.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v9qg-3j8p-r63v",
            "title": "[Django] Uncontrolled Recursion in Django",
            "date_modified": "2024-09-20T16:09:22.000Z",
            "date_published": "2019-08-06T01:43:31.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v9qg-3j8p-r63v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14235\">https://nvd.nist.gov/vuln/detail/CVE-2019-14235</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v9qg-3j8p-r63v\">https://github.com/advisories/GHSA-v9qg-3j8p-r63v</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-14.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-14.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v9qg-3j8p-r63v",
            "title": "[Django] Uncontrolled Recursion in Django",
            "date_modified": "2024-09-20T16:09:22.000Z",
            "date_published": "2019-08-06T01:43:31.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v9qg-3j8p-r63v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14234\">https://nvd.nist.gov/vuln/detail/CVE-2019-14234</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://github.com/django/django/commit/4f5b58f5cd3c57fee9972ab074f8dc6895d8f387\">https://github.com/django/django/commit/4f5b58f5cd3c57fee9972ab074f8dc6895d8f387</a></li>\n<li><a href=\"https://github.com/django/django/commit/ed682a24fca774818542757651bfba576c3fc3ef\">https://github.com/django/django/commit/ed682a24fca774818542757651bfba576c3fc3ef</a></li>\n<li><a href=\"https://github.com/django/django/commit/f74b3ae3628c26e1b4f8db3d13a91d52a833a975\">https://github.com/django/django/commit/f74b3ae3628c26e1b4f8db3d13a91d52a833a975</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6r97-cj55-9hrq\">https://github.com/advisories/GHSA-6r97-cj55-9hrq</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-13.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-13.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6r97-cj55-9hrq",
            "title": "[Django] SQL Injection in Django",
            "date_modified": "2024-09-20T16:08:24.000Z",
            "date_published": "2019-08-16T14:00:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6r97-cj55-9hrq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14234\">https://nvd.nist.gov/vuln/detail/CVE-2019-14234</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://github.com/django/django/commit/4f5b58f5cd3c57fee9972ab074f8dc6895d8f387\">https://github.com/django/django/commit/4f5b58f5cd3c57fee9972ab074f8dc6895d8f387</a></li>\n<li><a href=\"https://github.com/django/django/commit/ed682a24fca774818542757651bfba576c3fc3ef\">https://github.com/django/django/commit/ed682a24fca774818542757651bfba576c3fc3ef</a></li>\n<li><a href=\"https://github.com/django/django/commit/f74b3ae3628c26e1b4f8db3d13a91d52a833a975\">https://github.com/django/django/commit/f74b3ae3628c26e1b4f8db3d13a91d52a833a975</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6r97-cj55-9hrq\">https://github.com/advisories/GHSA-6r97-cj55-9hrq</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-13.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-13.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6r97-cj55-9hrq",
            "title": "[Django] SQL Injection in Django",
            "date_modified": "2024-09-20T16:08:24.000Z",
            "date_published": "2019-08-16T14:00:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6r97-cj55-9hrq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14234\">https://nvd.nist.gov/vuln/detail/CVE-2019-14234</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs\">https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs</a></li>\n<li><a href=\"https://github.com/django/django/commit/4f5b58f5cd3c57fee9972ab074f8dc6895d8f387\">https://github.com/django/django/commit/4f5b58f5cd3c57fee9972ab074f8dc6895d8f387</a></li>\n<li><a href=\"https://github.com/django/django/commit/ed682a24fca774818542757651bfba576c3fc3ef\">https://github.com/django/django/commit/ed682a24fca774818542757651bfba576c3fc3ef</a></li>\n<li><a href=\"https://github.com/django/django/commit/f74b3ae3628c26e1b4f8db3d13a91d52a833a975\">https://github.com/django/django/commit/f74b3ae3628c26e1b4f8db3d13a91d52a833a975</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6r97-cj55-9hrq\">https://github.com/advisories/GHSA-6r97-cj55-9hrq</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-13.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-13.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Aug/15\">https://seclists.org/bugtraq/2019/Aug/15</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202004-17\">https://security.gentoo.org/glsa/202004-17</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190828-0002\">https://security.netapp.com/advisory/ntap-20190828-0002</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4498\">https://www.debian.org/security/2019/dsa-4498</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/aug/01/security-releases\">https://www.djangoproject.com/weblog/2019/aug/01/security-releases</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6r97-cj55-9hrq",
            "title": "[Django] SQL Injection in Django",
            "date_modified": "2024-09-20T16:08:24.000Z",
            "date_published": "2019-08-16T14:00:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6r97-cj55-9hrq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-46695\">https://nvd.nist.gov/vuln/detail/CVE-2023-46695</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f\">https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f</a></li>\n<li><a href=\"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e\">https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e</a></li>\n<li><a href=\"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b\">https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20231214-0001\">https://security.netapp.com/advisory/ntap-20231214-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/nov/01/security-releases\">https://www.djangoproject.com/weblog/2023/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq\">https://github.com/advisories/GHSA-qmf9-6jqf-j8fq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq",
            "title": "[Django] Django potential denial of service vulnerability in UsernameField on Windows",
            "date_modified": "2024-09-20T16:05:10.000Z",
            "date_published": "2023-11-02T06:30:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-46695\">https://nvd.nist.gov/vuln/detail/CVE-2023-46695</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f\">https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f</a></li>\n<li><a href=\"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e\">https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e</a></li>\n<li><a href=\"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b\">https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20231214-0001\">https://security.netapp.com/advisory/ntap-20231214-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/nov/01/security-releases\">https://www.djangoproject.com/weblog/2023/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq\">https://github.com/advisories/GHSA-qmf9-6jqf-j8fq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq",
            "title": "[Django] Django potential denial of service vulnerability in UsernameField on Windows",
            "date_modified": "2024-09-20T16:05:10.000Z",
            "date_published": "2023-11-02T06:30:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-46695\">https://nvd.nist.gov/vuln/detail/CVE-2023-46695</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f\">https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f</a></li>\n<li><a href=\"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e\">https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e</a></li>\n<li><a href=\"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b\">https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml</a></li>\n<li><a href=\"https://groups.google.com/forum/#%21forum/django-announce\">https://groups.google.com/forum/#%21forum/django-announce</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.2/releases/security\">https://docs.djangoproject.com/en/4.2/releases/security</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20231214-0001\">https://security.netapp.com/advisory/ntap-20231214-0001</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2023/nov/01/security-releases\">https://www.djangoproject.com/weblog/2023/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq\">https://github.com/advisories/GHSA-qmf9-6jqf-j8fq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq",
            "title": "[Django] Django potential denial of service vulnerability in UsernameField on Windows",
            "date_modified": "2024-09-20T16:05:10.000Z",
            "date_published": "2023-11-02T06:30:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. <code>UserAttributeSimilarityValidator</code> incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45115\">https://nvd.nist.gov/vuln/detail/CVE-2021-45115</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://github.com/django/django/commit/2135637fdd5ce994de110affef9e67dffdf77277\">https://github.com/django/django/commit/2135637fdd5ce994de110affef9e67dffdf77277</a></li>\n<li><a href=\"https://github.com/django/django/commit/a8b32fe13bcaed1c0b772fdc53de84abc224fb20\">https://github.com/django/django/commit/a8b32fe13bcaed1c0b772fdc53de84abc224fb20</a></li>\n<li><a href=\"https://github.com/django/django/commit/df79ef03ac867c93caaa6be56bc69e66abfeef8f\">https://github.com/django/django/commit/df79ef03ac867c93caaa6be56bc69e66abfeef8f</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security\">https://docs.djangoproject.com/en/4.0/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220121-0005\">https://security.netapp.com/advisory/ntap-20220121-0005</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases\">https://www.djangoproject.com/weblog/2022/jan/04/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-53qw-q765-4fww\">https://github.com/advisories/GHSA-53qw-q765-4fww</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-1.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-53qw-q765-4fww",
            "title": "[Django] Denial-of-service in Django",
            "date_modified": "2024-09-20T16:04:23.000Z",
            "date_published": "2022-01-12T19:20:53.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-53qw-q765-4fww"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}