{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>In modoboa prior to 2.1.0, sending a GET request to the endpoint <code>/api/v2/parameters/core/</code> returns sensitive information without any authentication or authorization.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-2227\">https://nvd.nist.gov/vuln/detail/CVE-2023-2227</a></li>\n<li><a href=\"https://github.com/modoboa/modoboa/commit/7bcd3f6eb264d4e3e01071c97c2bac51cdd6fe97\">https://github.com/modoboa/modoboa/commit/7bcd3f6eb264d4e3e01071c97c2bac51cdd6fe97</a></li>\n<li><a href=\"https://huntr.dev/bounties/351f9055-2008-4af0-b820-01ff66678bf3\">https://huntr.dev/bounties/351f9055-2008-4af0-b820-01ff66678bf3</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/modoboa/PYSEC-2023-35.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/modoboa/PYSEC-2023-35.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-67mg-gm8m-ph5r\">https://github.com/advisories/GHSA-67mg-gm8m-ph5r</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-67mg-gm8m-ph5r",
            "title": "[modoboa] Improper Authorization in modoboa",
            "date_modified": "2024-09-24T21:26:21.000Z",
            "date_published": "2023-04-21T15:30:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-67mg-gm8m-ph5r"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Authentication Bypass by Primary Weakness in GitHub repository modoboa/modoboa prior to 2.0.4.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-0777\">https://nvd.nist.gov/vuln/detail/CVE-2023-0777</a></li>\n<li><a href=\"https://github.com/modoboa/modoboa/commit/47d17ac6643f870719691073956a26e4be0a4806\">https://github.com/modoboa/modoboa/commit/47d17ac6643f870719691073956a26e4be0a4806</a></li>\n<li><a href=\"https://huntr.dev/bounties/a17e7a9f-0fee-4130-a522-5a0466fc17c7\">https://huntr.dev/bounties/a17e7a9f-0fee-4130-a522-5a0466fc17c7</a></li>\n<li><a href=\"http://packetstormsecurity.com/files/171744/modoboa-2.0.4-Admin-Takeover.html\">http://packetstormsecurity.com/files/171744/modoboa-2.0.4-Admin-Takeover.html</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/modoboa/PYSEC-2023-32.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/modoboa/PYSEC-2023-32.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rfhw-fm4m-52j6\">https://github.com/advisories/GHSA-rfhw-fm4m-52j6</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rfhw-fm4m-52j6",
            "title": "[modoboa] Authentication Bypass in modoboa",
            "date_modified": "2024-09-24T21:22:34.000Z",
            "date_published": "2023-02-10T21:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rfhw-fm4m-52j6"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>mlflow prior to 2.3.0 is vulnerable to path traversal due to a bypass of the fix for CVE-2023-1177.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-2780\">https://nvd.nist.gov/vuln/detail/CVE-2023-2780</a></li>\n<li><a href=\"https://github.com/mlflow/mlflow/commit/fae77a525dd908c56d6204a4cef1c1c75b4e9857\">https://github.com/mlflow/mlflow/commit/fae77a525dd908c56d6204a4cef1c1c75b4e9857</a></li>\n<li><a href=\"https://huntr.dev/bounties/b12b0073-0bb0-4bd1-8fc2-ec7f17fd7689\">https://huntr.dev/bounties/b12b0073-0bb0-4bd1-8fc2-ec7f17fd7689</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/mlflow/PYSEC-2023-69.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/mlflow/PYSEC-2023-69.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wjq3-7jxx-whj9\">https://github.com/advisories/GHSA-wjq3-7jxx-whj9</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wjq3-7jxx-whj9",
            "title": "[mlflow] mlflow Path Traversal vulnerability",
            "date_modified": "2024-09-24T21:12:16.000Z",
            "date_published": "2023-05-17T21:30:22.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wjq3-7jxx-whj9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>IRRd did not always filter password hashes in query responses relating to <code>mntner</code> objects and database exports. This may have allowed adversaries to retrieve some of these hashes, perform a brute-force search for the clear-text passphrase, and use these to make unauthorised changes to affected IRR objects. This issue only affected instances that process password hashes, which means it is limited to IRRd instances that serve authoritative databases. IRRd instances operating solely as mirrors of other IRR databases are not affected.</p>\n<p>The issue occurred:</p>\n<ul>\n<li>For <code>mntner</code> objects where all password hash names (<code>MD5-PW</code> and <code>CRYPT-PW</code>) were in lower or mixed case in the <code>auth</code> attribute. For these objects, hashes remained in the output of all queries of any method and all database exports made with the <code>export_destination</code> setting. Fortunately, objects in the common public IRR database virtually all use uppercase hash names which means very few of those objects were affected.</li>\n<li>For any GraphQL queries that queried the <code>auth</code> field on <code>mntner</code> objects.</li>\n<li>For any GraphQL queries that queried the <code>objectText</code> field on the <code>journal</code> field on <code>mntner</code> objects, if the <code>nrtm_access_list</code> setting permitted journal access.</li>\n</ul>\n<p>The two GraphQL cases are visible in logs, allowing users to determine whether any existing objects had their hashes exposed.\nThis has been fixed in IRRd 4.2.3 and the main branch. Versions in the 4.1.x series never were affected. Users of the 4.2.x series are strongly recommended to upgrade. All users running a more recent version from the main branch should update to the latest version. Alternatively, but not recommended, apply the patch manually [for 4.2.x]</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/irrdnet/irrd/security/advisories/GHSA-cqxx-66wh-8pjw\">https://github.com/irrdnet/irrd/security/advisories/GHSA-cqxx-66wh-8pjw</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-24798\">https://nvd.nist.gov/vuln/detail/CVE-2022-24798</a></li>\n<li><a href=\"https://github.com/irrdnet/irrd/commit/0e41bae8d3d27316381a2fc7b466597230e35ec6\">https://github.com/irrdnet/irrd/commit/0e41bae8d3d27316381a2fc7b466597230e35ec6</a></li>\n<li><a href=\"https://github.com/irrdnet/irrd/commit/fdffaf8dd71713f06e99dff417e6aa1e6fa84b70\">https://github.com/irrdnet/irrd/commit/fdffaf8dd71713f06e99dff417e6aa1e6fa84b70</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/irrd/PYSEC-2022-178.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/irrd/PYSEC-2022-178.yaml</a></li>\n<li><a href=\"https://irrd.readthedocs.io/en/stable/releases/4.2.3\">https://irrd.readthedocs.io/en/stable/releases/4.2.3</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cqxx-66wh-8pjw\">https://github.com/advisories/GHSA-cqxx-66wh-8pjw</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cqxx-66wh-8pjw",
            "title": "[irrd] Improper Removal of Sensitive Information Before Storage or Transfer in irrd",
            "date_modified": "2024-09-24T21:11:10.000Z",
            "date_published": "2022-04-01T13:59:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cqxx-66wh-8pjw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in openstack-mistral. By manipulating the SSH private key filename, the std.ssh action can be used to disclose the presence of arbitrary files within the filesystem of the executor running the action. Since std.ssh private_key_filename can take an absolute path, it can be used to assess whether or not a file exists on the executor's filesystem.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-16849\">https://nvd.nist.gov/vuln/detail/CVE-2018-16849</a></li>\n<li><a href=\"https://bugs.launchpad.net/mistral/+bug/1783708\">https://bugs.launchpad.net/mistral/+bug/1783708</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16849\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16849</a></li>\n<li><a href=\"https://github.com/openstack/mistral/commit/c93b45a61f49d4633f76d8e117cd89063e7759c4\">https://github.com/openstack/mistral/commit/c93b45a61f49d4633f76d8e117cd89063e7759c4</a></li>\n<li><a href=\"https://github.com/openstack/mistral/commit/2309e5265a1d5f28480ae872817b5de05f66e83c\">https://github.com/openstack/mistral/commit/2309e5265a1d5f28480ae872817b5de05f66e83c</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/mistral/PYSEC-2018-92.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/mistral/PYSEC-2018-92.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fqw7-c6vr-q29m\">https://github.com/advisories/GHSA-fqw7-c6vr-q29m</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fqw7-c6vr-q29m",
            "title": "[mistral] openstack-mistral Discloses the presence of arbitrary files within the filesystem",
            "date_modified": "2024-09-24T21:06:46.000Z",
            "date_published": "2022-05-13T01:34:06.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fqw7-c6vr-q29m"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>JSNAPy is an open source python version of Junos Snapshot Administrator developed by Juniper available through github. The default configuration and sample files of JSNAPy automation tool versions prior to 1.3.0 are created world writable. This insecure file and directory permission allows unprivileged local users to alter the files under this directory including inserting operations not intended by the package maintainer, system administrator, or other users. This issue only affects users who downloaded and installed JSNAPy from github.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-0023\">https://nvd.nist.gov/vuln/detail/CVE-2018-0023</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qc55-vm3j-74gp\">https://github.com/advisories/GHSA-qc55-vm3j-74gp</a></li>\n<li><a href=\"https://kb.juniper.net/JSA10856\">https://kb.juniper.net/JSA10856</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/jsnapy/PYSEC-2018-84.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/jsnapy/PYSEC-2018-84.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20200227125151/http://www.securityfocus.com/bid/103745\">https://web.archive.org/web/20200227125151/http://www.securityfocus.com/bid/103745</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qc55-vm3j-74gp",
            "title": "[jsnapy] JSNAPy allows unprivileged local users to alter files under the directory",
            "date_modified": "2024-09-24T21:02:13.000Z",
            "date_published": "2018-07-12T20:30:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qc55-vm3j-74gp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>JupyterHub 1.1.0 allows CSRF in the admin panel via a request that lacks an <code>_xsrf</code> field, as demonstrated by a /hub/api/user request (to add or remove a user account).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-36191\">https://nvd.nist.gov/vuln/detail/CVE-2020-36191</a></li>\n<li><a href=\"https://github.com/jupyterhub/jupyterhub/issues/3304\">https://github.com/jupyterhub/jupyterhub/issues/3304</a></li>\n<li><a href=\"https://github.com/jupyterhub/jupyterhub/releases\">https://github.com/jupyterhub/jupyterhub/releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-7xx3-qp5w-fw96\">https://github.com/advisories/GHSA-7xx3-qp5w-fw96</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/jupyterhub/PYSEC-2021-67.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/jupyterhub/PYSEC-2021-67.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-7xx3-qp5w-fw96",
            "title": "[jupyterhub] Cross-Site Request Forgery in JupyterHub",
            "date_modified": "2024-09-24T21:00:22.000Z",
            "date_published": "2022-05-24T17:38:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-7xx3-qp5w-fw96"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><em>What kind of vulnerability is it? Who is impacted?</em></p>\n<p>Open redirect vulnerability - a maliciously crafted link to a jupyter server could redirect the browser to a different website.</p>\n<p>All jupyter servers running without a base_url prefix are technically affected, however, these maliciously crafted links can only be reasonably made for known jupyter server hosts. A link to your jupyter server may <em>appear</em> safe, but ultimately redirect to a spoofed server on the public internet. This same vulnerability was patched in upstream notebook v5.7.8.</p>\n<h3 id=\"patches\">Patches</h3>\n<p><em>Has the problem been patched? What versions should users upgrade to?</em></p>\n<p>Patched in jupyter_server 1.1.1. If upgrade is not available, a workaround can be to run your server on a url prefix:</p>\n<pre><code>jupyter server --ServerApp.base_url=/jupyter/\n</code></pre>\n<h3 id=\"references\">References</h3>\n<p><a href=\"https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html\">OWASP page on open redirects</a></p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory, or vulnerabilities to report, please email our security list <a href=\"mailto:security@ipython.org\">security@ipython.org</a>.</p>\n<p>Credit: Yaniv Nizry from CxSCA group at Checkmarx</p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-9f66-54xg-pc2c\">https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-9f66-54xg-pc2c</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter_server/commit/85e4abccf6ea9321d29153f73b0bd72ccb3a6bca\">https://github.com/jupyter-server/jupyter_server/commit/85e4abccf6ea9321d29153f73b0bd72ccb3a6bca</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-26275\">https://nvd.nist.gov/vuln/detail/CVE-2020-26275</a></li>\n<li><a href=\"https://advisory.checkmarx.net/advisory/CX-2020-4291\">https://advisory.checkmarx.net/advisory/CX-2020-4291</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2020-50.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2020-50.yaml</a></li>\n<li><a href=\"https://pypi.org/project/jupyter-server\">https://pypi.org/project/jupyter-server</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-9f66-54xg-pc2c\">https://github.com/advisories/GHSA-9f66-54xg-pc2c</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-9f66-54xg-pc2c",
            "title": "[jupyter-server] Jupyter Server open redirect vulnerability",
            "date_modified": "2024-09-24T20:55:39.000Z",
            "date_published": "2020-12-21T18:01:41.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-9f66-54xg-pc2c"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>This vulnerability creates a false sense of security for keylime users -- i.e. a user could query keylime and conclude that a parcitular node/agent is correctly attested, while attestations are not in fact taking place.</p>\n<p><strong>Short explanation</strong>: the keylime verifier creates periodic reports on the state of each attested agent. The keylime verifier runs a set of python asynchronous processes to challenge attested nodes and create reports on the outcome. </p>\n<p>The vulnerability consists of the above named python asynchronous processes failing silently, i.e. quitting without leaving behind a database entry, raising an error or producing even a mention of an error in a log. The silent failure can be triggered by a small set of transient network failure conditions; recoverable device driver crashes being one such condition we saw in the wild.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem is fixed in keylime starting with tag 6.5.1</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>This <a href=\"https://github.com/keylime/keylime/pull/1128/files\">patch</a> can be retroactively applied to any running keylime deployment.\nOnly running verifiers need to be patched.\nAfter the patch is applied, the keylime verifier needs to be restarted.</p>\n<h3 id=\"references\">References</h3>\n<p>The problem, as well as the proposed fix, are described in detail <a href=\"https://github.com/keylime/keylime/pull/1128\">here</a>.\nFurther details about the system where the bug was found, and the conditions in which the bug was found, are available from @galmasi on demand.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this <a href=\"https://github.com/keylime/keylime/security/advisories/GHSA-hff2-x2j9-gxgv\">advisory</a>, please comment at the bottom of the advisory itself.</p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/keylime/keylime/security/advisories/GHSA-hff2-x2j9-gxgv\">https://github.com/keylime/keylime/security/advisories/GHSA-hff2-x2j9-gxgv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-3500\">https://nvd.nist.gov/vuln/detail/CVE-2022-3500</a></li>\n<li><a href=\"https://github.com/keylime/keylime/pull/1128\">https://github.com/keylime/keylime/pull/1128</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2022-3500\">https://access.redhat.com/security/cve/CVE-2022-3500</a></li>\n<li><a href=\"https://github.com/keylime/keylime/commit/f969d397f92962b553f8c5bcbbeeb3bbdeca9456\">https://github.com/keylime/keylime/commit/f969d397f92962b553f8c5bcbbeeb3bbdeca9456</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/keylime/PYSEC-2022-42995.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/keylime/PYSEC-2022-42995.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PUTHMDVFNGGVPCNPOGULMJAAFEP7MEXP\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PUTHMDVFNGGVPCNPOGULMJAAFEP7MEXP</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QX4XVCAUFGJ2I2NCTOKONTJGRJB2NBBT\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QX4XVCAUFGJ2I2NCTOKONTJGRJB2NBBT</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZQH5CJRX65QYMQN5WGUKKKE3IRJBWG5Z\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZQH5CJRX65QYMQN5WGUKKKE3IRJBWG5Z</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hff2-x2j9-gxgv\">https://github.com/advisories/GHSA-hff2-x2j9-gxgv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hff2-x2j9-gxgv",
            "title": "[Keylime] Keylime: unhandled exceptions could lead to invalid attestation states",
            "date_modified": "2024-09-24T20:54:22.000Z",
            "date_published": "2022-10-28T19:19:42.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hff2-x2j9-gxgv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Pallets Jinja before 2.8.1, str.format allows a sandbox escape.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-10745\">https://nvd.nist.gov/vuln/detail/CVE-2016-10745</a></li>\n<li><a href=\"https://github.com/pallets/jinja/commit/9b53045c34e61013dc8f09b7e52a555fa16bed16\">https://github.com/pallets/jinja/commit/9b53045c34e61013dc8f09b7e52a555fa16bed16</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:1022\">https://access.redhat.com/errata/RHSA-2019:1022</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:1237\">https://access.redhat.com/errata/RHSA-2019:1237</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:1260\">https://access.redhat.com/errata/RHSA-2019:1260</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:3964\">https://access.redhat.com/errata/RHSA-2019:3964</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:4062\">https://access.redhat.com/errata/RHSA-2019:4062</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hj2j-77xm-mc5v\">https://github.com/advisories/GHSA-hj2j-77xm-mc5v</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html\">http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html\">http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/jinja2/PYSEC-2019-220.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/jinja2/PYSEC-2019-220.yaml</a></li>\n<li><a href=\"https://palletsprojects.com/blog/jinja-281-released\">https://palletsprojects.com/blog/jinja-281-released</a></li>\n<li><a href=\"https://usn.ubuntu.com/4011-1\">https://usn.ubuntu.com/4011-1</a></li>\n<li><a href=\"https://usn.ubuntu.com/4011-2\">https://usn.ubuntu.com/4011-2</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hj2j-77xm-mc5v",
            "title": "[Jinja2] Jinja2 sandbox escape vulnerability",
            "date_modified": "2024-09-24T20:51:40.000Z",
            "date_published": "2019-04-10T14:30:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hj2j-77xm-mc5v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Users of JupyterLab with JupyterHub who have multiple JupyterLab tabs open in the same browser session, may see incomplete logout from the single-user server, as fresh credentials (for the single-user server only, not the Hub) reinstated after logout, if another active JupyterLab session is open while the logout takes place.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Upgrade to JupyterHub 1.5. For distributed deployments, it is jupyterhub in the <em>user</em> environment that needs patching. There are no patches necessary in the Hub environment.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>The only workaround is to make sure that only one JupyterLab tab is open when you log out.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/jupyterhub/jupyterhub/security/advisories/GHSA-cw7p-q79f-m2v7\">https://github.com/jupyterhub/jupyterhub/security/advisories/GHSA-cw7p-q79f-m2v7</a></li>\n<li><a href=\"https://github.com/jupyterhub/jupyterhub/commit/5ac9e7f73a6e1020ffddc40321fc53336829fe27\">https://github.com/jupyterhub/jupyterhub/commit/5ac9e7f73a6e1020ffddc40321fc53336829fe27</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-41247\">https://nvd.nist.gov/vuln/detail/CVE-2021-41247</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/jupyterhub/PYSEC-2021-386.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/jupyterhub/PYSEC-2021-386.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cw7p-q79f-m2v7\">https://github.com/advisories/GHSA-cw7p-q79f-m2v7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cw7p-q79f-m2v7",
            "title": "[jupyterhub] incomplete JupyterHub logout with simultaneous JupyterLab sessions",
            "date_modified": "2024-09-24T20:50:55.000Z",
            "date_published": "2021-11-08T18:02:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cw7p-q79f-m2v7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>RhodeCode before 2.2.7 and Kallithea 0.1 allows remote authenticated users to obtain API keys and other sensitive information via the get_repo API method.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-0260\">https://nvd.nist.gov/vuln/detail/CVE-2015-0260</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/100888\">https://exchange.xforce.ibmcloud.com/vulnerabilities/100888</a></li>\n<li><a href=\"https://kallithea-scm.org/security/cve-2015-0260.html\">https://kallithea-scm.org/security/cve-2015-0260.html</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2015/q1/505\">http://seclists.org/oss-sec/2015/q1/505</a></li>\n<li><a href=\"https://rhodecode.com/blog/rhodecode-enterprise-security-release\">https://rhodecode.com/blog/rhodecode-enterprise-security-release</a></li>\n<li><a href=\"https://web.archive.org/web/20150321135511/http://www.securityfocus.com/bid/72573\">https://web.archive.org/web/20150321135511/http://www.securityfocus.com/bid/72573</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/kallithea/PYSEC-2015-29.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/kallithea/PYSEC-2015-29.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/rhodecode/PYSEC-2015-32.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/rhodecode/PYSEC-2015-32.yaml</a></li>\n<li><a href=\"https://kallithea-scm.org/repos/kallithea/changeset/5923d74742879b812965568475e21c3496d722a9\">https://kallithea-scm.org/repos/kallithea/changeset/5923d74742879b812965568475e21c3496d722a9</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hhx9-4vw2-x54r\">https://github.com/advisories/GHSA-hhx9-4vw2-x54r</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hhx9-4vw2-x54r",
            "title": "[Kallithea] RhodeCode and Kallithea are vulnerable to sensitive information disclosure",
            "date_modified": "2024-09-24T20:47:22.000Z",
            "date_published": "2022-05-13T01:26:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hhx9-4vw2-x54r"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site Scripting (XSS) - Stored in GitHub repository modoboa/modoboa prior to 2.0.4.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-0519\">https://nvd.nist.gov/vuln/detail/CVE-2023-0519</a></li>\n<li><a href=\"https://github.com/modoboa/modoboa/commit/eef9ab72b5305578a3ad7a7463bd284aa645e98b\">https://github.com/modoboa/modoboa/commit/eef9ab72b5305578a3ad7a7463bd284aa645e98b</a></li>\n<li><a href=\"https://huntr.dev/bounties/891ad0cb-d12f-4c5e-aac8-d7326caf2129\">https://huntr.dev/bounties/891ad0cb-d12f-4c5e-aac8-d7326caf2129</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/modoboa/PYSEC-2023-31.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/modoboa/PYSEC-2023-31.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jm3m-wr3p-hjrq\">https://github.com/advisories/GHSA-jm3m-wr3p-hjrq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jm3m-wr3p-hjrq",
            "title": "[modoboa] Cross-site Scripting in modoboa",
            "date_modified": "2024-09-24T20:46:32.000Z",
            "date_published": "2023-01-27T00:30:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jm3m-wr3p-hjrq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>IPython provides an interactive Python shell and Jupyter kernel to use Python interactively. Versions prior to 8.10.0 are vulnerable to command injection in the <code>set_term_title</code> <a href=\"https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/utils/terminal.py#L103-L117\">function</a> under specific conditions. This has been patched in version 8.10.0.</p>\n<h3 id=\"impact\">Impact</h3>\n<p>Users are only vulnerable when calling this function in Windows in a Python environment where <a href=\"https://docs.python.org/3/library/ctypes.html\">ctypes</a> is not available. The dependency on ctypes in <code>IPython.utils._process_win32</code> prevents the vulnerable code from ever being reached (making it effectively dead code). However, as a library that could be used by another tool, <code>set_term_title</code> could introduce a vulnerability for dependencies. Currently <code>set_term_title</code> is only called with (semi-)trusted input that contain the current working directory of the current IPython session. If an attacker can control directory names, and manage to get a user to <code>cd</code> into this directory, then the attacker can execute arbitrary commands contained in the folder names.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/ipython/ipython/security/advisories/GHSA-29gw-9793-fvw7\">https://github.com/ipython/ipython/security/advisories/GHSA-29gw-9793-fvw7</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/385d69325319a5972ee9b5983638e3617f21cb1f\">https://github.com/ipython/ipython/commit/385d69325319a5972ee9b5983638e3617f21cb1f</a></li>\n<li><a href=\"https://github.com/ipython/ipython/commit/991849c247fc208628879e7ca2923b3c218a5a75\">https://github.com/ipython/ipython/commit/991849c247fc208628879e7ca2923b3c218a5a75</a></li>\n<li><a href=\"https://github.com/Carreau/ipython/blob/7557ade0ed927475d5ab5b573d0ea4febfb22683/docs/source/whatsnew/version8.rst#ipython-810\">https://github.com/Carreau/ipython/blob/7557ade0ed927475d5ab5b573d0ea4febfb22683/docs/source/whatsnew/version8.rst#ipython-810</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-24816\">https://nvd.nist.gov/vuln/detail/CVE-2023-24816</a></li>\n<li><a href=\"https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/utils/terminal.py#L103-L117\">https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/utils/terminal.py#L103-L117</a></li>\n<li><a href=\"https://github.com/ipython/ipython/blob/56e6925dfa50e2c7f4a6471547b8176275db7c25/IPython/utils/_process_win32.py#L20\">https://github.com/ipython/ipython/blob/56e6925dfa50e2c7f4a6471547b8176275db7c25/IPython/utils/_process_win32.py#L20</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2023-17.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2023-17.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-29gw-9793-fvw7\">https://github.com/advisories/GHSA-29gw-9793-fvw7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-29gw-9793-fvw7",
            "title": "[ipython] IPython vulnerable to command injection via set_term_title",
            "date_modified": "2024-09-24T20:44:44.000Z",
            "date_published": "2023-02-10T19:55:53.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-29gw-9793-fvw7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><em>What kind of vulnerability is it? Who is impacted?</em></p>\n<p>JupyterHub deployments using:</p>\n<ul>\n<li>KubeSpawner &lt;= 0.11.1 (e.g. zero-to-jupyterhub 0.9.0) and</li>\n<li>enabled named_servers (not default), and</li>\n<li>an Authenticator that allows:<ul>\n<li>usernames with hyphens or other characters that require escape (e.g. <code>user-hyphen</code> or <code>user@email</code>), and</li>\n<li>usernames which may match other usernames up to but not including the escaped character (e.g. <code>user</code> in the above cases)</li>\n</ul>\n</li>\n</ul>\n<p>In this circumstance, certain usernames will be able to craft particular server names which will grant them access to the default server of other users who have matching usernames.</p>\n<h3 id=\"patches\">Patches</h3>\n<p><em>Has the problem been patched? What versions should users upgrade to?</em></p>\n<p>Patch will be released in kubespawner 0.12 and zero-to-jupyterhub 0.9.1</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p><em>Is there a way for users to fix or remediate the vulnerability without upgrading?</em></p>\n<h4 id=\"kubespawner\">KubeSpawner</h4>\n<p>Specify configuration:</p>\n<p>for KubeSpawner</p>\n<pre><code class=\"language-python\">from traitlets import default\nfrom kubespawner import KubeSpawner\n\nclass PatchedKubeSpawner(KubeSpawner):\n    @default(\"pod_name_template\")\n    def _default_pod_name_template(self):\n        if self.name:\n            return \"jupyter-{username}-{servername}\"\n        else:\n            return \"jupyter-{username}\"\n\n    @default(\"pvc_name_template\")\n    def _default_pvc_name_template(self):\n        if self.name:\n            return \"claim-{username}-{servername}\"\n        else:\n            return \"claim-{username}\"\n\nc.JupyterHub.spawner_class = PatchedKubeSpawner\n</code></pre>\n<p><strong>Note for KubeSpawner:</strong> this configuration will behave differently before and after the upgrade, so will need to be removed when upgrading. Only apply this configuration while still using KubeSpawner ≤ 0.11.1 and remove it after upgrade to ensure consistent pod and pvc naming.</p>\n<p>Changing the name template means pvcs for named servers will have different names. This will result in orphaned PVCs for named servers across Hub upgrade! This may appear as data loss for users, depending on configuration, but the orphaned PVCs will still be around and data can be migrated manually (or new PVCs created manually to reference existing PVs) before deleting the old PVCs and/or PVs.</p>\n<h3 id=\"references\">References</h3>\n<p><em>Are there any links users can visit to find out more?</em></p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in <a href=\"https://github.com/jupyterhub/kubespawner\">kubespawner</a></li>\n<li>Email us at <a href=\"mailto:security@ipython.org\">security@ipython.org</a></li>\n</ul>\n<p>Credit: Jining Huang</p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/jupyterhub/kubespawner/security/advisories/GHSA-v7m9-9497-p9gr\">https://github.com/jupyterhub/kubespawner/security/advisories/GHSA-v7m9-9497-p9gr</a></li>\n<li><a href=\"https://github.com/jupyterhub/kubespawner/commit/3dfe870a7f5e98e2e398b01996ca6b8eff4bb1d0\">https://github.com/jupyterhub/kubespawner/commit/3dfe870a7f5e98e2e398b01996ca6b8eff4bb1d0</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-15110\">https://nvd.nist.gov/vuln/detail/CVE-2020-15110</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/jupyterhub-kubespawner/PYSEC-2020-51.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/jupyterhub-kubespawner/PYSEC-2020-51.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v7m9-9497-p9gr\">https://github.com/advisories/GHSA-v7m9-9497-p9gr</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v7m9-9497-p9gr",
            "title": "[jupyterhub-kubespawner] Possible pod name collisions in jupyterhub-kubespawner",
            "date_modified": "2024-09-24T20:43:33.000Z",
            "date_published": "2020-07-22T23:07:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v7m9-9497-p9gr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>mechanize, a library for automatically interacting with HTTP web servers, contains a regular expression that is vulnerable to regular expression denial of service (ReDoS) prior to version 0.4.6. If a web server responds in a malicious way, then mechanize could crash. Version 0.4.6 has a patch for the issue.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-32837\">https://nvd.nist.gov/vuln/detail/CVE-2021-32837</a></li>\n<li><a href=\"https://github.com/python-mechanize/mechanize/commit/dd05334448e9f39814bab044d2eaa5ef69b410d6\">https://github.com/python-mechanize/mechanize/commit/dd05334448e9f39814bab044d2eaa5ef69b410d6</a></li>\n<li><a href=\"https://github.com/python-mechanize/mechanize/blob/3acb1836f3fd8edc5a758a417dd46b53832ae3b5/mechanize/_urllib2_fork.py#L878-L879\">https://github.com/python-mechanize/mechanize/blob/3acb1836f3fd8edc5a758a417dd46b53832ae3b5/mechanize/_urllib2_fork.py#L878-L879</a></li>\n<li><a href=\"https://github.com/python-mechanize/mechanize/releases/tag/v0.4.6\">https://github.com/python-mechanize/mechanize/releases/tag/v0.4.6</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2023/06/msg00022.html\">https://lists.debian.org/debian-lts-announce/2023/06/msg00022.html</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/mechanize/PYSEC-2023-25.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/mechanize/PYSEC-2023-25.yaml</a></li>\n<li><a href=\"https://securitylab.github.com/advisories/GHSL-2021-108-python-mechanize-mechanize\">https://securitylab.github.com/advisories/GHSL-2021-108-python-mechanize-mechanize</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-g3pv-pj5f-3hfq\">https://github.com/advisories/GHSA-g3pv-pj5f-3hfq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-g3pv-pj5f-3hfq",
            "title": "[mechanize] mechanize Regular Expression Denial of Service vulnerability",
            "date_modified": "2024-09-24T20:40:48.000Z",
            "date_published": "2023-01-18T00:30:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-g3pv-pj5f-3hfq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Synapse is an open-source Matrix homeserver written and maintained by the Matrix.org Foundation. The Matrix Federation API allows remote homeservers to request the <em>authorisation events</em> of events in a room. This is necessary so that a homeserver receiving some events can validate that those events are legitimate and permitted in their room.\nHowever, in versions of Synapse up to and including 1.68.0, a Synapse homeserver answering a query for authorisation events does not sufficiently check that the requesting server should be able to access them.</p>\n<p>Authorisation events include power level events (the list of user IDs and their power levels at the time) and relevant membership events (including the display name of the sender of that event), as well as events like <code>m.room.create</code>, <code>m.room.third_party_invite</code> and <code>m.room.join_rules</code>. Non-authorisation events are unaffected, so it isn't possible to e.g. extract message contents this way.</p>\n<p>This issue is only exploitable when a malicious actor knows the ID of a target room and the ID of an event from that room. In most cases, this makes exploitation infeasible. This issue is of negligible consequence for public rooms given that any server can easily join the room in order to be allowed to view authorisation events. Further, deployments in a closed federation where all homeservers are trustworthy are not affected.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The issue was patched in Synapse 1.69.0. Homeserver administrators are advised to upgrade.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Synapse can be configured with a list of servers that it is allowed to federate with <a href=\"https://matrix-org.github.io/synapse/v1.68/usage/configuration/config_documentation.html#federation_domain_whitelist\"><code>federation_domain_whitelist</code></a>. If this list is in use and all the servers on the list are trusted not to exploit this issue, then this issue is of no consequence.</p>\n<p>This workaround is not practical for homeservers participating in open federation as interaction with any server not on the list would have to happen indirectly through servers that are, leading to inconsistent delays in message delivery.</p>\n<h3 id=\"references\">References</h3>\n<p>Fixed in <a href=\"https://github.com/matrix-org/synapse/pull/13823\">https://github.com/matrix-org/synapse/pull/13823</a>.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory, e-mail us at <a href=\"mailto:security@matrix.org\">security@matrix.org</a>.</p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/matrix-org/synapse/security/advisories/GHSA-45cj-f97f-ggwv\">https://github.com/matrix-org/synapse/security/advisories/GHSA-45cj-f97f-ggwv</a></li>\n<li><a href=\"https://github.com/matrix-org/synapse/issues/13288\">https://github.com/matrix-org/synapse/issues/13288</a></li>\n<li><a href=\"https://github.com/matrix-org/synapse/pull/13823\">https://github.com/matrix-org/synapse/pull/13823</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-39335\">https://nvd.nist.gov/vuln/detail/CVE-2022-39335</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/matrix-synapse/PYSEC-2023-65.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/matrix-synapse/PYSEC-2023-65.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T2MBNMZAFY4RCZL2VGBGAPKGB4JUPZVS\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T2MBNMZAFY4RCZL2VGBGAPKGB4JUPZVS</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-45cj-f97f-ggwv\">https://github.com/advisories/GHSA-45cj-f97f-ggwv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-45cj-f97f-ggwv",
            "title": "[matrix-synapse] Synapse does not apply enough checks to servers requesting auth events of events in a room",
            "date_modified": "2024-09-24T20:30:14.000Z",
            "date_published": "2023-05-24T17:20:43.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-45cj-f97f-ggwv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In the marshmallow library before 2.15.1 and 3.x before 3.0.0b9 for Python, the schema \"only\" option treats an empty list as implying no \"only\" option, which allows a request that was intended to expose no fields to instead expose all fields (if the schema is being filtered dynamically using the \"only\" option, and there is a user role that produces an empty value for \"only\").</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-17175\">https://nvd.nist.gov/vuln/detail/CVE-2018-17175</a></li>\n<li><a href=\"https://github.com/marshmallow-code/marshmallow/issues/772\">https://github.com/marshmallow-code/marshmallow/issues/772</a></li>\n<li><a href=\"https://github.com/marshmallow-code/marshmallow/pull/777\">https://github.com/marshmallow-code/marshmallow/pull/777</a></li>\n<li><a href=\"https://github.com/marshmallow-code/marshmallow/pull/782\">https://github.com/marshmallow-code/marshmallow/pull/782</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/marshmallow/PYSEC-2018-67.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/marshmallow/PYSEC-2018-67.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-9q2p-fj49-vpxj\">https://github.com/advisories/GHSA-9q2p-fj49-vpxj</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-9q2p-fj49-vpxj",
            "title": "[marshmallow] In marshmallow library the schema \"only\" option treats an empty list as implying no \"only\" option",
            "date_modified": "2024-09-24T20:09:29.000Z",
            "date_published": "2018-10-10T16:10:46.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-9q2p-fj49-vpxj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Missing input validation of some parameters on the endpoints used to confirm third-party identifiers could cause excessive use of disk space and memory leading to resource exhaustion.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The issue is fixed by #9321.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Depending on the needs and configuration of the homeserver a few options are available:</p>\n<ol>\n<li><p>Using email as third-party identifiers be disabled by not configuring the <code>email</code> setting.</p>\n</li>\n<li><p>Using phone numbers as third-party identifiers can be disabled by ensuring that <code>account_threepid_delegates.msisdn</code> is not configured.</p>\n</li>\n<li><p>Additionally, the affected endpoint patterns can be blocked at a reverse proxy:</p>\n<ul>\n<li><code>^/_matrix/client/(r0|unstable)/register/email</code></li>\n<li><code>^/_matrix/client/(r0|unstable)/register/msisdn</code></li>\n<li><code>^/_matrix/client/(r0|unstable)/account/password</code></li>\n<li><code>^/_matrix/client/(r0|unstable)/account/3pid</code></li>\n</ul>\n</li>\n</ol>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/matrix-org/synapse/security/advisories/GHSA-w9fg-xffh-p362\">https://github.com/matrix-org/synapse/security/advisories/GHSA-w9fg-xffh-p362</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-21394\">https://nvd.nist.gov/vuln/detail/CVE-2021-21394</a></li>\n<li><a href=\"https://github.com/matrix-org/synapse/pull/9321\">https://github.com/matrix-org/synapse/pull/9321</a></li>\n<li><a href=\"https://github.com/matrix-org/synapse/pull/9393\">https://github.com/matrix-org/synapse/pull/9393</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/matrix-synapse/PYSEC-2021-27.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/matrix-synapse/PYSEC-2021-27.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TNNAJOZNMVMXM6AS7RFFKB4QLUJ4IFEY\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TNNAJOZNMVMXM6AS7RFFKB4QLUJ4IFEY</a></li>\n<li><a href=\"https://pypi.org/project/matrix-synapse\">https://pypi.org/project/matrix-synapse</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-w9fg-xffh-p362\">https://github.com/advisories/GHSA-w9fg-xffh-p362</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-w9fg-xffh-p362",
            "title": "[matrix-synapse] Denial of service (via resource exhaustion) due to improper input validation on third-party identifier endpoints",
            "date_modified": "2024-09-24T20:08:24.000Z",
            "date_published": "2021-04-13T15:12:51.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-w9fg-xffh-p362"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-5159\">https://nvd.nist.gov/vuln/detail/CVE-2015-5159</a></li>\n<li><a href=\"https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882\">https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1245200\">https://bugzilla.redhat.com/show_bug.cgi?id=1245200</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-j7c4-2xj8-wm7r\">https://github.com/advisories/GHSA-j7c4-2xj8-wm7r</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/kdcproxy/PYSEC-2018-85.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/kdcproxy/PYSEC-2018-85.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-j7c4-2xj8-wm7r",
            "title": "[kdcproxy] Improper Input Validation in kdcproxy",
            "date_modified": "2024-09-24T18:48:58.000Z",
            "date_published": "2018-11-01T14:49:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-j7c4-2xj8-wm7r"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}