{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>An issue was discovered in Pillow before 8.1.1. In TiffDecode.c, there is a negative-offset memcpy with an invalid size.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-25290\">https://nvd.nist.gov/vuln/detail/CVE-2021-25290</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/86f02f7c70862a0954bfe8133736d352db978eaa\">https://github.com/python-pillow/Pillow/commit/86f02f7c70862a0954bfe8133736d352db978eaa</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html\">https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202107-33\">https://security.gentoo.org/glsa/202107-33</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html\">https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/e25be1e33dc526bfd1094bc778a54d8e29bf66c9\">https://github.com/python-pillow/Pillow/commit/e25be1e33dc526bfd1094bc778a54d8e29bf66c9</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8xjq-8fcg-g5hw\">https://github.com/advisories/GHSA-8xjq-8fcg-g5hw</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-36.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-36.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8xjq-8fcg-g5hw",
            "title": "[pillow] Out-of-bounds Write in Pillow",
            "date_modified": "2024-10-08T13:11:58.000Z",
            "date_published": "2021-03-29T16:35:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8xjq-8fcg-g5hw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Pillow before 8.1.1. TiffDecode has a heap-based buffer overflow when decoding crafted YCbCr files because of certain interpretation conflicts with LibTIFF in RGBA mode. NOTE: this issue exists because of an incomplete fix for CVE-2020-35654.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-25289\">https://nvd.nist.gov/vuln/detail/CVE-2021-25289</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/3fee28eb9479bf7d59e0fa08068f9cc4a6e2f04c\">https://github.com/python-pillow/Pillow/commit/3fee28eb9479bf7d59e0fa08068f9cc4a6e2f04c</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html\">https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202107-33\">https://security.gentoo.org/glsa/202107-33</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/cbfdde7b1f2295059a20a539ee9960f0bec7b299\">https://github.com/python-pillow/Pillow/commit/cbfdde7b1f2295059a20a539ee9960f0bec7b299</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-57h3-9rgr-c24m\">https://github.com/advisories/GHSA-57h3-9rgr-c24m</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-35.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-35.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-57h3-9rgr-c24m",
            "title": "[pillow] Out of bounds write in Pillow",
            "date_modified": "2024-10-08T13:11:34.000Z",
            "date_published": "2021-03-29T16:35:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-57h3-9rgr-c24m"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Buffer overflow in the <code>ImagingPcdDecode</code> function in <code>PcdDecode.c</code> in Pillow before 3.1.1 and Python Imaging Library (PIL) 1.1.7 and earlier allows remote attackers to cause a denial of service (crash) via a crafted PhotoCD file.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-2533\">https://nvd.nist.gov/vuln/detail/CVE-2016-2533</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/pull/1706\">https://github.com/python-pillow/Pillow/pull/1706</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/5bdf54b5a76b54fb00bd05f2d733e0a4173eefc9#diff-8ff6909c159597e22288ad818938fd6b\">https://github.com/python-pillow/Pillow/commit/5bdf54b5a76b54fb00bd05f2d733e0a4173eefc9#diff-8ff6909c159597e22288ad818938fd6b</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/ae453aa18b66af54e7ff716f4ccb33adca60afd4#diff-8ff6909c159597e22288ad818938fd6b\">https://github.com/python-pillow/Pillow/commit/ae453aa18b66af54e7ff716f4ccb33adca60afd4#diff-8ff6909c159597e22288ad818938fd6b</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3c5c-7235-994j\">https://github.com/advisories/GHSA-3c5c-7235-994j</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201612-52\">https://security.gentoo.org/glsa/201612-52</a></li>\n<li><a href=\"http://www.debian.org/security/2016/dsa-3499\">http://www.debian.org/security/2016/dsa-3499</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2016/02/02/5\">http://www.openwall.com/lists/oss-security/2016/02/02/5</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2016/02/22/2\">http://www.openwall.com/lists/oss-security/2016/02/22/2</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinjan2016-2867206.html\">http://www.oracle.com/technetwork/topics/security/bulletinjan2016-2867206.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst?plain=1#L53\">https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst?plain=1#L53</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-19.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-19.yaml</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst\">https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3c5c-7235-994j",
            "title": "[pillow] Pillow buffer overflow in ImagingPcdDecode",
            "date_modified": "2024-10-08T13:09:01.000Z",
            "date_published": "2018-07-24T20:15:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3c5c-7235-994j"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Integer overflow in the <code>ImagingResampleHorizontal</code> function in <code>libImaging/Resample.c</code> in Pillow before 3.1.1 allows remote attackers to have unspecified impact via negative values of the new size, which triggers a heap-based buffer overflow.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-4009\">https://nvd.nist.gov/vuln/detail/CVE-2016-4009</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/pull/1714\">https://github.com/python-pillow/Pillow/pull/1714</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/4e0d9b0b9740d258ade40cce248c93777362ac1e\">https://github.com/python-pillow/Pillow/commit/4e0d9b0b9740d258ade40cce248c93777362ac1e</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hvr8-466p-75rh\">https://github.com/advisories/GHSA-hvr8-466p-75rh</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst\">https://github.com/python-pillow/Pillow/blob/c3cb690fed5d4bf0c45576759de55d054916c165/CHANGES.rst</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201612-52\">https://security.gentoo.org/glsa/201612-52</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/86064\">http://www.securityfocus.com/bid/86064</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-7.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-7.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hvr8-466p-75rh",
            "title": "[pillow] Pillow Integer overflow in ImagingResampleHorizontal",
            "date_modified": "2024-10-08T13:06:58.000Z",
            "date_published": "2018-07-24T20:15:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hvr8-466p-75rh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Pillow before 3.3.2 allows context-dependent attackers to obtain sensitive information by using the \"crafted image file\" approach, related to an \"Integer Overflow\" issue affecting the <code>Image.core.map_buffer</code> in <code>map.c</code> component.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-9189\">https://nvd.nist.gov/vuln/detail/CVE-2016-9189</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/issues/2105\">https://github.com/python-pillow/Pillow/issues/2105</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f\">https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rwr3-c2q8-gm56\">https://github.com/advisories/GHSA-rwr3-c2q8-gm56</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201612-52\">https://security.gentoo.org/glsa/201612-52</a></li>\n<li><a href=\"http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html\">http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html</a></li>\n<li><a href=\"http://www.debian.org/security/2016/dsa-3710\">http://www.debian.org/security/2016/dsa-3710</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/94234\">http://www.securityfocus.com/bid/94234</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-8.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2016-8.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rwr3-c2q8-gm56",
            "title": "[pillow] Pillow Integer overflow in Map.c",
            "date_modified": "2024-10-08T13:06:31.000Z",
            "date_published": "2018-07-24T20:08:27.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rwr3-c2q8-gm56"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Pillow before 8.1.0, PcxDecode has a buffer over-read when decoding a crafted PCX file because the user-supplied stride value is trusted for buffer calculations.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-35653\">https://nvd.nist.gov/vuln/detail/CVE-2020-35653</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/index.html\">https://pillow.readthedocs.io/en/stable/releasenotes/index.html</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html\">https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf\">https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-f5g8-5qq7-938w\">https://github.com/advisories/GHSA-f5g8-5qq7-938w</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-69.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-69.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-f5g8-5qq7-938w",
            "title": "[pillow] Pillow Out-of-bounds Read",
            "date_modified": "2024-10-08T13:05:46.000Z",
            "date_published": "2021-03-18T19:55:41.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-f5g8-5qq7-938w"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Pillow before 8.1.0, SGIRleDecode has a 4-byte buffer over-read when decoding crafted SGI RLE image files because offsets and length tables are mishandled.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-35655\">https://nvd.nist.gov/vuln/detail/CVE-2020-35655</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/index.html\">https://pillow.readthedocs.io/en/stable/releasenotes/index.html</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf\">https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/7e95c63fa7f503f185d3d9eb16b9cee1e54d1e46\">https://github.com/python-pillow/Pillow/commit/7e95c63fa7f503f185d3d9eb16b9cee1e54d1e46</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BYVI5G44MRIPERKYDQEL3S3YQCZTVHE</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF553AMNNNBW7SH4IM4MNE4M6GNZQ7YD</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hf64-x4gq-p99h\">https://github.com/advisories/GHSA-hf64-x4gq-p99h</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-71.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-71.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hf64-x4gq-p99h",
            "title": "[pillow] Pillow Out-of-bounds Read",
            "date_modified": "2024-10-08T13:05:15.000Z",
            "date_published": "2021-03-18T19:55:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hf64-x4gq-p99h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>There is a DoS vulnerability in Pillow before 6.2.2 caused by FpxImagePlugin.py calling the range function on an unvalidated 32-bit integer if the number of bands is large. On Windows running 32-bit Python, this results in an OverflowError or MemoryError due to the 2 GB limit. However, on Linux running 64-bit Python this results in the process being terminated by the OOM killer.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-19911\">https://nvd.nist.gov/vuln/detail/CVE-2019-19911</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/774e53bb132461d8d5ebefec1162e29ec0ebc63d\">https://github.com/python-pillow/Pillow/commit/774e53bb132461d8d5ebefec1162e29ec0ebc63d</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#622-2020-01-02\">https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#622-2020-01-02</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html\">https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html</a></li>\n<li><a href=\"https://www.debian.org/security/2020/dsa-4631\">https://www.debian.org/security/2020/dsa-4631</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5gm3-px64-rw72\">https://github.com/advisories/GHSA-5gm3-px64-rw72</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-172.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-172.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P</a></li>\n<li><a href=\"https://usn.ubuntu.com/4272-1\">https://usn.ubuntu.com/4272-1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5gm3-px64-rw72",
            "title": "[pillow] Uncontrolled Resource Consumption in Pillow",
            "date_modified": "2024-10-08T13:04:35.000Z",
            "date_published": "2020-04-01T16:36:44.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5gm3-px64-rw72"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>libImaging/TiffDecode.c</code> in Pillow before 6.2.2 has a TIFF decoding integer overflow, related to realloc.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-5310\">https://nvd.nist.gov/vuln/detail/CVE-2020-5310</a></li>\n<li><a href=\"https://github.com/python-pillow/Pillow/commit/4e2def2539ec13e53a82e06c4b3daf00454100c4\">https://github.com/python-pillow/Pillow/commit/4e2def2539ec13e53a82e06c4b3daf00454100c4</a></li>\n<li><a href=\"https://github.com/pypa/advisory-db/blob/7872b0a91b4d980f749e6d75a81f8cc1af32829f/vulns/pillow/PYSEC-2020-81.yaml\">https://github.com/pypa/advisory-db/blob/7872b0a91b4d980f749e6d75a81f8cc1af32829f/vulns/pillow/PYSEC-2020-81.yaml</a></li>\n<li><a href=\"https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html\">https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vcqg-3p29-xw73\">https://github.com/advisories/GHSA-vcqg-3p29-xw73</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-81.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2020-81.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2MMU3WT2X64GS5WHDPKKC2WZA7UIIQ3A\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2MMU3WT2X64GS5WHDPKKC2WZA7UIIQ3A</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P</a></li>\n<li><a href=\"https://usn.ubuntu.com/4272-1\">https://usn.ubuntu.com/4272-1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vcqg-3p29-xw73",
            "title": "[pillow] Integer overflow in Pillow",
            "date_modified": "2024-10-08T13:03:45.000Z",
            "date_published": "2021-11-03T18:04:41.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vcqg-3p29-xw73"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>ovirt-engine-sdk-python before 3.4.0.7 and 3.5.0.4 does not verify that the hostname of the remote endpoint matches the Common Name (CN) or subjectAltName as specified by its x.509 certificate in a TLS/SSL session. This could allow man-in-the-middle attackers to spoof remote endpoints via an arbitrary valid certificate.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-0161\">https://nvd.nist.gov/vuln/detail/CVE-2014-0161</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/cve-2014-0161\">https://access.redhat.com/security/cve/cve-2014-0161</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-0161\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-0161</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ovirt-engine-sdk-python/PYSEC-2020-245.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ovirt-engine-sdk-python/PYSEC-2020-245.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wf9j-m9fv-92gq\">https://github.com/advisories/GHSA-wf9j-m9fv-92gq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wf9j-m9fv-92gq",
            "title": "[ovirt-engine-sdk-python] ovirt-engine-sdk-python improper validation of hostname in x.509 certificate",
            "date_modified": "2024-10-08T12:56:51.000Z",
            "date_published": "2022-05-17T19:57:11.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wf9j-m9fv-92gq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"background\">Background</h3>\n<p>A variety of templates do not perform proper sanitization through HTML escaping.\nDue to the lack of sanitization and use of <code>jQuery.html()</code>, there are a whole host of XSS possibilities with specially crafted input to a variety of fields.</p>\n<h3 id=\"impact\">Impact</h3>\n<p>OMERO.web before 5.11.0 and OMERO.figure before 4.4.1.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Users should upgrade OMERO.web to 5.11.0 or higher and OMERO.figure to 4.4.1 or higher.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/ome/omero-web/security/advisories/GHSA-g67g-hvc3-xmvf\">https://github.com/ome/omero-web/security/advisories/GHSA-g67g-hvc3-xmvf</a></li>\n<li><a href=\"https://github.com/ome/omero-web/commit/0168067accde5e635341b3c714b1d53ae92ba424\">https://github.com/ome/omero-web/commit/0168067accde5e635341b3c714b1d53ae92ba424</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-41132\">https://nvd.nist.gov/vuln/detail/CVE-2021-41132</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/omero-figure/PYSEC-2021-379.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/omero-figure/PYSEC-2021-379.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/omero-web/PYSEC-2021-372.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/omero-web/PYSEC-2021-372.yaml</a></li>\n<li><a href=\"https://www.openmicroscopy.org/security/advisories/2021-SV3\">https://www.openmicroscopy.org/security/advisories/2021-SV3</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-g67g-hvc3-xmvf\">https://github.com/advisories/GHSA-g67g-hvc3-xmvf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-g67g-hvc3-xmvf",
            "title": "[omero-web] Inconsistent input sanitisation leads to XSS vectors",
            "date_modified": "2024-10-08T12:42:28.000Z",
            "date_published": "2021-10-14T21:19:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-g67g-hvc3-xmvf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In a default Red Hat Openstack Platform Director installation, openstack-octavia before versions openstack-octavia 2.0.2-5 and openstack-octavia-3.0.1-0.20181009115732 creates log files that are readable by all users. Sensitive information such as private keys can appear in these log files allowing for information exposure.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-16856\">https://nvd.nist.gov/vuln/detail/CVE-2018-16856</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16856\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16856</a></li>\n<li><a href=\"https://github.com/openstack/octavia/commit/ae7c87f54a6c5483a608d5e9fe51ea1966ea1f7e\">https://github.com/openstack/octavia/commit/ae7c87f54a6c5483a608d5e9fe51ea1966ea1f7e</a></li>\n<li><a href=\"https://github.com/openstack/octavia/commits/3.1.0\">https://github.com/openstack/octavia/commits/3.1.0</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/octavia/PYSEC-2019-193.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/octavia/PYSEC-2019-193.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qcj3-h27m-mp9x\">https://github.com/advisories/GHSA-qcj3-h27m-mp9x</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qcj3-h27m-mp9x",
            "title": "[octavia] Openstack Octavia allows Insertion of Sensitive Information into Log File",
            "date_modified": "2024-10-07T21:32:18.000Z",
            "date_published": "2022-05-13T01:07:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qcj3-h27m-mp9x"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulnerable to an information disclosure. Software using the CatchError class could include sensitive values in a traceback's error message. System users could exploit this flaw to obtain sensitive information from OpenStack component error logs (for example, keystone tokens).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-2592\">https://nvd.nist.gov/vuln/detail/CVE-2017-2592</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xcp8-hh74-f6mc\">https://github.com/advisories/GHSA-xcp8-hh74-f6mc</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:0300\">https://access.redhat.com/errata/RHSA-2017:0300</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:0435\">https://access.redhat.com/errata/RHSA-2017:0435</a></li>\n<li><a href=\"https://bugs.launchpad.net/keystonemiddleware/+bug/1628031\">https://bugs.launchpad.net/keystonemiddleware/+bug/1628031</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/oslo-middleware/PYSEC-2018-104.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/oslo-middleware/PYSEC-2018-104.yaml</a></li>\n<li><a href=\"http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html\">http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2017-0300.html\">http://rhn.redhat.com/errata/RHSA-2017-0300.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2017-0435.html\">http://rhn.redhat.com/errata/RHSA-2017-0435.html</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425730\">https://review.openstack.org/#/c/425730</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425732\">https://review.openstack.org/#/c/425732</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425734\">https://review.openstack.org/#/c/425734</a></li>\n<li><a href=\"https://usn.ubuntu.com/3666-1\">https://usn.ubuntu.com/3666-1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xcp8-hh74-f6mc",
            "title": "[oslo-middleware] oslo.middleware Information Disclosure vulnerability",
            "date_modified": "2024-10-07T21:21:54.000Z",
            "date_published": "2018-07-13T15:16:45.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xcp8-hh74-f6mc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulnerable to an information disclosure. Software using the CatchError class could include sensitive values in a traceback's error message. System users could exploit this flaw to obtain sensitive information from OpenStack component error logs (for example, keystone tokens).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-2592\">https://nvd.nist.gov/vuln/detail/CVE-2017-2592</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xcp8-hh74-f6mc\">https://github.com/advisories/GHSA-xcp8-hh74-f6mc</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:0300\">https://access.redhat.com/errata/RHSA-2017:0300</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:0435\">https://access.redhat.com/errata/RHSA-2017:0435</a></li>\n<li><a href=\"https://bugs.launchpad.net/keystonemiddleware/+bug/1628031\">https://bugs.launchpad.net/keystonemiddleware/+bug/1628031</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/oslo-middleware/PYSEC-2018-104.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/oslo-middleware/PYSEC-2018-104.yaml</a></li>\n<li><a href=\"http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html\">http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2017-0300.html\">http://rhn.redhat.com/errata/RHSA-2017-0300.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2017-0435.html\">http://rhn.redhat.com/errata/RHSA-2017-0435.html</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425730\">https://review.openstack.org/#/c/425730</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425732\">https://review.openstack.org/#/c/425732</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425734\">https://review.openstack.org/#/c/425734</a></li>\n<li><a href=\"https://usn.ubuntu.com/3666-1\">https://usn.ubuntu.com/3666-1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xcp8-hh74-f6mc",
            "title": "[oslo-middleware] oslo.middleware Information Disclosure vulnerability",
            "date_modified": "2024-10-07T21:21:54.000Z",
            "date_published": "2018-07-13T15:16:45.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xcp8-hh74-f6mc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulnerable to an information disclosure. Software using the CatchError class could include sensitive values in a traceback's error message. System users could exploit this flaw to obtain sensitive information from OpenStack component error logs (for example, keystone tokens).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-2592\">https://nvd.nist.gov/vuln/detail/CVE-2017-2592</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xcp8-hh74-f6mc\">https://github.com/advisories/GHSA-xcp8-hh74-f6mc</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:0300\">https://access.redhat.com/errata/RHSA-2017:0300</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:0435\">https://access.redhat.com/errata/RHSA-2017:0435</a></li>\n<li><a href=\"https://bugs.launchpad.net/keystonemiddleware/+bug/1628031\">https://bugs.launchpad.net/keystonemiddleware/+bug/1628031</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/oslo-middleware/PYSEC-2018-104.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/oslo-middleware/PYSEC-2018-104.yaml</a></li>\n<li><a href=\"http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html\">http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2017-0300.html\">http://rhn.redhat.com/errata/RHSA-2017-0300.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2017-0435.html\">http://rhn.redhat.com/errata/RHSA-2017-0435.html</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425730\">https://review.openstack.org/#/c/425730</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425732\">https://review.openstack.org/#/c/425732</a></li>\n<li><a href=\"https://review.openstack.org/#/c/425734\">https://review.openstack.org/#/c/425734</a></li>\n<li><a href=\"https://usn.ubuntu.com/3666-1\">https://usn.ubuntu.com/3666-1</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xcp8-hh74-f6mc",
            "title": "[oslo-middleware] oslo.middleware Information Disclosure vulnerability",
            "date_modified": "2024-10-07T21:21:54.000Z",
            "date_published": "2018-07-13T15:16:45.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xcp8-hh74-f6mc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An exploitable vulnerability exists in the YAML loading functionality of util.py in OwlMixin before 2.0.0a12. A \"Load YAML\" string or file (aka load_yaml or load_yamlf) can execute arbitrary Python commands resulting in command execution because load is used where safe_load should have been used. An attacker can insert Python into loaded YAML to trigger this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-16618\">https://nvd.nist.gov/vuln/detail/CVE-2017-16618</a></li>\n<li><a href=\"https://github.com/tadashi-aikawa/owlmixin/issues/12\">https://github.com/tadashi-aikawa/owlmixin/issues/12</a></li>\n<li><a href=\"https://github.com/tadashi-aikawa/owlmixin/commit/5d0575303f6df869a515ced4285f24ba721e0d4e\">https://github.com/tadashi-aikawa/owlmixin/commit/5d0575303f6df869a515ced4285f24ba721e0d4e</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-ccmq-qvcp-5mrm\">https://github.com/advisories/GHSA-ccmq-qvcp-5mrm</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/owlmixin/PYSEC-2017-22.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/owlmixin/PYSEC-2017-22.yaml</a></li>\n<li><a href=\"https://joel-malwarebenchmark.github.io/blog/2017/11/08/cve-2017-16618-convert-through-owlmixin\">https://joel-malwarebenchmark.github.io/blog/2017/11/08/cve-2017-16618-convert-through-owlmixin</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-ccmq-qvcp-5mrm",
            "title": "[owlmixin] Unsafe deserialization in owlmixin",
            "date_modified": "2024-10-07T21:07:58.000Z",
            "date_published": "2018-07-13T16:01:12.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-ccmq-qvcp-5mrm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>CVEs on latest 3.1.1</p>\n<h3 id=\"details\">Details</h3>\n<h2 id=\"security-issues\">SECURITY ISSUES</h2>\n<h3 id=\"cve-2024-1681-flask-core-401\">CVE-2024-1681: flask-core &lt;4.0.1</h3>\n<p>latest version of taipi 3.1.1 needs &lt;=4.0.0 </p>\n<h3 id=\"cve-2024-5629-pymongo-463\">CVE-2024-5629: pymongo &lt;4.6.3</h3>\n<p>#latest version of taipi 3.1.1 needs &lt;=4.6.1 </p>\n<h3 id=\"poc\">PoC</h3>\n<p>please upgrade to these versions </p>\n<h3 id=\"impact\">Impact</h3>\n<p>pre-commit breaks</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/Avaiga/taipy/security/advisories/GHSA-pp84-v3mw-gg4w\">https://github.com/Avaiga/taipy/security/advisories/GHSA-pp84-v3mw-gg4w</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pp84-v3mw-gg4w\">https://github.com/advisories/GHSA-pp84-v3mw-gg4w</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pp84-v3mw-gg4w",
            "title": "[taipy] Taipy 3.1.1 affected by CVEs on flask-core and pymongo",
            "date_modified": "2024-10-07T16:50:25.000Z",
            "date_published": "2024-08-27T19:50:54.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pp84-v3mw-gg4w"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>The cache action in action/cache.py allows directory traversal through a crafted HTTP request. An attacker who can upload attachments to the wiki can use this to achieve remote code execution.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Users are strongly advised to upgrade to a patched version.</p>\n<p>MoinMoin Wiki 1.9.11 has the necessary fixes and also contains other important fixes.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>It is not advised to work around this, but to upgrade MoinMoin to a patched version.</p>\n<p>That said, a work around via disabling the <code>cache</code> or the <code>AttachFile</code> action might be possible.</p>\n<p>Also, it is of course helpful if you give <code>write</code> permissions (which include uploading attachments) only to trusted users.</p>\n<h3 id=\"credits\">Credits</h3>\n<p>This vulnerability was discovered by Michael Chapman.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory, email me at <a href=\"mailto:twaldmann@thinkmo.de\">twaldmann@thinkmo.de</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/moinwiki/moin-1.9/security/advisories/GHSA-52q8-877j-gghq\">https://github.com/moinwiki/moin-1.9/security/advisories/GHSA-52q8-877j-gghq</a></li>\n<li><a href=\"https://github.com/moinwiki/moin-1.9/commit/6b96a9060069302996b5af47fd4a388fc80172b7\">https://github.com/moinwiki/moin-1.9/commit/6b96a9060069302996b5af47fd4a388fc80172b7</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-25074\">https://nvd.nist.gov/vuln/detail/CVE-2020-25074</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2020/11/msg00020.html\">https://lists.debian.org/debian-lts-announce/2020/11/msg00020.html</a></li>\n<li><a href=\"https://www.debian.org/security/2020/dsa-4787\">https://www.debian.org/security/2020/dsa-4787</a></li>\n<li><a href=\"http://moinmo.in/SecurityFixes\">http://moinmo.in/SecurityFixes</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/moin/PYSEC-2020-67.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/moin/PYSEC-2020-67.yaml</a></li>\n<li><a href=\"https://pypi.org/project/moin\">https://pypi.org/project/moin</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-52q8-877j-gghq\">https://github.com/advisories/GHSA-52q8-877j-gghq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-52q8-877j-gghq",
            "title": "[moin] MoinMoin vulnerable to remote code execution via cache action",
            "date_modified": "2024-10-07T14:54:34.000Z",
            "date_published": "2020-11-11T15:54:51.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-52q8-877j-gghq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Jupyter Notebook before 5.5.0 does not use a CSP header to treat served files as belonging to a separate origin. Thus, for example, an XSS payload can be placed in an SVG document.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-21030\">https://nvd.nist.gov/vuln/detail/CVE-2018-21030</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/pull/3341\">https://github.com/jupyter/notebook/pull/3341</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/releases/tag/5.5.0\">https://github.com/jupyter/notebook/releases/tag/5.5.0</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html\">https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/e321c80776542b8d6f3411af16f9e21e51e27687\">https://github.com/jupyter/notebook/commit/e321c80776542b8d6f3411af16f9e21e51e27687</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jqwc-jm56-wcwj\">https://github.com/advisories/GHSA-jqwc-jm56-wcwj</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2019-157.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2019-157.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jqwc-jm56-wcwj",
            "title": "[notebook] Cross-site scripting in Jupyter Notebook",
            "date_modified": "2024-10-07T14:48:30.000Z",
            "date_published": "2019-11-08T17:07:42.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jqwc-jm56-wcwj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In OpenStack Ironic before 21.4.4, 22.x and 23.x before 23.0.3, 23.x and 24.x before 24.1.3, and 25.x and 26.x before 26.1.0, there is a lack of checksum validation of supplied image_source URLs when configured to convert images to a raw format for streaming.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-47211\">https://nvd.nist.gov/vuln/detail/CVE-2024-47211</a></li>\n<li><a href=\"https://github.com/openstack/ironic/compare/24.1.2...26.1.0\">https://github.com/openstack/ironic/compare/24.1.2...26.1.0</a></li>\n<li><a href=\"https://github.com/openstack/ironic/security\">https://github.com/openstack/ironic/security</a></li>\n<li><a href=\"https://github.com/openstack/ironic/tags\">https://github.com/openstack/ironic/tags</a></li>\n<li><a href=\"https://security.openstack.org/ossa/OSSA-2024-004.html\">https://security.openstack.org/ossa/OSSA-2024-004.html</a></li>\n<li><a href=\"https://github.com/openstack/ironic/commit/2127cc4c93770778457fde0582c1bba258c67e02\">https://github.com/openstack/ironic/commit/2127cc4c93770778457fde0582c1bba258c67e02</a></li>\n<li><a href=\"https://github.com/openstack/ironic/commit/7a1292c569a84eb05806a57a89fca5bb6b0c4043\">https://github.com/openstack/ironic/commit/7a1292c569a84eb05806a57a89fca5bb6b0c4043</a></li>\n<li><a href=\"https://github.com/openstack/ironic/commit/ebce0fd0845de411171127a55002ae7c9605de57\">https://github.com/openstack/ironic/commit/ebce0fd0845de411171127a55002ae7c9605de57</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8h22-6qwx-q4w9\">https://github.com/advisories/GHSA-8h22-6qwx-q4w9</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8h22-6qwx-q4w9",
            "title": "[ironic] OpenStack Ironic fails to verify checksums of supplied image_source URLs",
            "date_modified": "2024-10-04T20:31:16.000Z",
            "date_published": "2024-10-04T18:31:11.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8h22-6qwx-q4w9"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}