{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>CKAN through 2.9.6 account takeovers by unauthenticated users when an existing user id is sent via an HTTP POST request. This allows a user to take over an existing account including superuser accounts.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-43685\">https://nvd.nist.gov/vuln/detail/CVE-2022-43685</a></li>\n<li><a href=\"https://ckan.org/blog/get-latest-patch-releases-your-ckan-site-october-2022\">https://ckan.org/blog/get-latest-patch-releases-your-ckan-site-october-2022</a></li>\n<li><a href=\"https://ckan.org\">https://ckan.org</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ckan/PYSEC-2022-42987.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ckan/PYSEC-2022-42987.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m2xp-jxfg-qq6g\">https://github.com/advisories/GHSA-m2xp-jxfg-qq6g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m2xp-jxfg-qq6g",
            "title": "[ckan] CKAN contains Improper Authentication leading to account takeover",
            "date_modified": "2024-09-06T16:31:22.000Z",
            "date_published": "2022-11-22T03:30:56.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m2xp-jxfg-qq6g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross Site Scripting (XSS) vulnerability in Arachnys Cabot up to and including 0.11.12 can be exploited via the Address column.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-25449\">https://nvd.nist.gov/vuln/detail/CVE-2020-25449</a></li>\n<li><a href=\"https://itsmeanonartist.tech/blogs/blog2.html\">https://itsmeanonartist.tech/blogs/blog2.html</a></li>\n<li><a href=\"https://packetstormsecurity.com/files/159070/Cabot-0.11.12-Cross-Site-Scripting.html\">https://packetstormsecurity.com/files/159070/Cabot-0.11.12-Cross-Site-Scripting.html</a></li>\n<li><a href=\"https://www.exploit-db.com/exploits/48791\">https://www.exploit-db.com/exploits/48791</a></li>\n<li><a href=\"https://www.exploitalert.com/view-details.html?id=36106\">https://www.exploitalert.com/view-details.html?id=36106</a></li>\n<li><a href=\"https://github.com/arachnys/cabot/commit/18708572cb0ed143842409419eada91160413973\">https://github.com/arachnys/cabot/commit/18708572cb0ed143842409419eada91160413973</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/cabot/PYSEC-2020-226.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/cabot/PYSEC-2020-226.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8q2h-4mq6-396j\">https://github.com/advisories/GHSA-8q2h-4mq6-396j</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8q2h-4mq6-396j",
            "title": "[cabot] Cabot Cross Site Scripting (XSS) vulnerability via Address column",
            "date_modified": "2024-09-06T16:30:06.000Z",
            "date_published": "2022-05-24T17:35:22.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8q2h-4mq6-396j"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in OpenStack blazar-dashboard before 1.3.1, 2.0.0, and 3.0.0. A user allowed to access the Blazar dashboard in Horizon may trigger code execution on the Horizon host as the user the Horizon service runs under (because the Python eval function is used). This may result in Horizon host unauthorized access and further compromise of the Horizon service. All setups using the Horizon dashboard with the blazar-dashboard plugin are affected.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-26943\">https://nvd.nist.gov/vuln/detail/CVE-2020-26943</a></li>\n<li><a href=\"https://launchpad.net/bugs/1895688\">https://launchpad.net/bugs/1895688</a></li>\n<li><a href=\"https://review.opendev.org/755810\">https://review.opendev.org/755810</a></li>\n<li><a href=\"https://review.opendev.org/755812\">https://review.opendev.org/755812</a></li>\n<li><a href=\"https://review.opendev.org/755813\">https://review.opendev.org/755813</a></li>\n<li><a href=\"https://review.opendev.org/755814\">https://review.opendev.org/755814</a></li>\n<li><a href=\"https://review.opendev.org/756064\">https://review.opendev.org/756064</a></li>\n<li><a href=\"https://security.openstack.org/ossa/OSSA-2020-007.html\">https://security.openstack.org/ossa/OSSA-2020-007.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2020/10/16/5\">http://www.openwall.com/lists/oss-security/2020/10/16/5</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/blazar-dashboard/PYSEC-2020-225.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/blazar-dashboard/PYSEC-2020-225.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-939m-4xpw-v34v\">https://github.com/advisories/GHSA-939m-4xpw-v34v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-939m-4xpw-v34v",
            "title": "[blazar-dashboard] Arbitrary Code Execution in blazar-dashboard",
            "date_modified": "2024-09-06T16:25:49.000Z",
            "date_published": "2020-10-27T17:55:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-939m-4xpw-v34v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in OpenStack blazar-dashboard before 1.3.1, 2.0.0, and 3.0.0. A user allowed to access the Blazar dashboard in Horizon may trigger code execution on the Horizon host as the user the Horizon service runs under (because the Python eval function is used). This may result in Horizon host unauthorized access and further compromise of the Horizon service. All setups using the Horizon dashboard with the blazar-dashboard plugin are affected.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-26943\">https://nvd.nist.gov/vuln/detail/CVE-2020-26943</a></li>\n<li><a href=\"https://launchpad.net/bugs/1895688\">https://launchpad.net/bugs/1895688</a></li>\n<li><a href=\"https://review.opendev.org/755810\">https://review.opendev.org/755810</a></li>\n<li><a href=\"https://review.opendev.org/755812\">https://review.opendev.org/755812</a></li>\n<li><a href=\"https://review.opendev.org/755813\">https://review.opendev.org/755813</a></li>\n<li><a href=\"https://review.opendev.org/755814\">https://review.opendev.org/755814</a></li>\n<li><a href=\"https://review.opendev.org/756064\">https://review.opendev.org/756064</a></li>\n<li><a href=\"https://security.openstack.org/ossa/OSSA-2020-007.html\">https://security.openstack.org/ossa/OSSA-2020-007.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2020/10/16/5\">http://www.openwall.com/lists/oss-security/2020/10/16/5</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/blazar-dashboard/PYSEC-2020-225.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/blazar-dashboard/PYSEC-2020-225.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-939m-4xpw-v34v\">https://github.com/advisories/GHSA-939m-4xpw-v34v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-939m-4xpw-v34v",
            "title": "[blazar-dashboard] Arbitrary Code Execution in blazar-dashboard",
            "date_modified": "2024-09-06T16:25:49.000Z",
            "date_published": "2020-10-27T17:55:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-939m-4xpw-v34v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in OpenStack blazar-dashboard before 1.3.1, 2.0.0, and 3.0.0. A user allowed to access the Blazar dashboard in Horizon may trigger code execution on the Horizon host as the user the Horizon service runs under (because the Python eval function is used). This may result in Horizon host unauthorized access and further compromise of the Horizon service. All setups using the Horizon dashboard with the blazar-dashboard plugin are affected.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-26943\">https://nvd.nist.gov/vuln/detail/CVE-2020-26943</a></li>\n<li><a href=\"https://launchpad.net/bugs/1895688\">https://launchpad.net/bugs/1895688</a></li>\n<li><a href=\"https://review.opendev.org/755810\">https://review.opendev.org/755810</a></li>\n<li><a href=\"https://review.opendev.org/755812\">https://review.opendev.org/755812</a></li>\n<li><a href=\"https://review.opendev.org/755813\">https://review.opendev.org/755813</a></li>\n<li><a href=\"https://review.opendev.org/755814\">https://review.opendev.org/755814</a></li>\n<li><a href=\"https://review.opendev.org/756064\">https://review.opendev.org/756064</a></li>\n<li><a href=\"https://security.openstack.org/ossa/OSSA-2020-007.html\">https://security.openstack.org/ossa/OSSA-2020-007.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2020/10/16/5\">http://www.openwall.com/lists/oss-security/2020/10/16/5</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/blazar-dashboard/PYSEC-2020-225.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/blazar-dashboard/PYSEC-2020-225.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-939m-4xpw-v34v\">https://github.com/advisories/GHSA-939m-4xpw-v34v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-939m-4xpw-v34v",
            "title": "[blazar-dashboard] Arbitrary Code Execution in blazar-dashboard",
            "date_modified": "2024-09-06T16:25:49.000Z",
            "date_published": "2020-10-27T17:55:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-939m-4xpw-v34v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Changedetection.io before 0.40.2 was discovered to contain a stored cross-site scripting (XSS) vulnerability in the main page. This vulnerability allows attackers to execute arbitrary web scripts or HTML via a crafted payload injected into the URL parameter under the \"Add a new change detection watch\" function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-24769\">https://nvd.nist.gov/vuln/detail/CVE-2023-24769</a></li>\n<li><a href=\"https://github.com/dgtlmoon/changedetection.io/issues/1358\">https://github.com/dgtlmoon/changedetection.io/issues/1358</a></li>\n<li><a href=\"https://www.edoardoottavianelli.it/CVE-2023-24769\">https://www.edoardoottavianelli.it/CVE-2023-24769</a></li>\n<li><a href=\"https://github.com/dgtlmoon/changedetection.io/pull/1359\">https://github.com/dgtlmoon/changedetection.io/pull/1359</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/changedetection-io/PYSEC-2023-10.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/changedetection-io/PYSEC-2023-10.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-68wj-c2jw-5pp9\">https://github.com/advisories/GHSA-68wj-c2jw-5pp9</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-68wj-c2jw-5pp9",
            "title": "[changedetection.io] Stored cross site scripting in changedetection.io",
            "date_modified": "2024-09-06T16:21:58.000Z",
            "date_published": "2023-02-18T00:31:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-68wj-c2jw-5pp9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability, which was classified as problematic, has been found in collective.dms.basecontent. This issue affects the function renderCell of the file src/collective/dms/basecontent/browser/column.py. The manipulation leads to cross site scripting. The attack may be initiated remotely. Upgrading to version 1.7 or later will address this issue. The patch is at commit 6c4d616fcc771822a14ebae5e23f3f6d96d134bd. It is recommended to upgrade the affected component. The identifier VDB-215813 was assigned to this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-4495\">https://nvd.nist.gov/vuln/detail/CVE-2022-4495</a></li>\n<li><a href=\"https://github.com/collective/collective.dms.basecontent/commit/6c4d616fcc771822a14ebae5e23f3f6d96d134bd\">https://github.com/collective/collective.dms.basecontent/commit/6c4d616fcc771822a14ebae5e23f3f6d96d134bd</a></li>\n<li><a href=\"https://vuldb.com/?id.215813\">https://vuldb.com/?id.215813</a></li>\n<li><a href=\"https://github.com/collective/collective.dms.basecontent/releases/tag/1.7\">https://github.com/collective/collective.dms.basecontent/releases/tag/1.7</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/collective-dms-basecontent/PYSEC-2022-42989.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/collective-dms-basecontent/PYSEC-2022-42989.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r48c-4vfj-h426\">https://github.com/advisories/GHSA-r48c-4vfj-h426</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r48c-4vfj-h426",
            "title": "[collective.dms.basecontent] collective.dms.basecontent Cross-site Scripting vulnerability",
            "date_modified": "2024-09-06T16:20:51.000Z",
            "date_published": "2022-12-14T15:30:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r48c-4vfj-h426"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>calibreweb prior to version 0.6.16 contains an Incorrect Authorization vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-0273\">https://nvd.nist.gov/vuln/detail/CVE-2022-0273</a></li>\n<li><a href=\"https://github.com/janeczku/calibre-web/commit/0c0313f375bed7b035c8c0482bbb09599e16bfcf\">https://github.com/janeczku/calibre-web/commit/0c0313f375bed7b035c8c0482bbb09599e16bfcf</a></li>\n<li><a href=\"https://huntr.dev/bounties/8f27686f-d698-4ab6-8ef0-899125792f13\">https://huntr.dev/bounties/8f27686f-d698-4ab6-8ef0-899125792f13</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/calibreweb/PYSEC-2022-22.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/calibreweb/PYSEC-2022-22.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vgmw-9cww-qq99\">https://github.com/advisories/GHSA-vgmw-9cww-qq99</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vgmw-9cww-qq99",
            "title": "[calibreweb] Incorrect Authorization in calibreweb",
            "date_modified": "2024-09-06T15:50:22.000Z",
            "date_published": "2022-01-31T00:00:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vgmw-9cww-qq99"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Cobbler through 3.3.0. In the templar.py file, the function check_for_invalid_imports can allow Cheetah code to import Python modules via the \"#from MODULE import\" substring. (Only lines beginning with #import are blocked.)</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45082\">https://nvd.nist.gov/vuln/detail/CVE-2021-45082</a></li>\n<li><a href=\"https://bugzilla.suse.com/show_bug.cgi?id=1193678\">https://bugzilla.suse.com/show_bug.cgi?id=1193678</a></li>\n<li><a href=\"https://github.com/cobbler/cobbler/releases\">https://github.com/cobbler/cobbler/releases</a></li>\n<li><a href=\"https://github.com/cobbler/cobbler/pull/2945\">https://github.com/cobbler/cobbler/pull/2945</a></li>\n<li><a href=\"https://github.com/cobbler/cobbler/releases/tag/v3.3.1\">https://github.com/cobbler/cobbler/releases/tag/v3.3.1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/cobbler/PYSEC-2022-37.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/cobbler/PYSEC-2022-37.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TEJN7CPW6YCHBFQPFZKGA6AVA6T5NPIW\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TEJN7CPW6YCHBFQPFZKGA6AVA6T5NPIW</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Z5CSXQE7Q4TVDQJKFYBO4XDH3BZ7BLAR\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Z5CSXQE7Q4TVDQJKFYBO4XDH3BZ7BLAR</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZCXMOUW4DH4DYWIJN44SMSU6R3CZDZBE\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZCXMOUW4DH4DYWIJN44SMSU6R3CZDZBE</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6cm4-gm85-972c\">https://github.com/advisories/GHSA-6cm4-gm85-972c</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6cm4-gm85-972c",
            "title": "[cobbler] Command Injection in Cobbler",
            "date_modified": "2024-09-06T15:47:49.000Z",
            "date_published": "2022-02-20T00:00:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6cm4-gm85-972c"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>bleach.clean</code> behavior parsing style attributes could result in a regular expression denial of service (ReDoS).</p>\n<p>Calls to <code>bleach.clean</code> with an allowed tag with an allowed <code>style</code> attribute are vulnerable to ReDoS. For example, <code>bleach.clean(..., attributes={'a': ['style']})</code>.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>3.1.4</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<ul>\n<li><p>do not whitelist the style attribute in <code>bleach.clean</code> calls</p>\n</li>\n<li><p>limit input string length</p>\n</li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://bugzilla.mozilla.org/show_bug.cgi?id=1623633\">https://bugzilla.mozilla.org/show_bug.cgi?id=1623633</a></li>\n<li><a href=\"https://www.regular-expressions.info/redos.html\">https://www.regular-expressions.info/redos.html</a></li>\n<li><a href=\"https://blog.r2c.dev/posts/finding-python-redos-bugs-at-scale-using-dlint-and-r2c/\">https://blog.r2c.dev/posts/finding-python-redos-bugs-at-scale-using-dlint-and-r2c/</a></li>\n<li><a href=\"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6817\">https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6817</a></li>\n</ul>\n<h3 id=\"credits\">Credits</h3>\n<ul>\n<li>Reported by schwag09 of r2c</li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue at <a href=\"https://github.com/mozilla/bleach/issues\">https://github.com/mozilla/bleach/issues</a></li>\n<li>Email us at <a href=\"mailto:security@mozilla.org\">security@mozilla.org</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/mozilla/bleach/security/advisories/GHSA-vqhp-cxgc-6wmm\">https://github.com/mozilla/bleach/security/advisories/GHSA-vqhp-cxgc-6wmm</a></li>\n<li><a href=\"https://bugzilla.mozilla.org/show_bug.cgi?id=1623633\">https://bugzilla.mozilla.org/show_bug.cgi?id=1623633</a></li>\n<li><a href=\"https://github.com/mozilla/bleach/releases/tag/v3.1.4\">https://github.com/mozilla/bleach/releases/tag/v3.1.4</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-6817\">https://nvd.nist.gov/vuln/detail/CVE-2020-6817</a></li>\n<li><a href=\"https://snyk.io/vuln/SNYK-PYTHON-BLEACH-561754\">https://snyk.io/vuln/SNYK-PYTHON-BLEACH-561754</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/bleach/PYSEC-2020-340.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/bleach/PYSEC-2020-340.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vqhp-cxgc-6wmm\">https://github.com/advisories/GHSA-vqhp-cxgc-6wmm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vqhp-cxgc-6wmm",
            "title": "[bleach] regular expression denial-of-service (ReDoS) in Bleach",
            "date_modified": "2024-09-06T15:46:16.000Z",
            "date_published": "2020-03-30T19:45:56.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vqhp-cxgc-6wmm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The Serialize.deserialize() method in CoAPthon3 1.0 and 1.0.1 mishandles certain exceptions, leading to a denial of service in applications that use this library (e.g., the standard CoAP server, CoAP client, example collect CoAP server and client) when they receive crafted CoAP messages.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-12679\">https://nvd.nist.gov/vuln/detail/CVE-2018-12679</a></li>\n<li><a href=\"https://github.com/Tanganelli/CoAPthon3/issues/16\">https://github.com/Tanganelli/CoAPthon3/issues/16</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-c6fm-rgw4-8q73\">https://github.com/advisories/GHSA-c6fm-rgw4-8q73</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/coapthon3/PYSEC-2019-166.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/coapthon3/PYSEC-2019-166.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-c6fm-rgw4-8q73",
            "title": "[CoAPthon3] CoAPthon3 vulnerable to Deserialization of Untrusted Data",
            "date_modified": "2024-09-06T15:42:54.000Z",
            "date_published": "2019-04-08T15:18:57.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-c6fm-rgw4-8q73"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A NULL pointer dereference (DoS) Vulnerability was found in the function <code>aubio_source_avcodec_readframe</code> in io/source_avcodec.c of aubio, which may lead to DoS when playing a crafted audio file.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-17554\">https://nvd.nist.gov/vuln/detail/CVE-2017-17554</a></li>\n<li><a href=\"https://github.com/IvanCql/vulnerability/blob/master/An%20NULL%20pointer%20dereference(DoS)%20Vulnerability%20was%20found%20in%20function%20%20aubio_source_avcodec_readframe%20of%20aubio.md\">https://github.com/IvanCql/vulnerability/blob/master/An%20NULL%20pointer%20dereference(DoS)%20Vulnerability%20was%20found%20in%20function%20%20aubio_source_avcodec_readframe%20of%20aubio.md</a></li>\n<li><a href=\"https://github.com/aubio/aubio/commit/a81b12a3b4174953b3bc7ef4c37103f4d5636740\">https://github.com/aubio/aubio/commit/a81b12a3b4174953b3bc7ef4c37103f4d5636740</a></li>\n<li><a href=\"https://github.com/aubio/aubio/blob/0.4.7/ChangeLog\">https://github.com/aubio/aubio/blob/0.4.7/ChangeLog</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/aubio/PYSEC-2017-76.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/aubio/PYSEC-2017-76.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-45h5-cqqw-9rjw\">https://github.com/advisories/GHSA-45h5-cqqw-9rjw</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-45h5-cqqw-9rjw",
            "title": "[aubio] Aubio is vulnerable to a NULL pointer dereference",
            "date_modified": "2024-09-06T15:28:38.000Z",
            "date_published": "2022-05-14T03:07:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-45h5-cqqw-9rjw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>DNS rebinding is a method of manipulating resolution of domain names to let the initial DNS query hits an address and the second hits another one. For instance the host <code>make-190.119.176.200-rebind-127.0.0.1-rr.1u.ms</code>  would be initially resolved to <code>190.119.176.200</code> and the next DNS issue to <code>127.0.0.1</code>. Please notice the following in the latest codebase:</p>\n<pre><code class=\"language-python\">def is_private_url(url: str):\n    \"\"\"\n    Raises exception if url is private\n\n    :param url: url to check\n    \"\"\"\n\n    hostname = urlparse(url).hostname\n    if not hostname:\n        # Unable to find hostname in url\n        return True\n    ip = socket.gethostbyname(hostname)\n    return ipaddress.ip_address(ip).is_private\n</code></pre>\n<p>As you can see, during the call to <code>is_private_url()</code> the initial DNS query would be issued by <code>ip = socket.gethostbyname(hostname)</code> to an IP (public one) and then due to DNS Rebinding, the next GET request would goes to the private one.</p>\n<h3 id=\"poc\">PoC</h3>\n<pre><code class=\"language-python\">from flask import Flask, request, jsonify\nfrom urllib.parse import urlparse\nimport socket\nimport ipaddress\nimport requests\n\napp = Flask(__name__)\n\n\ndef is_private_url(url: str):\n    \"\"\"\n    Raises exception if url is private\n\n    :param url: url to check\n    \"\"\"\n\n    hostname = urlparse(url).hostname\n    if not hostname:\n        # Unable to find hostname in url\n        return True\n    ip = socket.gethostbyname(hostname)\n    if ipaddress.ip_address(ip).is_private:\n        raise Exception(f\"Private IP address found for {url}\")\n\n\n@app.route(\"/\", methods=[\"GET\"])\ndef index():\n    return \"http://127.0.0.1:5000/check_private_url?url=https://www.google.Fr\"\n\n\n@app.route(\"/check_private_url\", methods=[\"GET\"])\ndef check_private_url():\n    url = request.args.get(\"url\")\n\n    if not url:\n        return jsonify({\"error\": 'Missing \"url\" parameter'}), 400\n\n    try:\n        is_private_url(url)\n        response = requests.get(url)\n\n        return jsonify(\n            {\n                \"url\": url,\n                \"is_private\": False,\n                \"text\": response.text,\n                \"status_code\": response.status_code,\n            }\n        )\n    except Exception as e:\n        return jsonify({\"url\": url, \"is_private\": True, \"error\": str(e)})\n\n\nif __name__ == \"__main__\":\n    app.run(debug=True)\n</code></pre>\n<p>After running the poc.py with flask installed, consider visiting the following URLs:</p>\n<ol>\n<li><a href=\"http://127.0.0.1:5000/check_private_url?url=https://www.example.com\">http://127.0.0.1:5000/check_private_url?url=https://www.example.com</a> since it is in the public space, you would get <code>is_private: false</code> and the GET request would be issued to the <a href=\"http://www.Example.com\">www.Example.com</a> website.</li>\n<li><a href=\"http://127.0.0.1:5000/check_private_url?url=http://localhost:8667\">http://127.0.0.1:5000/check_private_url?url=http://localhost:8667</a>, this one the address is private, you would get <code>is_private: true</code></li>\n<li><a href=\"http://127.0.0.1:5000/check_private_url?url=http://make-190.119.176.214-rebind-127.0.0.1-rr.1u.ms:8667/\">http://127.0.0.1:5000/check_private_url?url=http://make-190.119.176.214-rebind-127.0.0.1-rr.1u.ms:8667/</a> But this one, it initially returns the public IP <code>190.119.176.214</code> and then DNS rebind into the network location <code>127.0.0.1:8667</code>.</li>\n</ol>\n<p>I set up a simple HTTP server at <code>127.0.0.1:8667</code>, you can notice the results of the PoC in the next screenshot:</p>\n<pre><code>{\n  \"is_private\": false,\n  \"status_code\": 200,\n  \"text\": \"&lt;pre&gt;\\n&lt;a href=\\\"poc.py\\\"&gt;poc.py&lt;/a&gt;\\n&lt;/pre&gt;\\n\",\n  \"url\": \"http://make-190.119.176.214-rebind-127.0.0.1-rr.1u.ms:8667/\"\n}\n</code></pre>\n<h3 id=\"impact\">Impact</h3>\n<ul>\n<li>Bypass the SSRF protection on the whole website with DNS Rebinding.</li>\n<li>DoS too.</li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/mindsdb/mindsdb/security/advisories/GHSA-4jcv-vp96-94xr\">https://github.com/mindsdb/mindsdb/security/advisories/GHSA-4jcv-vp96-94xr</a></li>\n<li><a href=\"https://github.com/mindsdb/mindsdb/commit/5f7496481bd3db1d06a2d2e62c0dce960a1fe12b\">https://github.com/mindsdb/mindsdb/commit/5f7496481bd3db1d06a2d2e62c0dce960a1fe12b</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-24759\">https://nvd.nist.gov/vuln/detail/CVE-2024-24759</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-4jcv-vp96-94xr\">https://github.com/advisories/GHSA-4jcv-vp96-94xr</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-4jcv-vp96-94xr",
            "title": "[mindsdb] MindsDB Vulnerable to Bypass of SSRF Protection with DNS Rebinding",
            "date_modified": "2024-09-05T18:39:04.000Z",
            "date_published": "2024-09-05T16:37:56.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-4jcv-vp96-94xr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An Improper Output Neutralization for Logs flaw was found in Ansible when using the uri module, where sensitive data is exposed to content and json output. This flaw allows an attacker to access the logs or outputs of performed tasks to read keys used in playbooks from other users within the uri module. The highest threat from this vulnerability is to data confidentiality.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-14330\">https://nvd.nist.gov/vuln/detail/CVE-2020-14330</a></li>\n<li><a href=\"https://github.com/ansible/ansible/issues/68400\">https://github.com/ansible/ansible/issues/68400</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14330\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14330</a></li>\n<li><a href=\"https://www.debian.org/security/2021/dsa-4950\">https://www.debian.org/security/2021/dsa-4950</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/69653\">https://github.com/ansible/ansible/pull/69653</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/e0f25a2b1f9e6c21f751ba0ed2dc2eee2152983e\">https://github.com/ansible/ansible/commit/e0f25a2b1f9e6c21f751ba0ed2dc2eee2152983e</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-785x-qw4v-6872\">https://github.com/advisories/GHSA-785x-qw4v-6872</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-3.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-3.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-785x-qw4v-6872",
            "title": "[ansible] Improper Output Neutralization and Improper Encoding or Escaping of Output for Logs in ansible",
            "date_modified": "2024-09-05T00:44:54.000Z",
            "date_published": "2022-02-09T22:00:08.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-785x-qw4v-6872"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in ansible. ansible.cfg is read from the current working directory which can be altered to make it point to a plugin or a module path under the control of an attacker, thus allowing the attacker to execute arbitrary code.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-10875\">https://nvd.nist.gov/vuln/detail/CVE-2018-10875</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHBA-2018:3788\">https://access.redhat.com/errata/RHBA-2018:3788</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2150\">https://access.redhat.com/errata/RHSA-2018:2150</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2151\">https://access.redhat.com/errata/RHSA-2018:2151</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2152\">https://access.redhat.com/errata/RHSA-2018:2152</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2166\">https://access.redhat.com/errata/RHSA-2018:2166</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2321\">https://access.redhat.com/errata/RHSA-2018:2321</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2585\">https://access.redhat.com/errata/RHSA-2018:2585</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:0054\">https://access.redhat.com/errata/RHSA-2019:0054</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html\">https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4396\">https://www.debian.org/security/2019/dsa-4396</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html\">http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/42070\">https://github.com/ansible/ansible/pull/42070</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/43583\">https://github.com/ansible/ansible/pull/43583</a></li>\n<li><a href=\"https://web.archive.org/web/20201130165946/http://www.securitytracker.com/id/1041396\">https://web.archive.org/web/20201130165946/http://www.securitytracker.com/id/1041396</a></li>\n<li><a href=\"https://github.com/ansible/ansible/issues/42388\">https://github.com/ansible/ansible/issues/42388</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/4cecbe81adbc655d7ab734165d3ac539f8ba5981\">https://github.com/ansible/ansible/commit/4cecbe81adbc655d7ab734165d3ac539f8ba5981</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/f32c42c37aaf7b9db93ea3151b2f42a0c4bd8172\">https://github.com/ansible/ansible/commit/f32c42c37aaf7b9db93ea3151b2f42a0c4bd8172</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/ff980afefdbe4ceb828bdb1bb2eef03cf616bf63\">https://github.com/ansible/ansible/commit/ff980afefdbe4ceb828bdb1bb2eef03cf616bf63</a></li>\n<li><a href=\"https://usn.ubuntu.com/4072-1\">https://usn.ubuntu.com/4072-1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-43.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-43.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fc4h-467w-46rh\">https://github.com/advisories/GHSA-fc4h-467w-46rh</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fc4h-467w-46rh",
            "title": "[ansible] Ansible Arbitrary Code Execution",
            "date_modified": "2024-09-05T00:43:13.000Z",
            "date_published": "2022-05-13T01:07:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fc4h-467w-46rh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in ansible. ansible.cfg is read from the current working directory which can be altered to make it point to a plugin or a module path under the control of an attacker, thus allowing the attacker to execute arbitrary code.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-10875\">https://nvd.nist.gov/vuln/detail/CVE-2018-10875</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHBA-2018:3788\">https://access.redhat.com/errata/RHBA-2018:3788</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2150\">https://access.redhat.com/errata/RHSA-2018:2150</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2151\">https://access.redhat.com/errata/RHSA-2018:2151</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2152\">https://access.redhat.com/errata/RHSA-2018:2152</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2166\">https://access.redhat.com/errata/RHSA-2018:2166</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2321\">https://access.redhat.com/errata/RHSA-2018:2321</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2585\">https://access.redhat.com/errata/RHSA-2018:2585</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:0054\">https://access.redhat.com/errata/RHSA-2019:0054</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html\">https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4396\">https://www.debian.org/security/2019/dsa-4396</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html\">http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/42070\">https://github.com/ansible/ansible/pull/42070</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/43583\">https://github.com/ansible/ansible/pull/43583</a></li>\n<li><a href=\"https://web.archive.org/web/20201130165946/http://www.securitytracker.com/id/1041396\">https://web.archive.org/web/20201130165946/http://www.securitytracker.com/id/1041396</a></li>\n<li><a href=\"https://github.com/ansible/ansible/issues/42388\">https://github.com/ansible/ansible/issues/42388</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/4cecbe81adbc655d7ab734165d3ac539f8ba5981\">https://github.com/ansible/ansible/commit/4cecbe81adbc655d7ab734165d3ac539f8ba5981</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/f32c42c37aaf7b9db93ea3151b2f42a0c4bd8172\">https://github.com/ansible/ansible/commit/f32c42c37aaf7b9db93ea3151b2f42a0c4bd8172</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/ff980afefdbe4ceb828bdb1bb2eef03cf616bf63\">https://github.com/ansible/ansible/commit/ff980afefdbe4ceb828bdb1bb2eef03cf616bf63</a></li>\n<li><a href=\"https://usn.ubuntu.com/4072-1\">https://usn.ubuntu.com/4072-1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-43.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-43.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fc4h-467w-46rh\">https://github.com/advisories/GHSA-fc4h-467w-46rh</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fc4h-467w-46rh",
            "title": "[ansible] Ansible Arbitrary Code Execution",
            "date_modified": "2024-09-05T00:43:13.000Z",
            "date_published": "2022-05-13T01:07:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fc4h-467w-46rh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in ansible. ansible.cfg is read from the current working directory which can be altered to make it point to a plugin or a module path under the control of an attacker, thus allowing the attacker to execute arbitrary code.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-10875\">https://nvd.nist.gov/vuln/detail/CVE-2018-10875</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHBA-2018:3788\">https://access.redhat.com/errata/RHBA-2018:3788</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2150\">https://access.redhat.com/errata/RHSA-2018:2150</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2151\">https://access.redhat.com/errata/RHSA-2018:2151</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2152\">https://access.redhat.com/errata/RHSA-2018:2152</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2166\">https://access.redhat.com/errata/RHSA-2018:2166</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2321\">https://access.redhat.com/errata/RHSA-2018:2321</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2585\">https://access.redhat.com/errata/RHSA-2018:2585</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:0054\">https://access.redhat.com/errata/RHSA-2019:0054</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html\">https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4396\">https://www.debian.org/security/2019/dsa-4396</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html\">http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/42070\">https://github.com/ansible/ansible/pull/42070</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/43583\">https://github.com/ansible/ansible/pull/43583</a></li>\n<li><a href=\"https://web.archive.org/web/20201130165946/http://www.securitytracker.com/id/1041396\">https://web.archive.org/web/20201130165946/http://www.securitytracker.com/id/1041396</a></li>\n<li><a href=\"https://github.com/ansible/ansible/issues/42388\">https://github.com/ansible/ansible/issues/42388</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/4cecbe81adbc655d7ab734165d3ac539f8ba5981\">https://github.com/ansible/ansible/commit/4cecbe81adbc655d7ab734165d3ac539f8ba5981</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/f32c42c37aaf7b9db93ea3151b2f42a0c4bd8172\">https://github.com/ansible/ansible/commit/f32c42c37aaf7b9db93ea3151b2f42a0c4bd8172</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/ff980afefdbe4ceb828bdb1bb2eef03cf616bf63\">https://github.com/ansible/ansible/commit/ff980afefdbe4ceb828bdb1bb2eef03cf616bf63</a></li>\n<li><a href=\"https://usn.ubuntu.com/4072-1\">https://usn.ubuntu.com/4072-1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-43.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-43.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fc4h-467w-46rh\">https://github.com/advisories/GHSA-fc4h-467w-46rh</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fc4h-467w-46rh",
            "title": "[ansible] Ansible Arbitrary Code Execution",
            "date_modified": "2024-09-05T00:43:13.000Z",
            "date_published": "2022-05-13T01:07:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fc4h-467w-46rh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in the Ansible Engine when using module_args. Tasks executed with check mode (--check-mode) do not properly neutralize sensitive data exposed in the event data. This flaw allows unauthorized users to read this data. The highest threat from this vulnerability is to confidentiality.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-14332\">https://nvd.nist.gov/vuln/detail/CVE-2020-14332</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/71033\">https://github.com/ansible/ansible/pull/71033</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332</a></li>\n<li><a href=\"https://www.debian.org/security/2021/dsa-4950\">https://www.debian.org/security/2021/dsa-4950</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#security-fixes-4\">https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#security-fixes-4</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes-6\">https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes-6</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/291f94934c8c49eef85e6539087f2dfcd001fe4f\">https://github.com/ansible/ansible/commit/291f94934c8c49eef85e6539087f2dfcd001fe4f</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a\">https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/714cd2ad2eff7f003d728414afcb91591fad5d9a\">https://github.com/ansible/ansible/commit/714cd2ad2eff7f003d728414afcb91591fad5d9a</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-j667-c2hm-f2wp\">https://github.com/advisories/GHSA-j667-c2hm-f2wp</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#security-fixes-3\">https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#security-fixes-3</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-4.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-4.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-j667-c2hm-f2wp",
            "title": "[ansible] Insertion of Sensitive Information into Log File and Improper Output Neutralization for Logs in ansible",
            "date_modified": "2024-09-05T00:37:45.000Z",
            "date_published": "2022-02-09T21:59:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-j667-c2hm-f2wp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in the Ansible Engine when using module_args. Tasks executed with check mode (--check-mode) do not properly neutralize sensitive data exposed in the event data. This flaw allows unauthorized users to read this data. The highest threat from this vulnerability is to confidentiality.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-14332\">https://nvd.nist.gov/vuln/detail/CVE-2020-14332</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/71033\">https://github.com/ansible/ansible/pull/71033</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332</a></li>\n<li><a href=\"https://www.debian.org/security/2021/dsa-4950\">https://www.debian.org/security/2021/dsa-4950</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#security-fixes-4\">https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#security-fixes-4</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes-6\">https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes-6</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/291f94934c8c49eef85e6539087f2dfcd001fe4f\">https://github.com/ansible/ansible/commit/291f94934c8c49eef85e6539087f2dfcd001fe4f</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a\">https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/714cd2ad2eff7f003d728414afcb91591fad5d9a\">https://github.com/ansible/ansible/commit/714cd2ad2eff7f003d728414afcb91591fad5d9a</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-j667-c2hm-f2wp\">https://github.com/advisories/GHSA-j667-c2hm-f2wp</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#security-fixes-3\">https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#security-fixes-3</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-4.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-4.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-j667-c2hm-f2wp",
            "title": "[ansible] Insertion of Sensitive Information into Log File and Improper Output Neutralization for Logs in ansible",
            "date_modified": "2024-09-05T00:37:45.000Z",
            "date_published": "2022-02-09T21:59:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-j667-c2hm-f2wp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in the Ansible Engine when using module_args. Tasks executed with check mode (--check-mode) do not properly neutralize sensitive data exposed in the event data. This flaw allows unauthorized users to read this data. The highest threat from this vulnerability is to confidentiality.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-14332\">https://nvd.nist.gov/vuln/detail/CVE-2020-14332</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/71033\">https://github.com/ansible/ansible/pull/71033</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332</a></li>\n<li><a href=\"https://www.debian.org/security/2021/dsa-4950\">https://www.debian.org/security/2021/dsa-4950</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#security-fixes-4\">https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#security-fixes-4</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes-6\">https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes-6</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/291f94934c8c49eef85e6539087f2dfcd001fe4f\">https://github.com/ansible/ansible/commit/291f94934c8c49eef85e6539087f2dfcd001fe4f</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a\">https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/714cd2ad2eff7f003d728414afcb91591fad5d9a\">https://github.com/ansible/ansible/commit/714cd2ad2eff7f003d728414afcb91591fad5d9a</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-j667-c2hm-f2wp\">https://github.com/advisories/GHSA-j667-c2hm-f2wp</a></li>\n<li><a href=\"https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#security-fixes-3\">https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#security-fixes-3</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-4.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-4.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-j667-c2hm-f2wp",
            "title": "[ansible] Insertion of Sensitive Information into Log File and Improper Output Neutralization for Logs in ansible",
            "date_modified": "2024-09-05T00:37:45.000Z",
            "date_published": "2022-02-09T21:59:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-j667-c2hm-f2wp"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}